### PR TITLE
part of cam6_4_075: cam_dev silhs bug fix

### LINKED ISSUE #844: Crash when running cam_dev with SILHS
### What happened?

CAM crashes when running -silhs with -phys cam_dev.  The immediate error is coming from subcol.F90, in the subcol_field_avg interface, from the [subcol_field_avg_2dr subroutine](https://github.com/ESCOMP/CAM/blob/ea6d88db42902a85bf6e126dc22f9c42ee6edd15/src/physics/cam/subcol.F90#L392-L394).  Traceback indicates that the problem originates from cam_dev/micro_pumas_cam.F90, specifically where we are trying to call subcol_field_avg on the [proc_rates derived type](https://github.com/ESCOMP/CAM/blob/ea6d88db42902a85bf6e126dc22f9c42ee6edd15/src/physics/cam_dev/micro_pumas_cam.F90#L2519).  This derived type is not present in cam/micro_pumas_cam.F90, which I think explains why this isn't a problem in -phys cam6 runs.  I *think* the problem is that when proc_rates is allocated, [it's allocated with ncol in the first slot](https://github.com/ESCOMP/CAM/blob/ea6d88db42902a85bf6e126dc22f9c42ee6edd15/src/physics/cam_dev/micro_pumas_cam.F90#L1852), but the averaging subroutine requires that the first slot have dimension pcols*psubcols.  Not being familiar with the code, it's not obvious to me what the right solution to this is.  I tried simply allocating proc_rates with psetcols, but this created a bunch of NaNs in CLUBB and the model crashed.

### What are the steps to reproduce the bug?

Set up a new case, and set CAM_CONFIG_OPTS="-phys cam_dev -silhs" I think is all it should take.

### What CAM tag were you using?

cam6_3_114

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/stepheba/silhstest_camdev

### Will you be addressing this bug yourself?

Any CAM SE can do this

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by bstephens82**
Resolves #844.

This additional code in cam_dev/micro_pumas_cam.F90 will allow a run using cam_dev and SILHS, i.e. something like
~~~
CAM_CONFIG_OPTS="-phys cam_dev -silhs -psubcols 4"
~~~
to run without hitting the [pcols*psubcols abort error](https://github.com/ESCOMP/CAM/blob/776400d2a56d1c95551c9782810e4120ecb4f111/src/physics/cam/subcol.F90#L393) in subcol.F90.  This code is not super familiar to me, so my proposed fix (worked out with advice from @cacraigucar) may not be optimal yet, however I've tested it and it does work to get past the error and the model appears to be running normally afterward although I have not performed a months-long test yet.  

Furthermore, this will **not** resolve a separate problem which seems more general to any subcolumns, where subcolumns print as zeros in the netcdf history files.  See issue #1015 for more info about that.

### CODE REVIEW

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 1]
```diff
@@ -1524,6 +1524,47 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
    real(r8), pointer :: degrau(:,:)       ! Graupel effective diameter (m)
    real(r8), pointer :: bergstot(:,:)     ! Conversion of cloud water to snow from bergeron
 
+   real(r8) :: evapsnow_sc(state%psetcols,pver-top_lev+1)
```
Comment (Katetc) [inline src/physics/cam_dev/micro_pumas_cam.F90:1527]: Would it be possible to add a comment block before all of these explaining that you are duplicating the variables within the proc_rates DDT to get the averaging code to work for diagnostics and no other reason? Thanks!

**Review by Katetc — APPROVED** [review]
I am kind of sad about this change because we created the DDT to reduce the amount of code related to declaring all of these variables, and here it is again. I think it would be better to be able to do this within the DDT - ie, have some accessor that gives back the variable in the appropriate dimensions for subcolumn averaging. But, that would take a good bit more work than anybody has time for here, and this fixes the problem, so I'm ok with it.

File: src/physics/cam_dev/micro_pumas_cam.F90 (hunk 1 above)
Comment (cacraigucar) [reply src/physics/cam_dev/micro_pumas_cam.F90:1527]: @bstephens82 - @nusbaume will be bringing this into his misc tag that he will be making in a day or two.  Do you want to add this comment, or should Jesse just add it when he brings it into his misc PR?

Comment (bstephens82) [reply src/physics/cam_dev/micro_pumas_cam.F90:1527]: I assume the easiest thing would be for Jesse to just add it? It's been a good while since I've looked at this.

Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90:1527]: That's perfect, thanks so much!
