### PR TITLE
cam6_4_143: Extended non-LTE CO2 cooling parameterization

### LINKED ISSUE #1358: Extended CO2 non-LTE cooling
### What is the feature/what would you like to discuss?

Implement the option to use an extended parameterization of CO2 cooling described here:
https://doi.org/10.5194/egusphere-2023-2424, by Manuel Lopez-Puertas, et al.

Some test results are posted here:
https://github.com/NCAR/wawg_dev/issues/95

### Is there anyone in particular you want to be part of this conversation?

_No response_

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by fvitt**
Closes #1358

### CODE REVIEW

File: src/physics/waccm/nlte_extco2.F90 [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+  subroutine nlte_extco2_init(co2_mw,n2_mw,o1_mw,o2_mw)
+    use ref_pres, only: pref_mid
+
+    ! Input variables
+    real(r8), intent(in) :: o1_mw     ! O molecular weight
+    real(r8), intent(in) :: o2_mw     ! O2 molecular weight
+    real(r8), intent(in) :: co2_mw    ! CO2 molecular weight
+    real(r8), intent(in) :: n2_mw     ! N2 molecular weight
+
+#ifdef EXT_CO2_COOL
```
Comment (cacraigucar) [inline src/physics/waccm/nlte_extco2.F90]: I'm wondering about why you felt the need to encapsulate this code within a #ifdef.  We try to avoid using these directives and backtracing this particular routine, it is only called when `nlte_use_extco2` is true.  I believe this #ifdef is not needed.   I've not analyzed the other #ifdef directives, but I would suggest there might also might be others that are not needed.  If all can be removed, please remove the definition from configure as well.

File: bld/namelist_files/namelist_defaults_cam.xml [hunk 2]
```diff
@@ -182,7 +182,7 @@
 <ncdata hgrid="ne16np4"  nlev="126" waccmx="1"                                 >atm/waccm/ic/waccmx_ne16np4_126L_c200108.nc</ncdata>
 <ncdata hgrid="ne16np4"  nlev="126" waccmx="1" aquaplanet="1"                  >atm/waccm/ic/waccmx_aqua_ne16np4_126L_c191108.nc</ncdata>
 <ncdata hgrid="ne16np4"  nlev="126" waccmx="1" aquaplanet="1" ionosphere="none">atm/waccm/ic/waccmx4_neutral_aquap_ne16np4_126lev_c200827.nc</ncdata>
-<ncdata hgrid="ne16np4"  nlev="130" waccmx="1"     >atm/waccm/ic/waccmx_ne16pg3_L130_c250318.nc</ncdata>
+<ncdata hgrid="ne16np4"  nlev="130" waccmx="1"     >atm/waccm/ic/FX2000_ne16pg3_spinup01.cam.i.0002-01-01_c251215.nc</ncdata>
```
Comment (cacraigucar) [inline bld/namelist_files/namelist_defaults_cam.xml:185]: Has this file been "rimport"ed?

File: bld/namelist_files/namelist_definition.xml [hunk 3]
```diff
@@ -7994,6 +7994,13 @@ Call ALI-ARMS every X timesteps
 Default: 1
 </entry>
 
+<entry id="nlte_use_extco2" type="logical" category="waccm_phys"
+       group="radheat_nl" valid_values="" >
+If TRUE, then use the extended CO2 scheme of Lopez-Puertas et al. 2024 as an alernative method of computing non-LTE
```
Comment (cacraigucar) [inline bld/namelist_files/namelist_definition.xml:7999]: Since this is a comment which will show up on a web page, would it be appropriate to include the DOI here also?

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: src/physics/waccm/nlte_extco2.F90 (hunk 1 above)
Comment (fvitt) [reply src/physics/waccm/nlte_extco2.F90]: The external code ext_co2_cooling code does not compile with NAG compiler.

Comment (cacraigucar) [reply src/physics/waccm/nlte_extco2.F90]: With that in mind, does it make sense to only #ifdef the calls and the use statements (keep it contained around the code which only needed to not compiled)?

Comment (fvitt) [reply src/physics/waccm/nlte_extco2.F90]: I would prefer not to add the history fields when the model is not configured to use the extended cooling method.

File: bld/namelist_files/namelist_defaults_cam.xml (hunk 2 above)
Comment (fvitt) [reply bld/namelist_files/namelist_defaults_cam.xml:185]: done

File: bld/namelist_files/namelist_definition.xml (hunk 3 above)
Comment (fvitt) [reply bld/namelist_files/namelist_definition.xml:7999]: DOI has been added here

File: src/physics/waccm/nlte_extco2.F90 (hunk 1 above)
Comment (cacraigucar) [reply src/physics/waccm/nlte_extco2.F90]: Is there something preventing you from passing in the variable `nlte_use_extco2` and using it to determine if the history fields are being set or not?

Comment (fvitt) [reply src/physics/waccm/nlte_extco2.F90]: I have concluded with the checks in higher level modules, the cpp ifdefs in init routine was not necessary.

**Review by cacraigucar — APPROVED** [review]
