### PR TITLE
cam6_4_156: fixes to prescribed volcanic aerosols

### LINKED ISSUE #1493: An updated IC file is needed for the B1850C_MTt4s compset
### Issue Type

Other (please describe below)

### Issue Description

Update T4S2 chemistry IC file for 1850.  Should use file:
```
/glade/campaign/cesm/cesmdata/cseg/inputdata/atm/cam/inic/se/b.e30_alpha07c_cesm.B1850C_MTt4s.ne30_t232_wgx3.251.001.cam.i.0032-01-01_c260304.nc
```

Update ncdata in use case file
```
  bld/namelist_files/use_cases/1850_trop_strat_t4s_cam7.xml
```

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

### PR DESCRIPTION
**Pull request by fvitt**
Corrections to mode 5 of the prescribed volcanic forcings and update to MTt4s 1850 IC file.

Closes #1493 and #1494

Some test results can be viewed here:
 https://docs.google.com/presentation/d/1Bje5NJr0riKG4ii-oRXxgq60ZTPNhU_7/edit?slide=id.g3cca65dbc48_1_55#slide=id.g3cca65dbc48_1_55

### CODE REVIEW

**Comment by fvitt** [comment]
@tilmes and @cecilehannay 
What forcings datasets do we currently have?  Do we need to automatically set the correct `rad_climate` setting, including `VOLC_MMR`, for only some of the `MTso` compsets, such as 1850 and HIST?

File: src/physics/cam/aerosol_optics_cam.F90 [hunk 1]
```diff
@@ -941,9 +946,9 @@ subroutine aerosol_optics_cam_sw(list_idx, state, pbuf, nnite, idxnite, tauxar,
              bam_cnt = bam_cnt+1
              call aer_vis_diag_out(lchnk, ncol, nnite, idxnite, bam_cnt, taubam, &
                   list_idx, troplev)
-          else
-             call output_bin_diags()
-          end if
+          endif
+
+          call output_bin_diags()
```
Comment (cacraigucar) [inline src/physics/cam/aerosol_optics_cam.F90:951]: I haven't attempted to look at the scope of this being moved out of the "else" block.  I just wanted to confirm that calling `output_bin_diags` every time this section of the code is hit is an appropriate change.

File: cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam [hunk 2]
```diff
@@ -18,7 +18,7 @@ rad_climate =
  'N:VOLC_MMR1:$DIN_LOC_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.6_mode1_c210211.nc',
  'N:VOLC_MMR2:$DIN_LOC_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.6_mode2_c210211.nc',
  'N:VOLC_MMR3:$DIN_LOC_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode3_c210211.nc',
- 'N:VOLC_MMR5:$DIN_LOC_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode3_c210211.nc'
+ 'N:VOLC_MMR5:$DIN_LOC_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode5_c260228.nc'
```
Comment (cacraigucar) [inline cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam:21]: Just a reminder to make sure this has been `rimport`ed, if this is the final version of this file.  It may have already been done, I've not checked.

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: src/physics/cam/aerosol_optics_cam.F90 (hunk 1 above)
Comment (fvitt) [reply src/physics/cam/aerosol_optics_cam.F90:951]: Yes, this is intended.

File: cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam (hunk 2 above)
Comment (fvitt) [reply cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam:21]: Done.

**Comment by cacraigucar** [comment]
@fvitt - Thanks for answering my questions.  I will reserve my final approval until you let me know your modifications are done.

File: bld/namelist_files/use_cases/1850_cam_mt.xml [hunk 3]
```diff
@@ -87,6 +87,17 @@
...
+  'A:Q:H2O', 'N:O2:O2', 'A:CO2:CO2', 'N:ozone:O3', 'A:N2O:N2O', 'A:CH4:CH4', 'N:CFC11STAR:CFC11', 'A:CFC12:CFC12',
+  'M:mam4_mode1:$INPUTDATA_ROOT/atm/cam/physprops/mam4_mode1_rrtmg_aeronetdust_sig1.6_dgnh.48_c140304.nc',
+  'M:mam4_mode2:$INPUTDATA_ROOT/atm/cam/physprops/mam4_mode2_rrtmg_aitkendust_c141106.nc',
+  'M:mam4_mode3:$INPUTDATA_ROOT/atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_c141106.nc',
+  'M:mam4_mode4:$INPUTDATA_ROOT/atm/cam/physprops/mam4_mode4_rrtmg_c130628.nc',
+  'N:VOLC_MMR1:$INPUTDATA_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.6_mode1_c210211.nc',
+  'N:VOLC_MMR2:$INPUTDATA_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.6_mode2_c210211.nc',
+  'N:VOLC_MMR3:$INPUTDATA_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode3_c210211.nc',
+  'N:VOLC_MMR5:$INPUTDATA_ROOT/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode5_c260228.nc'
+</rad_climate>
```
Comment (fvitt) [inline bld/namelist_files/use_cases/1850_cam_mt.xml:100]: I set `rad_climate` to include `VOLC_MMR5` here in this use case file since we only have new forcings only for 1850.  When we have a transient forcings we should consider setting `rad_climate` correctly in `build-namelist`.

**Comment by fvitt** [comment]
> @fvitt - Thanks for answering my questions. I will reserve my final approval until you let me know your modifications are done.

My mods are done.  This is ready for review.  I will start regression tests.

**Review by cacraigucar — APPROVED** [review]

**Comment by cacraigucar** [comment]
This was discussed with @cecilehannay, @JulioTBacmeister and @dlawrenncar all approved this PR going into CAM
