### PR TITLE
cam6_3_043: Read ncdata file with either ncol or ncol_d dimension (SE dycore)

### LINKED ISSUE #339: SE dycore not reading default ncdata for ne30np4 F2000
Running the ne30_ne30_mg17 grid with a F2000climo compset errors out:

` ERROR: check_file_layout: ERROR: either ncol or ncol_d dimension not found in ncdata file`

This same default ncdata is used for ne30pg2, ne30pg3 & ne30np4. This file has a dimension size ncol_d = 48602:
/glade/p/cesmdata/cseg/inputdata/atm/cam/inic/se/F2000climo_ne30pg3_mg17_01-01-00000_c200424.nc

This file works fine for ne30pg2 and ne30pg3, as ncol_d = 48602 is consistent with their definition of ncol_d. ne30np4 seems to not want ncol_d, but rather ncol = 48602, which is not present in this file.

ne30np4 runs fine if I instead point to this CAM-Chem inic, which has dimensions ncol = 48602:
/glade/p/cesmdata/cseg/inputdata/atm/cam/inic/se/f.e22.FC2010climo.ne30_ne30_mg17.cam6_2_022.001.cam.i.0016-01-01-00000_c200610.nc

@PeterHjortLauritzen

### PR DESCRIPTION
**Pull request by peverwhee**
Make ini_grid_hdim_name in dyn_grid public and use in dyn_comp so that GLL grids can use initial data files with ncol_d.

Closes #339

### CODE REVIEW

**Review by gold2718 — APPROVED** [review]
Looks good!
Have you tested this with both an `ncol_d` / `area_d` file and an `ncol` / `area` file?

**Review by cacraigucar — APPROVED** [review]

**Comment by peverwhee** [comment]
> Looks good! Have you tested this with both an `ncol_d` / `area_d` file and an `ncol` / `area` file?

yes - tested with both F2000climo_ne30pg3_mg17_01-01-00000_c200424.nc (ncol_d/area_d) and initial_data.cam.ne30.L32.RCEMIP_c20190507.nc (ncol/area) on izumi.

File: src/dynamics/se/dyn_comp.F90 [hunk 1]
```diff
@@ -2034,18 +2034,20 @@ subroutine check_file_layout(file, elem, dyn_cols, file_desc, dyn_ok, dimname)
...
-   character(len=max_fieldname_len) :: dimname2, coordname
+   character(len=max_fieldname_len) :: coordname
 
    character(len=*), parameter      :: sub = 'check_file_layout'
    !----------------------------------------------------------------------------
 
    ! Check that number of columns in IC file matches grid definition.
+   if (trim(ini_grid_hdim_name) == 'none') then
+      call endrun(sub//': ERROR: no horizontal dimension in initial data file. &
+         Cannot read data from file')
```
Comment (fvitt) [inline src/dynamics/se/dyn_comp.F90:2045]: Is this the correct syntax for continuing a string to the next line?

File: src/dynamics/se/dyn_grid.F90 [hunk 2]
```diff
@@ -62,6 +62,9 @@ module dyn_grid
 
 character(len=3), protected :: ini_grid_name
 
+! Name of horizontal grid dimension in initial file.
+character(len=6), protected :: ini_grid_hdim_name = ''
```
Comment (fvitt) [inline src/dynamics/se/dyn_grid.F90:66]: I don't see where `ini_grid_hdim_name` gets set.

Comment (gold2718) [reply src/dynamics/se/dyn_grid.F90:66]: It is set in the subroutine `get_hdim_name`.
Hmm, maybe we should use a different variable name instead of shadowing the module variable?

File: src/dynamics/se/dyn_comp.F90 (hunk 1 above)
Comment (peverwhee) [reply src/dynamics/se/dyn_comp.F90]: good call - fixed.

Comment (gold2718) [inline src/dynamics/se/dyn_comp.F90]: It is not illegal per se, however, the output is probably not what we want to say. How about:
```suggestion
      call endrun(sub//': ERROR: no horizontal dimension in initial data file. &
         &Cannot read data from file')
```

File: src/dynamics/se/dyn_grid.F90 (hunk 2 above)
Comment (peverwhee) [reply src/dynamics/se/dyn_grid.F90:66]: ini_grid_hdim_name was already being set (unrelated to my changes) on line 224. I just made that variable public.

Comment (fvitt) [reply src/dynamics/se/dyn_grid.F90:66]: OK thanks.  Maybe I needed more coffee to see it.

Comment (peverwhee) [reply src/dynamics/se/dyn_grid.F90:66]: @gold2718 we can do that. Why would we want to avoid shadowing the module variable? Because it could be changed in some future update without realizing how it affects the other module?

Comment (gold2718) [reply src/dynamics/se/dyn_grid.F90:66]: No technical reason, it is just by using `ini` in the variable names (`fh_ini`, `ini_grid_hdim_name`), it can give the impression that this routine is only for initial data files when it could, in principle, be used to examine any SE data file. If you do make the variable name changes, please update the comment ('the initial file') to express this more general usage possibility.

Comment (peverwhee) [reply src/dynamics/se/dyn_grid.F90:66]: ok. Is it ok that the grid name is ini_grid_name? It seems like changing ini_grid_hdim_name creates a weird mismatch since we use ini_grid_name in dyn_comp as well as ini_grid_hdim_name.

Comment (gold2718) [reply src/dynamics/se/dyn_grid.F90:66]: I was thinking `grid_hdim_name`.
Also, maybe `fh_ptr` instead of `fh_ini`.

Comment (peverwhee) [reply src/dynamics/se/dyn_grid.F90:66]: I agree. I guess my question is whether the grid name in dyn_grid should be ini_grid_name or just grid_name ?

Comment (gold2718) [reply src/dynamics/se/dyn_grid.F90:66]: I think the module variable names are all great, I am just looking at the dummy arguments in `get_hdim_name`. Does that address the question?

Comment (peverwhee) [reply src/dynamics/se/dyn_grid.F90:66]: it sure does!

Comment (peverwhee) [reply src/dynamics/se/dyn_grid.F90:66]: variable names changed.

**Review by fvitt — APPROVED** [review]

**Review by nusbaume — APPROVED** [review]
Looks good!  I just had one Fortran syntax question (which is probably better directed to @gold2718 ).

File: src/dynamics/se/dyn_comp.F90 [hunk 3]
```diff
@@ -2034,18 +2034,20 @@ subroutine check_file_layout(file, elem, dyn_cols, file_desc, dyn_ok, dimname)
...
-   character(len=max_fieldname_len) :: dimname2, coordname
+   character(len=max_fieldname_len) :: coordname
 
    character(len=*), parameter      :: sub = 'check_file_layout'
    !----------------------------------------------------------------------------
 
    ! Check that number of columns in IC file matches grid definition.
+   if (trim(ini_grid_hdim_name) == 'none') then
+      call endrun(sub//': ERROR: no horizontal dimension in initial data file. ' &
+         '&Cannot read data from file')
```
[the remark this answers is not in the document]
Comment (gold2718) [reply src/dynamics/se/dyn_comp.F90:2045]: It would be interesting to try but it is not what I recommended. My version is the Fortran 'break a line anywhere' get out of jail free card:
```suggestion
      call endrun(sub//': ERROR: no horizontal dimension in initial data file. &
         &Cannot read data from file')
```

[the remark this answers is not in the document]
Comment (peverwhee) [reply src/dynamics/se/dyn_comp.F90]: fixed.
