### PR TITLE
part of cam6_2_011: bug fix for including user chemmech file; update to latest git paths

### LINKED ISSUE #51: filepaths not updated to build new usr_mech file
ChemPreprocess.pm has old hardcoded paths referencing $cam_root/components/cam.

fix is to replace cam_root with cam_dir cfg_ref variable that is set properly during cam configure.

++  my $cam_dir = $cfg_ref->get('cam_dir');

--     ~~my $chem_preprocessor = "$cam_root/components/cam/chem_proc";~~                                                                                   
++    my $chem_preprocessor = "$cam_dir/chem_proc";

--      ~~$usr_mech_infile = "$cam_root/components/cam/src/chemistry/pp_${chem_pkg}/chem_mech.in";~~                                                    
++       $usr_mech_infile = "$cam_dir/src/chemistry/pp_${chem_pkg}/chem_mech.in";

I've run a smoke test to make sure nothing is broken and also verified that the fix does enable cesm to correctly build the Buildconf/camconf/chem_proc/cam.subs.tar file which wasn't being created before.  I will make a pull request.

jt

### PR DESCRIPTION
**Pull request by jtruesdal**
Closes #51

### CODE REVIEW

File: bld/perl5lib/Build/ChemPreprocess.pm [hunk 1]
```diff
@@ -39,6 +39,7 @@ sub chem_preprocess
     my $prog_species = $cfg_ref->get('prog_species');
     my $chem_pkg = $cfg_ref->get('chem');
     my $cam_root = $cfg_ref->get('cam_root');
```
Comment (nusbaume) [inline bld/perl5lib/Build/ChemPreprocess.pm]: It looks like nothing in this file uses "cam_root" anymore.  Might want to remove it?

Comment (jtruesdal) [reply bld/perl5lib/Build/ChemPreprocess.pm]: @nusbaume Cleanup is always a good idea.  I'll make a quick test and update my branch if everything looks OK.

**Comment by cacraigucar** [comment]
> Do we have a tag slot for this PR? Is someone going to do testing or can we slide this in with another tag? @jtruesdal, thanks for finding and fixing this but do not merge just yet.

John and I had already talked.  I told him to use the "next tag" tag and we will request that an upcoming tag bring this in (on both CAM branches).  Chris' development tag is far enough along, I don't want to perturb it, so it will probably go into the next one.

File: bld/perl5lib/Build/ChemPreprocess.pm (hunk 1 above)
Comment (nusbaume) [reply bld/perl5lib/Build/ChemPreprocess.pm]: Great, thanks @jtruesdal!  Otherwise everything else looks good to me, and thanks again for catching the bug.

**Comment by jtruesdal** [comment]
@cacraigucar I cleaned up the code as recommended by Jesse, tested it and pushed the branch back to git hub.  I think this is ready to go.
