### PR TITLE
 Misc bugs #1: rrtmg_state pointer, SCAM namelist, izumi compiler and TGIT test

### LINKED ISSUE #86: Cheyenne jobs randomly failing with deallocation
In some instances cheyenne jobs just fail with an unhelpful message that a deallocation is invalid as the pointer has not been allocated.  In some instances the job can fail on the first timestep and other times it can be later.  This different behavior can all happen with the exact same code base.

The jobs which fail with a traceback indicate that the deallocate at line 267 in rrtmg_state.F90 is failing.  While this appears to be valid code, there is something which is causing cheyenne to have random issues.

A couple of suggestions that could solve the random issue:
 - Remove the pointer attribute for the rstate variable
 - Introduce an "if allocated(rstate)" prior to the deallocate.

### LINKED ISSUE #130: SCAM6 namelist definitions inconsistent
### Summary of Issue:
The namelist variable scm_iop_lhflxshflxTg is specified as a logical, but string variables are given as valid values in namelist_definitions.xml. This is also the case for several other SCAM-specific namelist variables (scm_use_obs_qv,scm_force_latlon).
### Expected behavior and actual behavior:
An error is thrown at runtime that a logical (either .true. or .false.) is not a valid value for the variable.
### Steps to reproduce the problem. Include externals description file(s) and link to public repository):
Set scm_iop_lhflxshflxtg=.true. in user_nl_cam for any build using FSCAM compset.
### Screen output or log file showing the error message and context:
Screen Shot 2020-04-30 at 2 58 44 PM

### LINKED ISSUE #145: Updates to handle Izumi compiler and Cheyenne updates
Need to update the cime external and test_driver.sh to handle the updated libraries

### PR DESCRIPTION
**Pull request by cacraigucar**
Fix rrtmg_state pointer bug, correct SCAM6 namelist inconsistencies and update izumi compilers and TGIT test

Closes #86 
Closes #130 
Closes #145

Also updates TGIT regression test

### CODE REVIEW

**Review by fvitt — APPROVED** [review]

**Review by brian-eaton — APPROVED** [review]

**Review by nusbaume — APPROVED** [review]
Looks good, and thanks for fixing the TGIT error codes!  Just one question regarding a print statement.

File: src/control/scamMod.F90 [hunk 1]
```diff
@@ -303,6 +317,46 @@ subroutine scam_readnl(nlfile,single_column_in,scmlat_in,scmlon_in)
...
+              if (adv) then
+                 write (iulog, "(A18)") "'"//trim(scm_relax_fincl(i))//"',"
+              else
+                 write (iulog, "(A18)", ADVANCE="NO") "'"//trim(scm_relax_fincl(i))//"',"
+              end if
+           else
+              exit
+           end if
+        end do
+        print *
```
[the remark this answers is not in the document]
Comment (cacraigucar) [reply src/control/scamMod.F90:357]: Exactly - I saw that too!   I decided that because I am applying the exact changes from cam_development, I would leave it in.  We all missed it the first time around, but not now!

**Review by jtruesdal — APPROVED** [review]

File: doc/ChangeLog [hunk 2]
```diff
@@ -1,6 +1,94 @@
...
 ===============================================================
 
+Tag name:cam_cesm2_1_rel_46
+Originator(s): cacraig, fvitt, jet
+Date:
+One-line Summary: Fix rrtmg_state pointer bug, correct SCAM6 namelist inconsistencies and update izumi compilers and TGIT test
+
+Purpose of changes:
+Closes:
+    Workaround rrtmg_state pointer issue on cheyenne (issue #86)
```
Comment (gold2718) [inline doc/ChangeLog:11]: The new ChangeLog template says to include the issue text, but that is not what is written here. In fact, this text should be down in the modified section where an explanation of the changes should be.
Speaking of the new ChangeLog template, it would not hurt to update that in this branch for future maintenance tags.

File: doc/ChangeLog [hunk 3]
```diff
@@ -1,6 +1,94 @@
...
+    SCAM6 namelist definitions inconsistent (issue #130)
+    Updates for using latest izumi compilers (issue #146)
```
Comment (gold2718) [inline doc/ChangeLog:13]: This is a PR, not an issue. There should be an issue for these changes.

File: doc/ChangeLog [hunk 4]
```diff
@@ -1,6 +1,94 @@
...
+Code reviewed by:
+
+List all files eliminated:
+
+List all files added and what they do:
+
+List all existing files that have been modified, and describe the changes:
+        modified:   src/physics/rrtmg/radiation.F90
+        modified:   src/physics/rrtmg/rrtmg_state.F90
+          - Mods for issue #86
```
Comment (gold2718) [inline doc/ChangeLog:35]: A summary of the change would be much better here.

File: doc/ChangeLog [hunk 5]
```diff
@@ -1,6 +1,94 @@
...
+
+        modified:   bld/namelist_files/namelist_definition.xml
+        modified:   src/control/scamMod.F90
+        modified:   src/dynamics/eul/iop.F90
+        modified:   src/physics/cam/physpkg.F90
+          - Mods for issue #130
```
Comment (gold2718) [inline doc/ChangeLog:41]: A summary of the change would be much better here.

File: doc/ChangeLog [hunk 6]
```diff
@@ -1,6 +1,94 @@
...
+
+        modified:   Externals.cfg
+        modified:   test/system/CAM_compare.sh
+        modified:   test/system/test_driver.sh
+          - Mods for issue #146
```
Comment (gold2718) [inline doc/ChangeLog:46]: A summary of the change would be much better here.

File: doc/ChangeLog [hunk 7]
```diff
@@ -1,6 +1,94 @@
...
+
+        modified:   TGIT.sh
+          - Update the TGIT CAM regression test
```
Comment (gold2718) [inline doc/ChangeLog:49]: Why did it need an update? Is there an issue on that?

File: src/control/scamMod.F90 (hunk 1 above)
[the remark this answers is not in the document]
Comment (gold2718) [reply src/control/scamMod.F90:357]: So is it going away? I think it should.

File: test/system/TGIT.sh [hunk 8]
```diff
@@ -67,16 +68,26 @@ EOF
...
     check_code "$?" "Problem running 'find' command for multi-git file check."
 
-    if [ "${git_file_num}" -gt 2 ]; then
+    if [ "${git_file_num}" -gt 3 ]; then
         cat <<EOF
-More than two ".git*" files or sub-directories present in this CAM git repo.
+More than three ".git*" files or sub-directories present in this CAM git repo.
 EOF
-        rc=4
+        rc=5
```
Comment (gold2718) [inline test/system/TGIT.sh:90]: Note for the future. This seems like a losing game. Perhaps a better approach would be to take a peek in Externals.cfg and maybe also Externals_CAM.cfg and check that those directories, and only those directories contain .git files.
Another check could be to use `manage_externals/checkout_externals --status` to make sure that all the .git files that are supposed to be there are actually working clones in a clean state.

**Review by gold2718 — CHANGES_REQUESTED** [review]
Mostly documentation issues but I think that stray print statement should go away.

File: doc/ChangeLog (hunk 2 above)
Comment (cacraigucar) [reply doc/ChangeLog:11]: I am only addressing the open issues on the CESM2.1 branch.  Since there was no issue to update the ChangeLog_template, I did not bring it in.   I will make an issue to bring it in with my next tag in this branch.

File: doc/ChangeLog (hunk 4 above)
Comment (cacraigucar) [reply doc/ChangeLog:35]: I will copy the issue text here and for the following.

File: doc/ChangeLog (hunk 5 above)
Comment (cacraigucar) [reply doc/ChangeLog:41]: I will copy the issue text here

File: doc/ChangeLog (hunk 6 above)
Comment (cacraigucar) [reply doc/ChangeLog:46]: I will copy the issue text here

File: doc/ChangeLog (hunk 7 above)
Comment (cacraigucar) [reply doc/ChangeLog:49]: The test failed when I ran it.  I had looked for an issue that I could reference, but it was buried in issue #82.  I decided to not reference that issue as the thrust of the issue was not this modification.  I also thought since I was fixing the test, I wouldn't bother with making an issue for it.

In hindsight, since issue #82 included a change to the CAM source tree, it should not have been committed without making a tag and an updated ChangeLog.  I was unable to find this change via the ChangeLog, but rather had to use the github log.  I believe all CAM source changes should be documented in the ChangeLog.

File: test/system/TGIT.sh (hunk 8 above)
Comment (cacraigucar) [reply test/system/TGIT.sh:90]: This is what is currently on cam_development.   If a change is needed then an issue needs to be opened.   I will not be making any changes now, as the test is passing.

File: src/control/scamMod.F90 (hunk 1 above)
[the remark this answers is not in the document]
Comment (cacraigucar) [reply src/control/scamMod.F90:357]: I will remove the print statement.  If someone wants it removed from cam_development, then an issue needs to be opened for it.

File: doc/ChangeLog (hunk 3 above)
Comment (nusbaume) [reply doc/ChangeLog:13]: @cacraigucar if you can also change the PR number to the correct issue number in the keyword text above that would be great, as it will help us avoid having to close the issue manually later.  Thanks!

File: test/system/TGIT.sh (hunk 8 above)
Comment (nusbaume) [reply test/system/TGIT.sh:90]: @gold2718 I might disagree with that assessment.  Right now this test only examines the `.git*` files and directories in the top-level CAM directory, which should be quite limited (right now it is only `.git`, `.gitignore`, and `.github`.  I know there are a few other `.git*` file types out there, but I can't imagine there are too many more that we would add to the repo?  

Also, I can of course modify the script to examine the externals as well, but I wasn't sure if this test should cover them, or if they should be the responsibility of their own repo's tests?  Either way is fine with me.

File: doc/ChangeLog [hunk 9]
```diff
@@ -1,6 +1,100 @@
 
 ===============================================================
 
+Tag name: cam_cesm2_1_rel_46
+Originator(s):  cacraig, fvitt, jet
+Date:
+One-line Summary:  Fix rrtmg_state pointer bug, correct SCAM6 namelist inconsistencies and update izumi compilers and TGIT test
+Github PR URL:
```
Comment (gold2718) [inline doc/ChangeLog:8]: Where is the URL?

**Review by gold2718 — APPROVED** [review]
Either the ChangeLog template is wrong or you need to include a GitHub PR URL near the top.

File: doc/ChangeLog [hunk 10]
```diff
@@ -1,6 +1,100 @@
...
+   Misc bugs #1: rrtmg_state pointer, SCAM namelist, izumi compiler and TGIT test
+
+Purpose of changes (include the issue number and title text for each relevant GitHub issue):
+    cheyenne jobs randomly failing with deallocation [rrtmg_state pointer bug] (issue #86)
+    SCAM6 namelist definitions inconsistent (issue #130)
+    Updates to handle izumi compiler updates (issue #145)
+
```
Comment (gold2718) [inline doc/ChangeLog:15]: Do you need to include #228 here?

**Review by nusbaume — APPROVED** [review]
Should we create an issue to remind us to remove the erroneous `print` statement from the other branches as well?

File: doc/ChangeLog (hunk 9 above)
Comment (cacraigucar) [reply doc/ChangeLog:8]: Sorry - first time filling out the template and didn't register the "URL".  Added

File: doc/ChangeLog (hunk 10 above)
Comment (cacraigucar) [reply doc/ChangeLog:15]: Forgot to add that documentation.  Added both here and to the PR text.
