### PR TITLE
cam6_4_112: Fix minor bugs in cloud chemistry

### LINKED ISSUE #1345: Minor cloud chemistry bugs
### What happened?

Several minor bugs related to cloud chemistry were identified during refactoring:

- different values for Henry's Law Constant parameters are being used for wet deposition and cloud chemistry
- air density is taken as an input to the cloud chemistry function `setsox()` and used in several places, but in other places air density is calculated assuming an ideal gas
- inconsistent and rounded values for physical constants (e.g., Avogadro's number, Boltzmann Constant, pressure unit conversion) are used in `setsox()`
- a hard-coded value of 330 ppm is used for CO2
- the rate of H2O2 formation is incorrectly calculated for bulk aerosols
- outdated rate parameters for sulfur oxidation are used
- there are errors in the filters used to prevent over-reaction of some sulfur oxidation reactions
- there are a couple missing diagnostics for bulk aerosol configurations
- there is some incorrect logic in the output of wet deposition diagnostics for CARMA

We'll be submitting a PR in the near future to address these.
@tilmes @fvitt - let me know if I missed anything or got something wrong

### What are the steps to reproduce the bug?

Given the number of bugs with various configurations for aerosols, it's difficult to come up with an easy way to recreate them. Let me know if you would like me to put together a set of configurations that would cover all the cases.

### What CAM tag were you using?

cam6_4_101

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

GNU

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by mattldawson**
Several minor bugs related to cloud chemistry were identified during refactoring, and addressed here:
- different values for Henry's Law Constant parameters were being used for wet deposition and cloud chemistry
- air density was taken as an input to the cloud chemistry function setsox() and used in several places, but in other places air density is calculated assuming an ideal gas
- inconsistent and rounded values for physical constants (e.g., Avogadro's number, Boltzmann Constant, pressure unit conversion) are used in setsox()
- a hard-coded value of 330 ppm was used for CO2
- the rate of H2O2 formation was incorrectly calculated for bulk aerosols
- outdated rate parameters for sulfur oxidation were used
- there were errors in the filters used to prevent over-reaction of some sulfur oxidation reactions
- there were a couple missing diagnostics for bulk aerosol configurations
- there was some incorrect logic in the output of wet deposition diagnostics for CARMA

closes #1345

@fvitt @tilmes

### CODE REVIEW

File: src/chemistry/aerosol/mo_setsox.F90 [hunk 1]
```diff
@@ -218,7 +239,15 @@ subroutine setsox( state, &
     !-----------------------------------------------------------------------
     integer,  parameter :: itermax = 20
     real(r8), parameter :: ph0 = 5.0_r8  ! INITIAL PH VALUES
-    real(r8), parameter :: const0 = 1.e3_r8/6.023e23_r8
+    real(r8), parameter :: AVOGADRO = 6.02214076e23_r8          ! mol-1
+    real(r8), parameter :: BOLTZMANN = 1.380649e-23_r8          ! J K-1
```
Comment (cacraigucar) [inline src/chemistry/aerosol/mo_setsox.F90]: utils/physconst.F90 has a standard number for these

File: src/chemistry/aerosol/mo_setsox.F90 [hunk 2]
```diff
@@ -218,7 +239,15 @@ subroutine setsox( state, &
...
+    real(r8), parameter :: PASCAL_TO_ATM = 1.0_r8 / 101325.0_r8 ! atm Pa-1
+    real(r8), parameter :: M3_TO_L = 1.0e3_r8                   ! L m-3
+    real(r8), parameter :: M3_TO_CM3 = 1.0e6_r8                 ! cm3 m-3
+    real(r8), parameter :: SMALL_NUMBER = 1.0e-30_r8
+    real(r8), parameter :: const0 = 1.e3_r8/AVOGADRO
+    real(r8), parameter :: MOLECULAR_WEIGHT_DRY_AIR = 0.028966_r8  ! kg mol-1
+    real(r8), parameter :: MOLECULAR_WEIGHT_CO2 = 0.044009_r8      ! kg mol-1
```
Comment (cacraigucar) [inline src/chemistry/aerosol/mo_setsox.F90]: utils/physconst.F90 has a standard number for these

File: src/chemistry/aerosol/mo_setsox.F90 [hunk 3]
```diff
@@ -228,25 +257,27 @@ subroutine setsox( state, &
...
-    real(r8), parameter :: kh1 = 2.05e-5_r8         ! HO2(a)          -> H+ + O2-
-    real(r8), parameter :: kh2 = 8.6e5_r8           ! HO2(a) + ho2(a) -> h2o2(a) + o2
-    real(r8), parameter :: kh3 = 1.e8_r8            ! HO2(a) + o2-    -> h2o2(a) + o2
-    real(r8), parameter :: Ra = 8314._r8/101325._r8 ! universal constant   (atm)/(M-K)
-    real(r8), parameter :: xkw = 1.e-14_r8          ! water acidity
+    real(r8), parameter :: kh0 = 690.0_r8          ! HO2(g)          -> Ho2(a)        Reference: JPL 19-5
+    real(r8), parameter :: kh1 = 1.6e-5_r8         ! HO2(a)          -> H+ + O2-      Reference: JPL 19-5
+    real(r8), parameter :: kh2 = 8.3e5_r8          ! HO2(a) + ho2(a) -> h2o2(a) + o2  Reference: JPL; Bielski et al. 1985
+    real(r8), parameter :: kh3 = 9.7e7_r8          ! HO2(a) + o2-    -> h2o2(a) + o2  Reference: JPL; Bielski et al. 1985
+    real(r8), parameter :: Ra = BOLTZMANN * AVOGADRO * M3_TO_L * PASCAL_TO_ATM ! universal constant   (atm)/(M-K)
```
Comment (cacraigucar) [inline src/chemistry/aerosol/mo_setsox.F90]: Is this the same as the universal gas constant which is in utils/physconst.F90?

**Review by cacraigucar — CHANGES_REQUESTED** [review]
I believe that @fvitt is the proper person to officially review this PR.  But while I was skimming through it, I came across a couple of items which I believe should be addressed.

File: src/chemistry/aerosol/mo_setsox.F90 [hunk 4]
```diff
@@ -877,4 +887,19 @@ subroutine setsox( state, &
 
   end subroutine setsox
 
+   !-----------------------------------------------------------------
+   !       ... looks up Effective Henry's Law Constant parameters
+   !-----------------------------------------------------------------
+   pure integer function get_heff_index(species_name) result(index)
+      use shr_drydep_mod, only: species_name_table, dheff
```
Comment (fvitt) [inline src/chemistry/aerosol/mo_setsox.F90]: `dheff` is not used in this function.  Remove it from the use list.

File: src/chemistry/aerosol/mo_setsox.F90 [hunk 5]
```diff
@@ -272,7 +303,7 @@ subroutine setsox( state, &
          henh3,  &            ! henry law const for nh3
          heo3              !!,   &            ! henry law const for o3
 
-    real(r8) :: patm_x
+   real(r8), pointer :: co2_mass_mixing_ratio(:,:) ! kg kg-1
```
Comment (fvitt) [inline src/chemistry/aerosol/mo_setsox.F90]: Fix the indentation to be consistent with the other lines.

File: doc/ChangeLog [hunk 6]
```diff
@@ -1,3 +1,250 @@
...
+
+
+If there were any failures reported from running test_driver.sh on any test
+platform, and checkin with these failures has been OK'd by the gatekeeper,
+then copy the lines from the td.*.status files for the failed tests to the
+appropriate machine below.  All failed tests must be justified.
+
+derecho/intel/aux_cam:
+mattdawson@derecho3:/glade/derecho/scratch/mattdawson/aux_cam_intel_20250815100530> ./cs.status.aux_cam_intel_20250815100530 | grep -v PASS | grep -v TPUTCOMP | grep -v MEMCOMP
+aux_cam_intel_20250815100530: 51 tests
```
Comment (fvitt) [inline doc/ChangeLog]: These lines should not be copied into the change log.

File: doc/ChangeLog [hunk 7]
```diff
@@ -1,3 +1,250 @@
...
+  ERC_D_Ln9.f19_f19_mg17.QPC6.derecho_intel.cam-outfrq3s_cosp (Overall: DIFF) details:
```
Comment (fvitt) [inline doc/ChangeLog:68]: I believe all of these baseline failures are expected -- configurations that include prognostic aerosols and aqueous chemistry.

File: doc/ChangeLog [hunk 8]
```diff
@@ -1,3 +1,250 @@
...
+    FAIL ERS_Ln9_P24x1.mpasa480_mpasa480.F2000climo.izumi_gnu.cam-outfrq9s_mpasa480 BASELINE /fs/cgd/csm/models/atm/cam/pretag_bl/cam6_4_101_gnu: DIFF
+  SCT_D_Ln7.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 (Overall: DIFF) details:
+    FAIL SCT_D_Ln7.ne3_ne3_mg37.QPC6.izumi_gnu.cam-scm_prep_c6 BASELINE /fs/cgd/csm/models/atm/cam/pretag_bl/cam6_4_101_gnu: DIFF
+  SMS_D_Ln3.f10_f10_mg37.QPMOZ.izumi_gnu.cam-outfrq3s_chemproc (Overall: DIFF) details:
+    FAIL SMS_D_Ln3.f10_f10_mg37.QPMOZ.izumi_gnu.cam-outfrq3s_chemproc BASELINE /fs/cgd/csm/models/atm/cam/pretag_bl/cam6_4_101_gnu: DIFF
+  SMS_D_Ln9.ne5pg3_ne5pg3_mg37.QPC5.izumi_gnu.cam-outfrq3s_ttrac (Overall: DIFF) details:
+    FAIL SMS_D_Ln9.ne5pg3_ne5pg3_mg37.QPC5.izumi_gnu.cam-outfrq3s_ttrac BASELINE /fs/cgd/csm/models/atm/cam/pretag_bl/cam6_4_101_gnu: DIFF
+
+CAM tag used for the baseline comparison tests if different than previous
+tag: cam6_4_101
```
Comment (fvitt) [inline doc/ChangeLog]: I believe the regression tests will be re-run and compared against the latest cam tag when this PR is ready to merge -- when @cacraigucar gives the go ahead to merge into cam_development and create the next tag.  The test list may change and your new baselines may change after you merge to the head of cam_development.

File: doc/ChangeLog [hunk 9]
```diff
@@ -1,3 +1,250 @@
+
+===============================================================
+
+Tag name: tbd
+Originator(s): Matt Dawson, Francis Vitt
+Date: August 18, 2025
```
Comment (fvitt) [inline doc/ChangeLog:6]: This date will need to be updated

**Review by fvitt — CHANGES_REQUESTED** [review]
My initial review.

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 1 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: Hi @cacraigucar - The comment for Avogadro's number has units I wouldn't have expected:
https://github.com/ESCOMP/CAM/blob/2a5fb7ab948c3d2aa97fc618993345e1576be130/src/utils/physconst.F90#L46
Is it safe to assume this is a typo, or is this really molecules-per-kilomole?

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 3 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: yes, but in different units. I can replace the `BOLTZMANN * AVOGADRO` portion with the constant from utils/physconst.F90, but I have a similar question as for Avogadro's number about the units:
https://github.com/ESCOMP/CAM/blob/2a5fb7ab948c3d2aa97fc618993345e1576be130/src/utils/physconst.F90#L63
Should this be `(J K-1 mol-1)` or is this really per kilomole?

Comment (gold2718) [reply src/chemistry/aerosol/mo_setsox.F90]: The value in physconst is really per kmole. See 
https://github.com/ESCOMP/CESM_share/blob/b2fa120301f09323bfd3b7467a9b1fd13cf08ea3/src/shr_const_mod.F90#L25

Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: thanks @gold2718! Glad I asked!

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 1 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: @gold2718 answered this question in a separate thread. It should be updated now.

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 2 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: updated!

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 3 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: updated!

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 4 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: removed!

File: src/chemistry/aerosol/mo_setsox.F90 (hunk 5 above)
Comment (mattldawson) [reply src/chemistry/aerosol/mo_setsox.F90]: fixed!

File: doc/ChangeLog (hunk 6 above)
Comment (mattldawson) [reply doc/ChangeLog]: removed!

**Review by fvitt — APPROVED** [review]
Looks good to me.   Just need to update the ChangeLog when ready. Thanks.

**Comment by tilmes** [comment]
Budget changes for FCnudged MAM5 (1 year nudged simulation 2016):
Without bug fix: 
SO4
Burden 0.385725
Aq.Production 12.079
Nucleation (not part of chem.prod) 0.186733
Chemical Prod. (extf) 0.329749
Chemical Prod. gaex 14.3837
Total Prod. 26.7927
Total Loss.  26.4659
Dry Deposition 3.16711
Wet Deposition -23.2988
Wet Deposition int -5.44412
Wet Deposition cloud -17.8537
Lifetime 5.31966


With bug fix:
SO4
Burden 0.364546
Aq.Production 12.7007
Nucleation (not part of chem.prod) 0.173515
Chemical Prod. (extf) 0.329755
Chemical Prod. gaex 13.3769
Total Prod. 26.4073
Total Loss.  26.2099
Dry Deposition 3.14111
Wet Deposition -23.0687
Wet Deposition int -5.59311
Wet Deposition cloud -17.4734
Lifetime 5.07669

**Review by cacraigucar — APPROVED** [review]
