### PR TITLE
cam6_4_059: issue 1212 bug fix (cloud frac ice+liquid)

### LINKED ISSUE #1212: nucleate_ice_cam sets ice cloud frac to combined ice+liquid cloud frac
### What happened?

Bug in the following block of nucleate_ice_cam.F90
```
   call pbuf_get_field(pbuf, ast_idx, ast, start=(/1,1,itim_old/), kount=(/pcols,pver,1/))

   icecldf(:ncol,:pver) = ast(:ncol,:pver)
```

```ast``` is not ice cloud frac, but combined ice+liquid cloud frac. Changing the pbuf_get_field to ```aist_idx``` results in a slight reduction in CLDICE and NUMICE (compare FLTHIST to FLTHIST bugfix; note these are only 2 year runs):
temp_dzonal_CLDICE
temp_dzonal_NUMICE

@fvitt @tilmes

### What are the steps to reproduce the bug?

Run the FLTHIST compset.

### What CAM tag were you using?

cam6_4_047

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

copy this to SourceMods to run w/ bug fix: 
```
/glade/derecho/scratch/aherring/cam7_nochem_FLTHIST_ne30pg3_ne30pg3_mg17_3968pes_241222_aist-bug_Nx2yrs/SourceMods/src.cam/nucleate_ice_cam.F90
```

### PR DESCRIPTION
**Pull request by PeterHjortLauritzen**
Bug fix provided by @adamrher to fix issue [1212](https://github.com/ESCOMP/CAM/issues/1212)

closes #1212

### CODE REVIEW

File: src/physics/cam/nucleate_ice_cam.F90 [hunk 1]
```diff
@@ -509,9 +508,9 @@ subroutine nucleate_ice_cam_calc( &
    end if
 
    itim_old = pbuf_old_tim_idx()
-   call pbuf_get_field(pbuf, ast_idx, ast, start=(/1,1,itim_old/), kount=(/pcols,pver,1/))
-
-   icecldf(:ncol,:pver) = ast(:ncol,:pver)
+   call pbuf_get_field(pbuf, aist_idx, aist, start=(/1,1,itim_old/), kount=(/pcols,pver,1/))
+   !icecldf(:ncol,:pver) = ast(:ncol,:pver)
```
Comment (cacraigucar) [inline src/physics/cam/nucleate_ice_cam.F90:512]: Could we go ahead and remove this commented out line?

**Review by cacraigucar — CHANGES_REQUESTED** [review]
Also, the "auto closing feature" needs to have a variation of the word `fixes`, `resolves` or `closes` followed immediately by the issue number.  I've modified your description to get the auto-closer to work.

See: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

File: src/physics/cam/nucleate_ice_cam.F90 (hunk 1 above)
Comment (PeterHjortLauritzen) [reply src/physics/cam/nucleate_ice_cam.F90:512]: yes
