### PR TITLE
cam6_4_085: Phase 1 of rk_stratiform CCPPization; CCPPize cldfrc

### LINKED ISSUE #1267: Convert cloud_fraction/cldfrc to CCPP and move to atmospheric_physics
### What is the feature/what would you like to discuss?

Part of #1225 

This is the accompanying issue for the first-stage cleanup PR for CCPPizing rk_stratiform_tend (CAM4).

This will only affect CAM4 and CAM5 physics, which use cloud_fraction.

### Is there anyone in particular you want to be part of this conversation?

_No response_

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

### LINKED ISSUE #1274: Vertical dimension of tphysbc_cmfmc should be ilev (not lev)
### What happened?

`tphysbc_cmfmc` (`atmosphere_convective_mass_flux_due_to_all_convection`) is incorrectly written with `lev` as the vertical dimension instead of `ilev`.

It is defined at module level with interface dimension:
https://github.com/ESCOMP/CAM/blob/e73a79b0d3be075915502afc25348f6af6611153/src/physics/cam/physpkg.F90#L2137

The `addfld` call should be `ilev` here
https://github.com/ESCOMP/CAM/blob/e73a79b0d3be075915502afc25348f6af6611153/src/physics/cam/cam_snapshot.F90#L241-L242

and in `physics/cam7/cam_snapshot.F90` as well.

Because the vertical dimension is declared incorrectly, attempting to read this field in CAM-SIMA will lead to CAM-SIMA crashing.

### What are the steps to reproduce the bug?

Observe any tphysbc CAM snapshot
```
        double tphysbc_cmfmc(time, lev, ncol) ;
                tphysbc_cmfmc:mdims = 1 ;
                tphysbc_cmfmc:units = "unset" ;
                tphysbc_cmfmc:long_name = "tphysbc_cmfmc" ;
                tphysbc_cmfmc:cell_methods = "time: point" ;
```

### What CAM tag were you using?

cam6_4_075

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

Will likely bundle the fix into #1271 unless there is another urgent need for this field in other SIMA work.

### PR DESCRIPTION
**Pull request by jimmielin**
Purpose of changes (include the issue number and title text for each relevant GitHub issue):
* Closes #1267 
* Fixes #1274 for incorrect vertical dimension of `tphysbc_cmfmc` in snapshots
* Partial completion of https://github.com/ESCOMP/CAM/issues/1267; most code has been moved to atmospheric_physics.

Companion PR in atmospheric_physics: https://github.com/ESCOMP/atmospheric_physics/pull/219

Changes are expected to be B4B for CAM regression tests
Roundoff changes to CAM4 diagnostics

Describe any changes made to build system: N/A

Describe any changes made to the namelist:
* build-namelist updated to add `rk_stratiform_tend` snapshot point

List any changes to the defaults for the boundary datasets: N/A

Describe any substantial timing or memory changes: N/A

Code reviewed by: TBD

List all files eliminated: 
```
D       src/physics/cam/cldwat.F90
D       src/physics/cam/pkg_cldoptics.F90
  - moved to atmospheric_physics: prognostic_cloud_water CCPPized scheme
  - moved to atmospheric_physics: cloud_optical_properties to-be-ccppized library; dechunkized
```

List all files added and what they do: N/A

List all existing files that have been modified, and describe the changes:
```
M       .gitmodules
M       src/atmos_phys
  - new atmos_phys external to include CCPPized schemes

M       bld/configure
  - include atmos_phys/schemes/rasch_kristjansson

M       bld/build-namelist
M       bld/namelist_files/namelist_definition.xml
M       src/physics/cam/physpkg.F90
  - add rk_stratiform_tend snapshot point

R068    src/physics/cam/rk_stratiform.F90       src/physics/cam/rk_stratiform_cam.F90
M       src/control/runtime_opts.F90
M       src/physics/cam/const_init.F90
  - rename CAM interface to rk_stratiform_cam
  - CCPPize most logic and moved into atmos_phys

M       src/physics/cam/cloud_diagnostics.F90
  - changes to support move of pkg_cldoptics to atmos_phys

M       src/physics/cam/cloud_fraction.F90
  - CCPPized cldfrc and moved to atmos_phys: compute_cloud_fraction
  - shallow and deep convective cloud cover logic separated into CCPPized scheme in atmos_phys: convective_cloud_cover

M       src/physics/cam/macrop_driver.F90
  - changes to support CCPPization of cldfrc

M       src/physics/cam/pkg_cld_sediment.F90
  - CCPPized logic and moved into atmos_phys: cloud_particle_sedimendation

M       src/physics/cam7/cam_snapshot.F90
M       src/physics/cam/cam_snapshot.F90
  - fix #1274 vertical dimension of tphysbc_cmfmc
```

### CODE REVIEW

File: src/physics/cam/rk_stratiform_cam.F90 [hunk 1]
```diff
@@ -651,31 +689,80 @@ subroutine rk_stratiform_tend( &
...
+     errmsg              = errmsg,                         &
+     errflg              = errflg)
+
+   if(errflg /= 0) then
+      call endrun('rk_stratiform_tend:' // errmsg)
+   endif
 
-   ! Convert rain and snow fluxes at the surface from [kg/m2/s] to [m/s]
-   ! Compute total precipitation flux at the surface in [m/s]
+   wsedl(:ncol,:pver) = pvliq(:ncol,:pver)/gravit/(state1%pmid(:ncol,:pver)/(287.15_r8*state1%t(:ncol,:pver)))
```
Comment (nusbaume) [inline src/physics/cam/rk_stratiform_cam.F90:745]: I am like 95% sure that this `287` number is the gas constant for dry air.  I might vote to either just use the actual physical constant, or if that changes answers too much to just create a new parameter here labeling it as the gas constant but keeping the actual value the same.

File: src/physics/cam/rk_stratiform_cam.F90 [hunk 2]
```diff
@@ -757,63 +843,165 @@ subroutine rk_stratiform_tend( &
...
+      cappa = cappa, &
+      gravit = gravit, &
+      rair = rair, &
+      tmelt = tmelt, &
+      top_lev_cloudphys = 1, & ! CAM4 macrophysics.
+      pmid = state1%pmid(:ncol,:), &
+      ps = state1%pint(:,pverp), &
+      temp = state1%t(:ncol,:), &
+      sst = sst(:ncol), &
+      q = state1%q(:ncol,:,1), & ! note: assumes wv is at index 1.
```
Comment (nusbaume) [inline src/physics/cam/rk_stratiform_cam.F90:904]: Use `ixq` here and below as well if already set above?

File: src/physics/cam/rk_stratiform_cam.F90 [hunk 3]
```diff
@@ -822,91 +1010,207 @@ subroutine rk_stratiform_tend( &
...
+   ! Compute Stratiform Macro-Microphysical Tendencies
+   !-------------------------------------------------------
+
+   ! Add rain and snow fluxes as output variables from pcond, and into physics buffer
+   call pbuf_get_field(pbuf, ls_flxprc_idx, rkflxprc)
+   call pbuf_get_field(pbuf, ls_flxsnw_idx, rkflxsnw)
+
+   call t_startf('pcond')
+
+   !totcw(:ncol,:pver)     = state1%q(:ncol,:pver,ixcldice) + state1%q(:ncol,:pver,ixcldliq)
```
Comment (nusbaume) [inline src/physics/cam/rk_stratiform_cam.F90:1023]: Remove commented-out code?

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks good!  Just had some (hopefully) minor change requests.

File: src/physics/cam/rk_stratiform_cam.F90 (hunk 1 above)
Comment (nusbaume) [reply src/physics/cam/rk_stratiform_cam.F90]: Making an issue to tackle these magic numbers later seems sensible to me.  Thanks @jimmielin!

**Review by nusbaume — APPROVED** [review]
Everything looks great to me now.  Thanks @jimmielin!

File: src/physics/cam/macrop_driver.F90 [hunk 4]
```diff
@@ -848,14 +862,76 @@ subroutine macrop_driver_tend(                             &
...
+   call compute_cloud_fraction_run( &
+      ncol = ncol, &
+      pver = pver, &
+      cappa = cappa, &
+      gravit = gravit, &
+      rair = rair, &
+      tmelt = tmelt, &
+      top_lev_cloudphys = trop_cloud_top_lev, & ! CAM5 macrophysics.
+      pmid = state_loc%pmid(:ncol,:), &
+      ps = state_loc%pint(:,pverp), &
```
Comment (cacraigucar) [inline src/physics/cam/macrop_driver.F90:913]: Technically should have `:ncol` here.  This works because once the array is inside the CCPP'ized routine, it is a single dimension .

**Review by cacraigucar — CHANGES_REQUESTED** [review]
Accidentally sent my single request outside the review

File: src/physics/cam/rk_stratiform_cam.F90 (hunk 1 above)
Comment (cacraigucar) [reply src/physics/cam/rk_stratiform_cam.F90]: @jimmielin  - Have you opened an issue on this.  If so, could you please post the link here?

**Review by cacraigucar — APPROVED** [review]
