### PR TITLE
cam6_3_017: PUMAS Optimization PR pt2

### LINKED ISSUE #257: Bug in FSCAM with GNU compilers in DEBUG mode
Running SCAM with the GNU compilers with DEBUG=TRUE results in an error in CESM 2.2, but works in CESM 2.1.3.  

Tested on Cheyenne:

CESM 2.1.3, Intel compiler, DEBUG=FALSE - works fine
CESM 2.1.3, Intel compiler, DEBUG=TRUE - works fine
CESM 2.1.3, GNU compiler, DEBUG=FALSE - works fine
CESM 2.1.3, GNU compiler, DEBUG=TRUE - works fine

CESM 2.2.0, Intel compiler, DEBUG=FALSE - works fine
CESM 2.2.0, Intel compiler, DEBUG=TRUE - works fine
CESM 2.2.0, GNU compiler, DEBUG=FALSE - works fine
CESM 2.2.0, GNU compiler, DEBUG=TRUE - fail, with the message below

```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7efc67dc994f in ???
#1  0xf47df0 in __micro_mg3_0_MOD_micro_mg_tend
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/physics/pumas/micro_mg3_0.F90:1969
#2  0xc531c9 in micro_mg_cam_tend_pack
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/physics/cam/micro_mg_cam.F90:2517
#3  0xc710dc in __micro_mg_cam_MOD_micro_mg_cam_tend
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/physics/cam/micro_mg_cam.F90:1310
#4  0xc98a91 in __microp_driver_MOD_microp_driver_tend
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/physics/cam/microp_driver.F90:189
#5  0x662a1d in tphysbc
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/physics/cam/physpkg.F90:2473
#6  0x670449 in __physpkg_MOD_phys_run1
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/physics/cam/physpkg.F90:1073
#7  0x4fa1b3 in __cam_comp_MOD_cam_run1
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/control/cam_comp.F90:259
#8  0x4f4465 in __atm_comp_mct_MOD_atm_init_mct
	at /glade/scratch/bdobbins/scam/cesm2.2.0/components/cam/src/cpl/mct/atm_comp_mct.F90:354
#9  0x427e14 in __component_mod_MOD_component_init_cc
	at /glade/scratch/bdobbins/scam/cesm2.2.0/cime/src/drivers/mct/main/component_mod.F90:248
#10  0x41e9a6 in __cime_comp_mod_MOD_cime_init
	at /glade/scratch/bdobbins/scam/cesm2.2.0/cime/src/drivers/mct/main/cime_comp_mod.F90:2209
#11  0x4243b5 in cime_driver
	at /glade/scratch/bdobbins/scam/cesm2.2.0/cime/src/drivers/mct/main/cime_driver.F90:122
#12  0x424524 in main
	at /glade/scratch/bdobbins/scam/cesm2.2.0/cime/src/drivers/mct/main/cime_driver.F90:23
```

To reproduce the failure in the CESM 2.2 release, do:

_export CESM22ROOT=<path to CESM 2.2 checkout>
${CESM22ROOT}/cime/scripts/create_newcase --compset FSCAM --res T42_T42 --compiler gnu --case foo --user-mods-dir ${CESM22ROOT}/components/cam/cime_config/usermods_dirs/scam_arm97 --run-unsupported
cd foo
./xmlchange DEBUG=TRUE,PIO_TYPENAME=netcdf,STOP_N=1,STOP_OPTION=ndays
./case.setup 
./case.build 
./case.submit_ 

I've not tested other IOPs, just arm97.  I'm going to dig into this at some point, but I'm not familiar with the SCAM code base, so I thought others might have a quick solution or at least ideas.

### LINKED ISSUE #309: Modify conditionals to avoid potential divide by zero in micro_mg_cam
In micro_mg_cam.F90, there are 2 places where we need to adjust the conditional to be >qsmall rather than >= qsmall:

https://github.com/ESCOMP/CAM/blob/e3630ffd84789ae4f24bef13672db5d22c360c91/src/physics/cam/micro_mg_cam.F90#L3114
https://github.com/ESCOMP/CAM/blob/e3630ffd84789ae4f24bef13672db5d22c360c91/src/physics/cam/micro_mg_cam.F90#L3211

This has not created issues in CAM, but caused failures in another model (ECMWF-IFS) when running at single precision. 

The size_dist_param_basic calculation has a limiter that is > qsmall, so if it =qsmall the routine will return a zero for lambda (size parameter) and this will create a divide by zero.

Only noticed at single precision, but I think should be modified and will not change answers (hopefully) in CAM.

### LINKED ISSUE #329: PUMAS (Microphysics) Bug Fixes
We have a series of bug fixes coming in for PUMAS. I think Kate will be bringing these in.

These include two existing issues: #257 and #309 

As well as a bug identified in the PUMAS repository: ESCOMP/PUMAS#20

These are in addition to the two PR's already submitted for GPU optmization work.

### LINKED ISSUE #341: TR8 test gives incorrect summary
When an error in the TR8 test is found, it correctly writes out the offending line.  Even when a error is found, the status is "TR8 test PASS".

To reproduce this, any "_r8" can be removed from a Fortran routine.

### PR DESCRIPTION
**Pull request by Katetc**
Fixes #329 Fixes #309 Fixes #257 

Closes #341  Closes #350

This PR and another one titled "PUMAS Optimization PR pt1" should go into the same CAM tag for expediency. The changes were broken up to help with the review process.

The second part of the PR includes CAM source code changes as well as PUMAS source changes. However, these changes are all verified bit-for-bit against a full aux_cam Cheyenne suite generated by part 1 of the PR. To review the PUMAS changes look at:
https://github.com/ESCOMP/PUMAS/compare/pumas_cam-release_v1.9..pumas_cam-release_v1.11

Tagging @andrewgettelman so he can follow the discussion.

All changes suggested by review of both part 1 and part 2 PRs will be included in this PR.

### CODE REVIEW

**Review by cacraigucar — CHANGES_REQUESTED** [review]
When you address these minor issues from my preliminary review, I will then open this PR up for full review.

File: src/physics/cam/wv_sat_methods.F90 [hunk 1]
```diff
@@ -379,6 +547,23 @@ elemental function GoffGratch_svp_water(t) result(es)
...
+  real(r8), intent(out) :: es(vlen) ! SVP in Pa
+  integer :: i
+  ! uncertain below -70 C
+
+  do i=1,vlen
+     es(i) = 10._r8**(-7.90298_r8*(tboil/t(i)-1._r8)+ &
+       5.02808_r8*log10(tboil/t(i))- &
+       1.3816e-7_r8*(10._r8**(11.344_r8*(1._r8-t(i)/tboil))-1._r8)+ &
+       8.1328e-3_r8*(10._r8**(-3.49149_r8*(tboil/t(i)-1._r8))-1._r8)+ &
+       log10(1013.246_r8))*100._r8
```
[the remark this answers is not in the document]
Comment (andrewgettelman) [reply src/physics/cam/wv_sat_methods.F90:562]: Goff, J. A., and S. Gratch. “Low-Pressure Properties of Water from -160F to 212F.” Trans. Am. Soc. Heat. Vent. Eng. 52 (1946): 95–121.

File: src/physics/cam/wv_sat_methods.F90 [hunk 2]
```diff
@@ -404,6 +603,22 @@ elemental function MurphyKoop_svp_water(t) result(es)
...
+  real(r8), intent(out) :: es(vlen)             ! SVP in Pa
+  
+  integer :: i
+  ! (good for 123 < T < 332 K)
+
+  do i = 1, vlen
+     es(i) = exp(54.842763_r8 - (6763.22_r8 / t(i)) - (4.210_r8 * log(t(i))) + &
+          (0.000367_r8 * t(i)) + (tanh(0.0415_r8 * (t(i) - 218.8_r8)) * &
+          (53.878_r8 - (1331.22_r8 / t(i)) - (9.44523_r8 * log(t(i))) + &
+          0.014025_r8 * t(i))))
```
[the remark this answers is not in the document]
Comment (andrewgettelman) [reply src/physics/cam/wv_sat_methods.F90:618]: Murphy, D. M., and T. Koop. “Review of the Vapour Pressure of Ice and Supercooled Water for Atmospheric Applications.” Q. J. R. Meteorol. Soc. 131, no. 608 (2005): 1539–65.

File: src/physics/cam/macrop_driver.F90 [hunk 3]
```diff
@@ -1128,55 +1128,61 @@ end subroutine macrop_driver_tend
...
-  real(r8) :: ESL
-  real(r8) :: QSL
-
-  stend = 0._r8
-  qvtend = 0._r8
-  qctend = 0._r8
-  nctend = 0._r8
+  do i = 1, vlen
+     ! Don't allow supersaturation with respect to liquid.
+     if (qv(i).gt.QSL(i)) then
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/macrop_driver.F90]: Fixed

File: src/physics/cam/macrop_driver.F90 [hunk 4]
```diff
@@ -1128,55 +1128,61 @@ end subroutine macrop_driver_tend
...
+        qvtend(i) = 0._r8 - qctend(i)
+        stend(i)  = qctend(i) * xxlv    ! moist static energy tend...[J/kg/s] !
+   
+        ! If drops  exists (more than 1 L-1) and there is condensation,
+        ! do not add to number (= growth), otherwise  add 6um drops.
+        !
+        ! This is somewhat arbitrary, but ensures that some reasonable droplet
+        ! size is create to remove the excess water. This could be enhanced to
+        ! look at npccn, but ideally this entire routine should go away.
+        if (nc(i)*p(i)/rair/t(i).lt.1e3_r8.and.(qc(i)+qctend(i)*deltat).gt.1e-18_r8) then
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/macrop_driver.F90]: Fixed, I believe. I left the ".and." there because I don't think C-style Boolean operators are fully supported... but feel free to correct me if you prefer a "&&" here.

File: src/physics/cam/wv_sat_methods.F90 (hunk 1 above)
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:564]: Fixed

File: src/physics/cam/wv_sat_methods.F90 (hunk 2 above)
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:623]: Fixed

File: src/physics/cam/wv_sat_methods.F90 (hunk 1 above)
[the remark this answers is not in the document]
Comment (cacraigucar) [reply src/physics/cam/wv_sat_methods.F90:564]: Is there a DOI for this paper (it is pretty old)?  If so, please add it.

File: src/physics/cam/wv_sat_methods.F90 (hunk 2 above)
[the remark this answers is not in the document]
Comment (cacraigucar) [reply src/physics/cam/wv_sat_methods.F90:623]: Please add the DOI if there is one for this paper.

File: src/physics/cam/wv_sat_methods.F90 (hunk 1 above)
[the remark this answers is not in the document]
Comment (andrewgettelman) [reply src/physics/cam/wv_sat_methods.F90:564]: No DOI. Too old.

File: src/physics/cam/wv_sat_methods.F90 (hunk 2 above)
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:623]: Addressed this

**Comment by fvitt** [comment]
Is there a github issue this PR is addressing?

File: src/physics/cam/clubb_intr.F90 [hunk 5]
```diff
@@ -3508,50 +3508,53 @@ end subroutine clubb_tend_cam
...
-  real(r8), intent(out) :: qitend !ice mass tendency
-  real(r8), intent(out) :: nitend !ice number tendency  
+subroutine ice_macro_tend(naai,t,p,qv,qi,ni,xxls,deltat,stend,qvtend,qitend,nitend,vlen) 
+
+  use wv_sat_methods, only: wv_sat_qsat_ice_vect
+
+  integer,                   intent(in)  :: vlen
+  real(r8), dimension(vlen), intent(in)  :: naai   !Activated number of ice nuclei 
+  real(r8), dimension(vlen), intent(in)  :: t      !temperature (k)
+  real(r8), dimension(vlen), intent(in)  :: p      !pressure (pa0
```
Comment (fvitt) [inline src/physics/cam/clubb_intr.F90:3518]: Are the units (Pa)?

File: src/physics/cam/macrop_driver.F90 [hunk 6]
```diff
@@ -1128,55 +1128,61 @@ end subroutine macrop_driver_tend
...
+        stend(i)  = qctend(i) * xxlv    ! moist static energy tend...[J/kg/s] !
+   
+        ! If drops  exists (more than 1 L-1) and there is condensation,
+        ! do not add to number (= growth), otherwise  add 6um drops.
+        !
+        ! This is somewhat arbitrary, but ensures that some reasonable droplet
+        ! size is create to remove the excess water. This could be enhanced to
+        ! look at npccn, but ideally this entire routine should go away.
+        if ((nc(i)*p(i)/rair/t(i) < 1e3_r8) .and. (qc(i)+qctend(i)*deltat > 1e-18_r8)) then
+           nctend(i) = nctend(i) + 3._r8 * qctend(i)/(4._r8*3.14_r8*6.e-6_r8**3*rhow)
```
Comment (fvitt) [inline src/physics/cam/macrop_driver.F90:1181]: Is 3.14 pi?  To improve efficiency, could you let 3./(4*pi*6e-6**3*rhow) a parameter?

File: src/physics/cam/cldfrc2m.F90 [hunk 7]
```diff
@@ -1007,11 +1008,12 @@ subroutine aist_vector(qv_in, T_in, p_in, qi_in, ni_in, landfrac_in, snowh_in, a
...
-     call qsat_water(T_in(1:ncol), p_in(1:ncol), &
-          esat_in(1:ncol), qsat_in(1:ncol))
-     
-     do i = 1, ncol
+     call qsat_water(T_in(1:ncol), p_in(1:ncol), esat_in(1:ncol), qsat_in(1:ncol), ncol)
+     call svp_water_vect(T_in(1:ncol), esl(1:ncol), ncol)
+     call svp_ice_vect(T_in(1:ncol), esi(1:ncol), ncol)
 
+     do i = 1, ncol
+
```
Comment (fvitt) [inline src/physics/cam/cldfrc2m.F90:1016]: This loop does not seem to be indented.

File: src/physics/cam/wv_sat_methods.F90 [hunk 8]
```diff
@@ -271,10 +347,10 @@ end subroutine wv_sat_qsat_trans
 ! SVP INTERFACE FUNCTIONS
 !---------------------------------------------------------------------
 
-elemental function wv_sat_svp_water(t, idx) result(es)
+function wv_sat_svp_water(t, idx) result(es)
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:350]: Is there a need to do away with elemental functions?  I did not see discussion of this in the issues.  Is this done for efficiency reasons?  If so, much have you improved efficiency?

File: src/physics/cam/wv_sat_methods.F90 [hunk 9]
```diff
@@ -379,6 +547,25 @@ elemental function GoffGratch_svp_water(t) result(es)
...
+  ! Goff, J. A., and S. Gratch. “Low-Pressure Properties of Water from -160F
+  ! to 212F.” Trans. Am. Soc. Heat. Vent. Eng. 52 (1946): 95–121.
+  ! uncertain below -70 C
+
+  do i=1,vlen
+     es(i) = 10._r8**(-7.90298_r8*(tboil/t(i)-1._r8)+ &
+       5.02808_r8*log10(tboil/t(i))- &
+       1.3816e-7_r8*(10._r8**(11.344_r8*(1._r8-t(i)/tboil))-1._r8)+ &
+       8.1328e-3_r8*(10._r8**(-3.49149_r8*(tboil/t(i)-1._r8))-1._r8)+ &
+       log10(1013.246_r8))*100._r8
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:564]: Log is an expensive operation.  Could you make `log10(1013.246_r8)` a parameter?  There is  no need to compute this more than once.

File: src/physics/cam/wv_sat_methods.F90 [hunk 10]
```diff
@@ -390,6 +577,20 @@ elemental function GoffGratch_svp_ice(t) result(es)
...
+  integer, intent(in) :: vlen
+  real(r8), intent(in)  :: t(vlen)  ! Temperature in Kelvin
+  real(r8), intent(out) :: es(vlen)             ! SVP in Pa
+  integer :: i
+  ! good down to -100 C
+
+  do i=1,vlen
+     es(i) = 10._r8**(-9.09718_r8*(h2otrip/t(i)-1._r8)-3.56654_r8* &
+          log10(h2otrip/t(i))+0.876793_r8*(1._r8-t(i)/h2otrip)+ &
+          log10(6.1071_r8))*100._r8
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:590]: Could you make `log10(6.1071_r8)` a parameter?

File: src/physics/cam/wv_sat_methods.F90 [hunk 11]
```diff
@@ -404,6 +605,25 @@ elemental function MurphyKoop_svp_water(t) result(es)
 
 end function MurphyKoop_svp_water
 
+subroutine MurphyKoop_svp_water_vect(t, es, vlen)
+  integer, intent(in)   :: vlen
+  real(r8), intent(in)  :: t(vlen)  ! Temperature in Kelvin
+  real(r8), intent(out) :: es(vlen)             ! SVP in Pa
+  
+      integer :: i
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:613]: Please fix the indentation.

File: src/physics/cam/wv_sat_methods.F90 [hunk 12]
```diff
@@ -447,6 +681,28 @@ elemental function OldGoffGratch_svp_water(t) result(es)
...
+  integer :: i
+
+  do i = 1, vlen
+     ps(i) = 1013.246_r8
+     e1(i) = 11.344_r8*(1.0_r8 - t(i)/tboil)
+     e2(i) = -3.49149_r8*(tboil/t(i) - 1.0_r8)
+     f1(i) = -7.90298_r8*(tboil/t(i) - 1.0_r8)
+     f2(i) = 5.02808_r8*log10(tboil/t(i))
+     f3(i) = -1.3816_r8*(10.0_r8**e1(i) - 1.0_r8)/10000000.0_r8
+     f4(i) = 8.1328_r8*(10.0_r8**e2(i) - 1.0_r8)/1000.0_r8
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:699]: Instead of dividing constants, could you multiply by inverses?

File: src/physics/cam/wv_sat_methods.F90 [hunk 13]
```diff
@@ -447,6 +681,28 @@ elemental function OldGoffGratch_svp_water(t) result(es)
...
+     f5(i) = log10(ps(i))
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:700]: I seems that f5 could be a parameter (`log10(1013.256)`).

File: src/physics/cam/wv_sat_methods.F90 [hunk 14]
```diff
@@ -447,6 +681,28 @@ elemental function OldGoffGratch_svp_water(t) result(es)
...
+      f(i) = f1(i) + f2(i) + f3(i) + f4(i) + f5(i)
+     es(i) = (10.0_r8**f(i))*100.0_r8
+  end do
+end subroutine OldGoffGratch_svp_water_vect
+
 elemental function OldGoffGratch_svp_ice(t) result(es)
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:706]: Is this elemental function remaining as elemental?

File: src/physics/cam/wv_sat_methods.F90 [hunk 15]
```diff
@@ -390,6 +577,20 @@ elemental function GoffGratch_svp_ice(t) result(es)
...
+  do i=1,vlen
+     es(i) = 10._r8**(-9.09718_r8*(h2otrip/t(i)-1._r8)-3.56654_r8* &
+          log10(h2otrip/t(i))+0.876793_r8*(1._r8-t(i)/h2otrip)+ &
+          log10(6.1071_r8))*100._r8
+  enddo
+end subroutine GoffGratch_svp_ice_vect
+
 ! Murphy & Koop (2005)
 
 elemental function MurphyKoop_svp_water(t) result(es)
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:596]: Is this elemental function remaining as elemental?

**Review by fvitt — COMMENTED** [review]
I am seeing copies of constants and complicated formulas throughout wv_sat_methods.  This will be difficult to maintain.

File: src/physics/cam/cldfrc2m.F90 (hunk 7 above)
Comment (Katetc) [reply src/physics/cam/cldfrc2m.F90:1016]: I read this as "This loop does not seem to be intended" at first and spent some confused time staring at the code. Lol. Dyslexia.

File: src/physics/cam/wv_sat_methods.F90 (hunk 8 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:350]: The purpose of these PRs is to prep the microphysics code in CAM for offloading onto GPUs once they become available. Elemental functions do not vectorize well, and aren't as efficient on GPUs. These changes should not improve efficiency on currently supported machines, so there isn't a good way to quantify improvements right now.

File: src/physics/cam/wv_sat_methods.F90 (hunk 13 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:700]: I think keeping this as variable allows the function to be more flexible. For different sea levels (paleo runs, distant futures) or other reference surface pressures at other altitudes.

File: src/physics/cam/wv_sat_methods.F90 (hunk 14 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:706]: For some reason, yes, Jian left these as elemental functions. I grepped through the CESM code, and I can't find anywhere that OldGoffGratch is used any more, so I'm not sure if it matters at this point if those are elemental functions or not. If those functions are never called, then changing them to support GPUs is not necessary.

File: src/physics/cam/wv_sat_methods.F90 (hunk 15 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:596]: For some reason, John Dennis' postdoc Jian (who made these modifications for us) did leave some functions as elemental. Perhaps these are not called any more or will be updated in the future. It will remain elemental in this pull request.

File: src/physics/cam/clubb_intr.F90 (hunk 5 above)
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90]: Fixed the parenthesis

File: src/physics/cam/macrop_driver.F90 (hunk 6 above)
Comment (Katetc) [reply src/physics/cam/macrop_driver.F90]: Changed

File: src/physics/cam/cldfrc2m.F90 (hunk 7 above)
Comment (Katetc) [reply src/physics/cam/cldfrc2m.F90:1016]: Fixed indentation

File: src/physics/cam/wv_sat_methods.F90 (hunk 9 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90:565]: Made this change

File: src/physics/cam/wv_sat_methods.F90 (hunk 10 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: Made this change

File: src/physics/cam/wv_sat_methods.F90 (hunk 11 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: Fixed

File: src/physics/cam/wv_sat_methods.F90 (hunk 12 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: Changed

**Review by gold2718 — APPROVED** [review]
A few suggestions (and notes for the future) but basically okay.

**Review by nusbaume — APPROVED** [review]
Looks good to me!  Just a few very minor edits.

File: src/physics/cam/cldfrc2m.F90 [hunk 16]
```diff
@@ -1007,29 +1008,28 @@ subroutine aist_vector(qv_in, T_in, p_in, qi_in, ni_in, landfrac_in, snowh_in, a
...
+       if (present(rhmaxi_in))          rhmaxi          = rhmaxi_in(i)
+       if (present(rhmini_in))          rhmini          = rhmini_in(i)      
+       if (present(rhminl_in))          rhminl          = rhminl_in(i)      
+       if (present(rhminl_adj_land_in)) rhminl_adj_land = rhminl_adj_land_in(i)
+       if (present(rhminh_in))          rhminh          = rhminh_in(i)
           
-     if( iceopt.lt.3 ) then
+       if( iceopt.lt.3 ) then
          if( iceopt.eq.1 ) then
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/cldfrc2m.F90:1033]: Sure, sounds good to me!

File: src/physics/cam/clubb_intr.F90 [hunk 17]
```diff
@@ -3508,50 +3508,53 @@ end subroutine clubb_tend_cam
...
-     if (ni < 1.e3_r8 .and. (qi+qitend*deltat) > 1.e-18_r8) then
-        nitend = nitend + 3._r8 * qitend/(4._r8*3.14_r8* 10.e-6_r8**3*997._r8)
-     endif
+        qitend(i) = (qv(i)-QSI(i))/deltat !* exp(-tau/deltat)
+        qvtend(i) = 0._r8 - qitend(i)
+        stend(i)  = qitend(i) * xxls      ! moist static energy tend...[J/kg/s] !
+   
+        ! if ice exists (more than 1 L-1) and there is condensation, do not add to number (= growth), else, add 10um ice
+        if (ni(i) < 1.e3_r8 .and. (qi(i)+qitend(i)*deltat) > 1.e-18_r8) then
+           nitend(i) = nitend(i) + 3._r8 * qitend(i)/(4._r8*3.14_r8* 10.e-6_r8**3*997._r8)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90:3553]: Thanks, I agree!

File: src/physics/cam/wv_sat_methods.F90 (hunk 9 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: I have no idea what happened here. Apparently I was once sure I made this change, but it didn't stick. Maybe I can blame emacs or git or who knows. Thanks for catching that, Steve.

File: src/physics/cam/wv_sat_methods.F90 (hunk 13 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: Ahhh, I see what's up now. I made these requested changes.

File: src/physics/cam/cldwat.F90 [hunk 18]
```diff
@@ -778,6 +780,7 @@ subroutine pcond (lchnk   ,ncol    ,troplev ,dlat    , &
 ! should have taken care of all of large scale condensation.
 ! 
 
+
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/cldwat.F90]: I have no opinion on extra lines. Removed.

File: src/physics/cam/clubb_intr.F90 [hunk 19]
```diff
@@ -3508,50 +3508,53 @@ end subroutine clubb_tend_cam
...
+  call wv_sat_qsat_ice_vect(t, p, ESI, QSI, vlen)
 
+  do i = 1, vlen
+     if (naai(i) > 1.e-18_r8 .and. qv(i) > QSI(i)) then
 
- ! if ice exists (more than 1 L-1) and there is condensation, do not add to number (= growth), else, add 10um ice
-     if (ni < 1.e3_r8 .and. (qi+qitend*deltat) > 1.e-18_r8) then
-        nitend = nitend + 3._r8 * qitend/(4._r8*3.14_r8* 10.e-6_r8**3*997._r8)
-     endif
+        qitend(i) = (qv(i)-QSI(i))/deltat !* exp(-tau/deltat)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90]: I have no idea, this comment is from before my time. Sure, removed.

File: src/physics/cam/wv_sat_methods.F90 [hunk 20]
```diff
@@ -390,6 +578,22 @@ elemental function GoffGratch_svp_ice(t) result(es)
...
 
+subroutine GoffGratch_svp_ice_vect(t, es, vlen)
+  integer, intent(in) :: vlen
+  real(r8), intent(in)  :: t(vlen)  ! Temperature in Kelvin
+      real(r8), intent(out) :: es(vlen) ! SVP in Pa
+  real(r8) :: log_param
+  integer :: i
+  ! good down to -100 C
+
+  log_param = log10(6.1071_r8)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: Got it now, thanks!

File: src/physics/cam/aer_rad_props.F90 [hunk 21]
```diff
@@ -132,7 +132,7 @@ subroutine aer_rad_props_sw(list_idx, state, pbuf,  nnite, idxnite, &
 
    integer :: ncol
    integer :: lchnk
-   integer :: k       ! index
+   integer :: i, k       ! index
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/aer_rad_props.F90]: That's weird. I removed it.

File: src/physics/cam/clubb_intr.F90 [hunk 22]
```diff
@@ -3508,50 +3508,53 @@ end subroutine clubb_tend_cam
...
-  nitend = 0._r8
-
-!	calculate qsati from t,p,q
-
-  call wv_sat_qsat_ice(t, p, ESI, QSI)
-
-  if (naai > 1.e-18_r8 .and. qv > QSI) then
+  real(r8) :: ESI(vlen)
+  real(r8) :: QSI(vlen)
+!!  real(r8) :: tau
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90]: Sure

File: src/physics/cam/macrop_driver.F90 [hunk 23]
```diff
@@ -1128,55 +1128,64 @@ end subroutine macrop_driver_tend
...
+   
+        qctend(i) = (qv(i) - QSL(i)) / deltat
+        qvtend(i) = 0._r8 - qctend(i)
+        stend(i)  = qctend(i) * xxlv    ! moist static energy tend...[J/kg/s] !
+   
+        ! If drops  exists (more than 1 L-1) and there is condensation,
+        ! do not add to number (= growth), otherwise  add 6um drops.
+        !
+        ! This is somewhat arbitrary, but ensures that some reasonable droplet
+        ! size is create to remove the excess water. This could be enhanced to
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/macrop_driver.F90]: Fixed

**Review by cacraigucar — APPROVED** [review]

File: src/physics/cam/wv_sat_methods.F90 [hunk 24]
```diff
@@ -379,6 +547,27 @@ elemental function GoffGratch_svp_water(t) result(es)
...
+  integer, intent(in) :: vlen
+  real(r8), intent(in)  :: t(vlen)  ! Temperature in Kelvin
+  real(r8), intent(out) :: es(vlen) ! SVP in Pa
+  real(r8) :: log_tboil, log_ps
+  integer :: i
+  ! Goff, J. A., and S. Gratch. “Low-Pressure Properties of Water from -160F
+  ! to 212F.” Trans. Am. Soc. Heat. Vent. Eng. 52 (1946): 95–121.
+  ! uncertain below -70 C
+  log_tboil = log10(tboil)
+  log_ps = log10(1013.246_r8)
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:560]: Is there a reason this is not a parameter?
```
 real(r8), parameter :: log_ps = log10(1013.246_r8)
```

File: src/physics/cam/wv_sat_methods.F90 [hunk 25]
```diff
@@ -447,6 +684,30 @@ elemental function OldGoffGratch_svp_water(t) result(es)
...
 
+subroutine OldGoffGratch_svp_water_vect(t,es,vlen)
+  integer, intent(in) :: vlen
+  real(r8), intent(in)  :: t(vlen)
+  real(r8), intent(out) :: es(vlen)
+
+  real(r8), dimension(vlen) :: e1, e2, f1, f2, f3, f4
+
+  real(r8), parameter :: psp = 1013.246_r8
+  real(r8) :: f5 = log10(psp)
```
Comment (fvitt) [inline src/physics/cam/wv_sat_methods.F90:695]: Should `f5` a parameter? `psp` is a parameter.
```
real(r8), parameter :: f5 = log10(psp)
```

**Review by fvitt — APPROVED** [review]

File: src/physics/cam/wv_sat_methods.F90 (hunk 24 above)
Comment (fvitt) [reply src/physics/cam/wv_sat_methods.F90:560]: Maybe the log_ps parameter be defined once at the module level?

File: src/physics/cam/wv_sat_methods.F90 (hunk 25 above)
Comment (gold2718) [reply src/physics/cam/wv_sat_methods.F90:695]: I agree on the parameter issue. However, if there is a good reason to _not_ make it a parameter, please move the initialization (see comment on line 695).

File: src/physics/cam/wv_sat_methods.F90 [hunk 26]
```diff
@@ -447,6 +684,30 @@ elemental function OldGoffGratch_svp_water(t) result(es)
...
+  real(r8) :: f = 0._r8
```
Comment (gold2718) [inline src/physics/cam/wv_sat_methods.F90:696]: Do not set `f` here. If you initialize a variable in the declaration statement of a subroutine or function, it invokes the `save` attribute which can affect performance and possibly give you unexpected answers. I do not see a reason to set `f` at all given that it only possible use is after it is set in the code.

File: src/physics/cam/wv_sat_methods.F90 (hunk 24 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: Ok, moved the log_ps parameter to the module level. But I only updated the two functions that you guys have been looking at. The whole module needs a massive rewrite, and I don't have time to do that right now.

File: src/physics/cam/wv_sat_methods.F90 (hunk 25 above)
Comment (Katetc) [reply src/physics/cam/wv_sat_methods.F90]: As mentioned in the previous comment, I made log_ps a module level parameter and it is now used in these two functions. I'm not here to rewrite all of wv_sat_methods.F90 right now, though.

**Comment by cacraigucar** [comment]
Does your latest commit (which you are sending back to CISL) mean that you will be delaying the CAM tag until they give you a solution?

**Comment by Katetc** [comment]
> Does your latest commit (which you are sending back to CISL) mean that you will be delaying the CAM tag until they give you a solution?

No, I just won't include the water vapor optimized calls in ZM microphysics in this tag. Jian is working on a new set of changes right now, so I'll have him rework this bit of code with his current stuff and it can be included in his next PR.

**Comment by andrewgettelman** [comment]
Agreed. zm convective microphysics is optional (not default) code, rarely used.
