### PR TITLE
cam6_4_123: Misc changes to CAM

### LINKED ISSUE #1179: bad mpas L93 default ncdata files
### What happened?

The FMTHIST compsets blow-up of the box using mpas, which @gdicker1 tracked down to missing values in the real world inic files for the 120 km and 480 km grids:
```
<ncdata hgrid="mpasa480" nlev="93" >atm/cam/inic/mpas/cami_01-01-2000_00Z_mpasa480_L93_CFSR_c240814.nc</ncdata>
<ncdata hgrid="mpasa120" nlev="93" >atm/cam/inic/mpas/cami_01-01-2000_00Z_mpasa120_L93_CFSR_c240814.nc</ncdata>
```
The issue seems to be that the ~80 km model top in L93 is well above the ~60 km CFSR top used to create the inic. One solutions is to use the ERA5 model level dataset, which has an ~80 km top and only requires extrapolation into the top most layer of L93 mpas. New inic's could be generated using betacast or the mpas inic generator.

I have not checked whether the analytic ic inic's are similarly problematic:
```
<ncdata hgrid="mpasa480" nlev="93" analytic_ic="1" >atm/cam/inic/mpas/mpasa480_L93_notopo_coords_c240814.nc</ncdata>
<ncdata hgrid="mpasa120" nlev="93" analytic_ic="1" >atm/cam/inic/mpas/mpasa120_L93_notopo_coords_c240814.nc</ncdata>
<ncdata hgrid="mpasa60"  nlev="93" analytic_ic="1" >atm/cam/inic/mpas/mpasa60_L93_notopo_coords_c240814.nc</ncdata>
```

### What are the steps to reproduce the bug?

Run FMTHIST with ```mpasa120_mpasa120``` or ```mpasa480_mpasa480```.

### What CAM tag were you using?

cam6_4_038

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes, but I will need some help

### Extra info

_No response_

### LINKED ISSUE #1337: Use of pointers in user defined types and memory leaks
### Issue Type

Code Clean-up

### Issue Description

The CAM-SE dynamical core has several modules that have user-defined types that include pointers.  The Fortran standard does not require the pointer variables to be deallocated when the local variables go out of scope.  While the gfortran and Intel compilers will deallocate this memory, the NVHPC compiler will not, resulting in memory leaks. The solution is to use allocatables when possible in user-defined types, and add explicit finalization methods to make it easier to deallocate memory.   

### Will this change answers?

No

### Will you be implementing this yourself?

Yes

### LINKED ISSUE #1351: Share files and changes from EarthWorks
### What is the feature/what would you like to discuss?

The EarthWorks project has some input files and settings for runs using mpasa60, mpasa30, and mpasa15. As CESM3 and other projects look at higher resolution runs, these values may be helpful. Merging these changes would also reduce the difference between ESCOMP/CAM and EarthWorksOrg/CAM.

I think this is unlikely to change answers. I don't think any of these changes are in tests usually run by CESM or CAM folks.

### Is there anyone in particular you want to be part of this conversation?

@mgduda

### Will this change (regression test) answers?

I Don't Know

### Will you be implementing this enhancement yourself?

Yes

### LINKED ISSUE #1371: part of cam6_4_123: update topo file for ne30np4 (no physics grid), ne16pg3 and ne30pg2
### What is the feature/what would you like to discuss?

It has come to my attention that ACOM uses the non-physgrid version of ne30 extensively, therefore the topo file should be updated (the current default is from 2017!).

Please replace

```
<bnd_topo hgrid="ne30np4"         >atm/cam/topo/se/ne30np4_nc3000_Co060_Fi001_PF_nullRR_Nsw042_20171020.nc</bnd_topo>
```

with

```
<bnd_topo hgrid="ne30np4"         >atm/cam/topo/se/ne30np4_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_greenlndantarcsgh30fac2.50_20250822.nc</bnd_topo>
```

once the file

/glade/campaign/cgd/amp/pel/topo/cesm3/ne30np4_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_greenlndantarcsgh30fac2.50_20250825.nc

has been copied over to the cesm inputdata directory.

There are signifcant differences betweem the two topo files:

PHIS

Image

SGH

Image

SGH30

Image

and these fields are not in one of the files:

```SGH_UF, TERR_UF, MXVRX, MXVRY, WGHTS, CWGHT, COUNT.```

Update ne16pg3 topo file (only field that changed is SGH30):

Please change

<bnd_topo hgrid="ne16np4"  npg="3">atm/cam/topo/se/ne16pg3_gmted2010_modis_bedmachine_nc3000_Laplace0200_20230202.nc</bnd_topo>

to 

<bnd_topo hgrid="ne16np4"  npg="3">atm/cam/topo/se/ne16pg3_gmted2010_modis_bedmachine_nc3000_Laplace0200_noleak_greenlndantarcsgh30fac2.50_20250825.nc</bnd_topo>

once 

/glade/campaign/cgd/amp/pel/topo/cesm3/ne16pg3_gmted2010_modis_bedmachine_nc3000_Laplace0200_noleak_greenlndantarcsgh30fac2.50_20250825.nc

has been copied to the CESM input directory. SGH30 difference between new and old topo file below:

Image

Other fields are close to round-off the same.

Update ne30pg2 grid (mainly for StormSPEED project):

Replace

<bnd_topo hgrid="ne30np4"  npg="2">atm/cam/topo/se/ne30pg2_nc3000_Co060_Fi001_PF_nullRR_Nsw042_20171014.nc</bnd_topo>

with 

<bnd_topo hgrid="ne30np4"  npg="2">atm/cam/topo/se/ne30pg2_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_greenlndantarcsgh30fac2.50_20250825.nc</bnd_topo>

once

 /glade/campaign/cgd/amp/pel/topo/cesm3/ne30pg2_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_greenlndantarcsgh30fac2.50_20250825.nc

has been copied the CESM input data directory.

### Is there anyone in particular you want to be part of this conversation?

@tilmes @fvitt @JulioTBacmeister 

### Will this change (regression test) answers?

I Don't Know

### Will you be implementing this enhancement yourself?

Any CAM SE can do this

### LINKED ISSUE #1377: Move FMS support requirement to components
### What is the feature/what would you like to discuss?

In CMEPS https://github.com/ESCOMP/CMEPS/pull/584 I have added support for a new XML variable
CASE_SUPPORT_LIBRARIES.  One of those support libraries required when cam_dycore is fv3 is FMS, cam should set this value itself in buildcpp.

### Is there anyone in particular you want to be part of this conversation?

@jtruesdal 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes

### LINKED ISSUE #1383: New RRTMGP library version fails with nvhpc
### Fixes from Jian:
1. [ccs_config_cesm1.0.59](https://github.com/ESMCI/ccs_config_cesm/releases/tag/ccs_config_cesm1.0.59)
2. https://github.com/ESCOMP/CAM/pull/1386

### What happened?

cam6_4_114 brought in the latest RRTMGP library (updating from v1.7 to v1.9.2). I have confimed that v1.8 does not produce the error. [Here](https://github.com/earth-system-radiation/rte-rrtmgp/compare/v1.8...v1.9.2) is what's new since v1.8.

The nvhpc aux_cam regression test fails with the following error:
```
ERROR: Longwave down sent from the atmosphere model is negative or zero
```

### What are the steps to reproduce the bug?

1. Check out CAM tag cam6_4_114
2. Run the nvhpc test on derecho: `env BL_TESTDIR=/glade/campaign/cesm/community/amwg/cam_baselines/cam6_4_114_nvhpc CAM_FC=nvhpc  ./test_driver.sh -f`
3. Observe the failing test in your scratch directory.

### What CAM tag were you using?

cam6_4_114

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

NVHPC

### Path to a case directory, if applicable

/glade/derecho/scratch/cacraig/aux_cam_nvhpc_20250905161547/ERS_Ln9.ne30pg3_ne30pg3_mt232.FHISTC_LTso.derecho_nvhpc.cam-outfrq9s_gpu_default.GC.aux_cam_nvhpc_20250905161547

### Will you be addressing this bug yourself?

Yes, but I will need some help

### Extra info

_No response_

### LINKED ISSUE #1387: rei_cloud, rel_cloud output units for CAM4 (RK microphysics) are incorrect
### What happened?

This was reported by @brianpm via response to forum post https://bb.cgd.ucar.edu/cesm/threads/possible-error-units-of-effective-radius-of-droplet-and-ice-in-cloud.10074/

RK microphysics was CCPPized, but this output code is in current CAM. CAM-SIMA is unaffected.

> the units of both REL and REI should be microns.

### What are the steps to reproduce the bug?

Run CAM4
Output `rel_cloud` and/or `rei_cloud` fields; observe units are incorrect

### What CAM tag were you using?

cam6_4_114

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

_No response_

### LINKED ISSUE #1397: COSP is not working properly out-of-the-box - interpolate_output and cosp_histfile_num mismatch tripped
### What happened?

In #1385 @islasimpson reported:
I'm trying with this alpha tag but I can't compile. I get an error "interpolate_output does not work with COSP". I have interpolate_output = .true. in user_nl_cam, but I'm not setting anything related to COSP. I'm running the same script as I was using with cam6_4_097 and only changed the tag. Do I now have to actively turn COSP off?

@gold2718 responded: 
This is a weird interaction in that the default value for the COSP history file is 1 (i.e., h0).
Try setting cosp_histfile_num to something other than 1 in your user_nl_cam.
What I would like to do is fix the problem but probably not this week. The new build-namelist block was put in during PR https://github.com/ESCOMP/CAM/pull/1359 (cam6_4_109) but I do not see any issue on fixing the underlying problem (interpolated output for multi-dimensional fields such as COSP).

### What are the steps to reproduce the bug?

See above

### What CAM tag were you using?

cam6_4_116

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

No

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by cacraigucar**
Closes #1388 and closes #1387 - fix rei_cloud and rel_cloud units to um for CAM4 - @jimmielin 
Closes #1352 ,  closes #1351 and closes #1179 - share some input and settings from EarthWorks - @gdicker1 
Closes #1356 and closes #1337 - Reduce potential memory leaks - @johnmauff 
Closes #1367 and closes #1367 - Add support for NUOPC write_restart_at_endorun - @jedwards4b 
Closes #1371 - Update topo file for ne30np4 (no physics grid), ne16pg3 and ne30pg2 - @PeterHjortLauritzen 
Closes #1378 and closes #1377 - Move FMS support requirement to components - @jedwards4b 
Closes #1386 and closes #1383 - Fix the CAM+RRTMGP GPU interface bug - @sjsprecious 
Closes #1398 and closes #1397 - fix check of COSP with interpolated output - @brian-eaton

### CODE REVIEW

**Review by sjsprecious — APPROVED** [review]
The RRTMGP GPU bug fix looks good to me. Thanks @cacraigucar for working on this.

**Review by jimmielin — APPROVED** [review]
Thank you @cacraigucar!

**Review by jedwards4b — APPROVED** [review]

File: src/dynamics/se/dycore/interpolate_mod.F90 [hunk 1]
```diff
@@ -114,6 +122,34 @@ module interpolate_mod
...
+  !
+  ! Destructors for interpdata_t
+  !
+  subroutine finalize_interpdata_t(this)
+     class(interpdata_t), intent(inout) :: this
+     call finalize_interpdata_t_core(this)
+  end subroutine finalize_interpdata_t
+  subroutine finalize_interpdata_t_core(this)
+     type (interpdata_t) :: this
+     if(associated(this%interp_xy)) deallocate(this%interp_xy)
```
Comment (johnmauff) [inline src/dynamics/se/dycore/interpolate_mod.F90]: @cacraigucar There appears to be an inconsistency with the definition of the interpdata_t data structure and this finalize subroutine.  The fix would be to replace the associated() in lines 134, 135, and 136 with a call to allocated()

**Review by PeterHjortLauritzen — APPROVED** [review]

**Review by johnmauff — APPROVED** [review]
