### PR TITLE
cam6_3_152:  "Science optimize" SE-CSLAM dycore and stabilize WACCM

### LINKED ISSUE #552: Always read in PHIS on GLL grid
Related to issue #551: 

The spectral-element dynamical core should always see the same topography (with the same GLL resolution). Currently that is not the case in physics grid configurations. I am suggesting to make this change when we update to GMTED2010-bedmachine topography since the topo file will need PHIS on GLL grid whereas the rest of the variables should be on the physics grid (currently all variables are on physics grid). 

Note: dyn_comp.F90 will be less lines of code with this modification!

### LINKED ISSUE #864: dycore derived_phys ordering should match physics_update
### What happened?

Will be addressed with PR associated with #949 

Both the SE and MPAS dycores contain a "derived_phys" subroutine that calculates the geopotential, which now includes the use of thermodynamically-active water species.  However, the qneg check, which ensures that all water species have physical (e.g. non-negative) values, is performed _after_ the geopotential calculation, which means any negative mixing ratio values could potentially impact the geopotential values themselves (which could be hard to catch).

To remedy this issue, it would make sense for these subroutines to have the same ordering as `physics_update`, which runs qneg first before calculating the geopotential.  That way no negative values will be mistakenly used, and the geopotential values will still be "in sync" with the water species mixing ratio values.

### What are the steps to reproduce the bug?

Look at the ordering in either `derived_phys_dry` in `src/dynamics/se/dp_coupling.F90` or in `derived_phys` in `src/dynamics/mpas/dp_coupling.F90`, and compare it to the ordering of `physics_update` in `src/physics/cam/physics_types.F90`.

I should note that this is only a "theoretical" bug.  So far it hasn't appeared to cause problems (but it feels like it eventually will if given the "right" model configuration). 

### What CAM tag were you using?

cam6_3_120

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Any CAM SE can do this

### Extra info

Along with this re-ordering, should `derived_phys_dry` still be labeled "dry" given that it now uses water species amounts in some of its calculations?

### LINKED ISSUE #951: remove pg4 topo files from default namelist
### Issue Type

Code Clean-up

### Issue Description

remove pg4 topo files from default namelist

### Will this change answers?

No

### Will you be implementing this yourself?

Yes

### LINKED ISSUE #970: ModuleNotFoundError: No module named 'imp'
### Issue Type

Infrastructure Update

### Issue Description

Recent versions of python no longer support the imp module:

File "/glade/work/jedwards/sandboxes/CAM/cime_config/buildnml", line 7, in <module>
            import sys, os, shutil, filecmp, imp
        ModuleNotFoundError: No module named 'imp'

### Will this change answers?

No

### Will you be implementing this yourself?

Any CAM SE can do this

### PR DESCRIPTION
**Pull request by PeterHjortLauritzen**
Increase computational throughput of the SE-CSLAM dynamical core by:

 - Reducing se_nsplit to 2 (from 3) in FMT: CSLAM now runs with ~30% longer time-step compared to baseline
 - No double advection of thermodynamic active tracers when using CSLAM. Overwrite GLL values of Q, CLDLIQ,
   etc. every vertical remapping time-step with CSLAM values (interpolated from physics grid to GLL grid)
 - Vertical sponge layer diffusion in physics for WACCM and WACCM-x
 - No increased hyperdiffusion in sponge for FLT and FMT

Provide stable configuration for WACCM with spectral-elements (ne30pg3 and ne16pg3): namelist changes

Resolve #864 (qneg issue)
Resolve #552  (read in topo file on GLL grid if available)
Resolve #951 (remove namelist defaults for pg4 grids)
Resolve #970 (Remove deprecated 'imp' module)

### CODE REVIEW

File: src/dynamics/se/dyn_comp.F90 [hunk 1]
```diff
@@ -1969,14 +1974,8 @@ subroutine set_phis(dyn_in)
...
    end do
-   if (fv_nphys > 0) then
-      do ie = 1, nelemd
-         dyn_in%fvm(ie)%phis_physgrid = RESHAPE(phis_phys_tmp(:,ie),(/fv_nphys,fv_nphys/))
-      end do
-   end if
-
    deallocate(phis_tmp)
-   if (fv_nphys > 0) then
+   if (allocated(phis_phys_tmp)) then
```
Comment (nusbaume) [inline src/dynamics/se/dyn_comp.F90:1978]: It looks like the `phis_phys_tmp` variable is no longer used anymore after the `map_phis_from_physgrid_to_gll` call above.  Maybe it makes sense to simply deallocate the variable right after that call instead of down here?  That way we can also get rid of the `allocated` check being done here (as the variable will always have to be allocated).

File: src/dynamics/se/dyn_grid.F90 [hunk 2]
```diff
@@ -182,7 +182,7 @@ subroutine dyn_grid_init()
       end if
 
       if (fv_nphys > 0) then
```
Comment (nusbaume) [inline src/dynamics/se/dyn_grid.F90:184]: Use `use_cslam` here?

```suggestion
      if (use_cslam) then
```

File: src/physics/cam/vertical_diffusion.F90 [hunk 3]
```diff
@@ -301,6 +302,27 @@ subroutine vertical_diffusion_init(pbuf2d)
...
+        !
+        ! WACCM and WACCM-x
+        !
+        write(iulog,*)'Artificial sponge layer vertical diffusion added:'
+        write(iulog,*)'vertical diffusion coefficient at interface 1 is increased by 2.0E6 m^2/s2'
+        write(iulog,*)'vertical diffusion coefficient at interface 2 is increased by 2.0E6 m^2/s2'
+        write(iulog,*)'vertical diffusion coefficient at interface 3 is increased by 1.5E6 m^2/s2'
+        write(iulog,*)'vertical diffusion coefficient at interface 4 is increased by 1.0E6 m^2/s2'
+        write(iulog,*)'vertical diffusion coefficient at interface 5 is increased by 0.5E6 m^2/s2'
+        write(iulog,*)'vertical diffusion coefficient at interface 6 is increased by 0.1E6 m^2/s2'
```
Comment (nusbaume) [inline src/physics/cam/vertical_diffusion.F90:324]: I might vote to remove the `^` symbol here since it isn't being used in the denominator.  Plus we can make it better match CCPP unit text:

```suggestion
        write(iulog,*)'Artificial sponge layer vertical diffusion added:'
        write(iulog,*)'vertical diffusion coefficient at interface 1 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 2 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 3 is increased by 0.5E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 4 is increased by 0.1E6 m2 s-2'
     else if (ptop_ref>1e-4_r8) then
        !
        ! WACCM and WACCM-x
        !
        write(iulog,*)'Artificial sponge layer vertical diffusion added:'
        write(iulog,*)'vertical diffusion coefficient at interface 1 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 2 is increased by 2.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 3 is increased by 1.5E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 4 is increased by 1.0E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 5 is increased by 0.5E6 m2 s-2'
        write(iulog,*)'vertical diffusion coefficient at interface 6 is increased by 0.1E6 m2 s-2'
```

File: src/physics/cam/vertical_diffusion.F90 [hunk 4]
```diff
@@ -1067,6 +1089,36 @@ subroutine vertical_diffusion_tend( &
...
+  ! add sponge layer vertical diffusion
+  !
+  if (ptop_ref>300.0_r8) then
+     !
+     ! for low tops the tanh formulae below makes the sponge excessively deep
+     !
+  else if (ptop_ref>100.0_r8) then
+     !
+     ! CAM6 top (~225 Pa) or CAM7 low top
+     !
```
Comment (nusbaume) [inline src/physics/cam/vertical_diffusion.F90:1102]: I might vote to remove these checks because they don't appear to be doing anything.

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks good, but I did have some small suggestions and a few questions.

File: src/dynamics/se/dycore/global_norms_mod.F90 [hunk 5]
```diff
@@ -600,12 +600,12 @@ subroutine print_cfl(elem,hybrid,nets,nete,dtnu,ptop,pmid,&
     lev_set = sponge_del4_lev < 0
     if (ptop>1000.0_r8) then
       !
-      ! low top (~1000 Pa)
+      ! low top (~10 Pa)
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/dynamics/se/dycore/global_norms_mod.F90:603]: @PeterHjortLauritzen it would be good for you to double-check this.  Thanks!

File: doc/ChangeLog [hunk 6]
```diff
@@ -1,5 +1,91 @@
...
+
+List any changes to the defaults for the boundary datasets:
+	- new default topo file for ne30pg3
+
+Describe any substantial timing or memory changes:
+
+	- approximately 30% speed-up of entire CAM model using COMPSET FLTHIST or FMTHIST
+
+
+List all existing files that have been modified, and describe the changes:
```
Comment (fvitt) [inline doc/ChangeLog:47]: Please include the changes you have in cime_config scripts.

File: src/dynamics/se/dycore/global_norms_mod.F90 [hunk 7]
```diff
@@ -634,28 +634,38 @@ subroutine print_cfl(elem,hybrid,nets,nete,dtnu,ptop,pmid,&
...
+    if (top_140_600km) then
+      umax = 800._r8
+    end if
     if (top_090_140km.or.top_140_600km) then
-      if (sponge_del4_lev       <0) sponge_del4_lev        = 10
+      if (sponge_del4_lev       <0) sponge_del4_lev        = 20
       if (sponge_del4_nu_fac    <0) sponge_del4_nu_fac     = 5.0_r8
-      if (sponge_del4_nu_div_fac<0) sponge_del4_nu_div_fac = 7.5_r8
+      if (sponge_del4_nu_div_fac<0) sponge_del4_nu_div_fac = 10.0_r8
     end if
```
Comment (fvitt) [inline src/dynamics/se/dycore/global_norms_mod.F90:669]: This section could be shortened to something like:
```
    if (sponge_del4_lev       <0) sponge_del4_lev        = 1
    if (sponge_del4_nu_fac    <0) sponge_del4_nu_fac     = 1.0_r8
    if (sponge_del4_nu_div_fac<0) sponge_del4_nu_div_fac = 1.0_r8

    if (top_090_140km.or.top_140_600km) then ! defaults for waccm(x)
      if (sponge_del4_lev       <0) sponge_del4_lev        = 20
      if (sponge_del4_nu_fac    <0) sponge_del4_nu_fac     = 5.0_r8
      if (sponge_del4_nu_div_fac<0) sponge_del4_nu_div_fac = 10.0_r8
    end if

    ! set max wind speed for diagnostics
    umax = 120.0_r8
    if (top_042_090km) then
       umax = 240._r8
    else if (top_090_140km) then
       umax = 300._r8
    else if (top_140_600km) then
       umax = 800._r8
    end if

```

File: src/dynamics/se/dycore/prim_driver_mod.F90 [hunk 8]
```diff
@@ -537,32 +555,19 @@ subroutine prim_step(elem, fvm, hybrid,nets,nete, dt, tl, hvcoord, rstep)
...
       call Prim_Advec_Tracers_remap(elem, deriv,hvcoord,hybridnew,dt_q,tl,nets,nete)
       !$OMP END PARALLEL
       call omp_set_nested(.false.)
       call t_stopf('prim_advec_tracers_remap')
-    end if
-    !
-    ! only run fvm transport every fvm_supercycling rstep
-    !
-    if (use_cslam) then
+   else
```
Comment (fvitt) [inline src/dynamics/se/dycore/prim_driver_mod.F90:568]: Fix indentation

**Review by fvitt — CHANGES_REQUESTED** [review]
Here are some initial comments

File: src/dynamics/se/dycore/fvm_mapping.F90 [hunk 9]
```diff
@@ -1318,5 +1284,64 @@ subroutine get_q_overlap_save(ie,k,fvm,q_fvm,num_trac,q_phys)
      end do
    end subroutine get_q_overlap_save
 
+   subroutine cslam2gll(elem, fvm, hybrid,nets,nete, tl_f, tl_qdp)
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/dynamics/se/dycore/fvm_mapping.F90:1287]: @PeterHjortLauritzen If you can provide me a text description of what this subroutine is doing then I can add it to my code review updates.  Thanks!

File: src/dynamics/se/dycore/fvm_mapping.F90 [hunk 10]
```diff
@@ -240,21 +184,33 @@ subroutine fvm2dyntn(fld_fvm,fld_gll,hybrid,nets,nete,numlev,num_flds,fvm,llimit
     type (hybrid_t)      , intent(in)    :: hybrid
     type(fvm_struct)     , intent(in)    :: fvm(nets:nete)
     logical              , intent(in)    :: llimiter(num_flds)
+    logical, optional    , intent(in)    :: halo_filled
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/dynamics/se/dycore/fvm_mapping.F90:187]: @PeterHjortLauritzen if you can provide a descripton for what `halo_filled` does then I can add it to the PR.  Thanks!

File: bld/namelist_files/namelist_definition.xml [hunk 11]
```diff
@@ -8227,6 +8227,20 @@ Default: Set by build-namelist.
...
+  0: physics tendencies will be added every vertical remapping time-step (dt_phys/se_nsplit)
+     for se_ftype=0,2
+
+  1: physics tendencies will be added every dynamics time-step (dt_phys/se_nsplit*se_rsplit)
+     for se_ftype=0,2
+
+     If se_ftype=1 then se_dribble_in_rsplit_loop has no effect since physics tendencies are added as an adjustment
+
+  Default: Set by build-namelist.
+</entry>
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply bld/namelist_files/namelist_definition.xml:8242]: There might. Hence I would prefer to keep integer.

File: src/dynamics/se/dycore/fvm_mapping.F90 [hunk 12]
```diff
@@ -1318,5 +1284,64 @@ subroutine get_q_overlap_save(ie,k,fvm,q_fvm,num_trac,q_phys)
...
+     !
+     ! for tensor product Lagrange interpolation
+     !
+     integer              :: nflds
+     logical, allocatable :: llimiter(:)
+     call t_startf('cslam2gll')
+     nflds = thermodynamic_active_species_num
+     allocate(fld_fvm(1-nhc:nc+nhc,1-nhc:nc+nhc,nlev,nflds,nets:nete))
+     allocate(fld_gll(np,np,nlev,thermodynamic_active_species_num,nets:nete))
+     allocate(llimiter(nflds))
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/fvm_mapping.F90:1326]: done

File: src/dynamics/se/dycore/global_norms_mod.F90 (hunk 5 above)
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/global_norms_mod.F90:603]: Code correct. Changed comments.

File: src/dynamics/se/dyn_comp.F90 [hunk 13]
```diff
@@ -1878,12 +1897,36 @@ subroutine set_phis(dyn_in)
...
+         ! map to the physgrid in d_p_coupling
+         !
+         ! This requires a topo file with PHIS_gll on it ...
+         !
+         if (masterproc) then
+            write(iulog, *) "Reading in PHIS on GLL grid (mapped to physgrid in d_p_coupling)"
+         end if
+         call read_dyn_var(fieldname_gll, fh_topo, 'ncol_gll', phis_tmp)
+      else if (dyn_field_exists(fh_topo, trim(fieldname))) then
          if (fv_nphys == 0) then
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dyn_comp.F90:1913]: sure ... also changed in other places in dyn_comp.F90 for consistency!

File: src/dynamics/se/dyn_grid.F90 (hunk 2 above)
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dyn_grid.F90:184]: done

File: src/dynamics/se/dyn_comp.F90 (hunk 1 above)
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dyn_comp.F90]: sure

File: src/dynamics/se/dycore/fvm_mapping.F90 [hunk 14]
```diff
@@ -280,21 +236,33 @@ subroutine fvm2dynt1(fld_fvm,fld_gll,hybrid,nets,nete,numlev,fvm,llimiter)
     type (hybrid_t)      , intent(in)    :: hybrid
     type(fvm_struct)     , intent(in)    :: fvm(nets:nete)
     logical              , intent(in)    :: llimiter(1)
+    logical, optional    , intent(in)    :: halo_filled
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/fvm_mapping.F90]: sure

File: src/dynamics/se/dycore/fvm_mapping.F90 (hunk 9 above)
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/fvm_mapping.F90:1299]: done

File: src/dynamics/se/dycore/global_norms_mod.F90 (hunk 7 above)
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/global_norms_mod.F90:669]: new code adopted. thanks

File: src/dynamics/se/dycore/prim_driver_mod.F90 (hunk 8 above)
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/prim_driver_mod.F90:568]: done

File: src/dynamics/se/dycore/global_norms_mod.F90 [hunk 15]
```diff
@@ -634,28 +634,38 @@ subroutine print_cfl(elem,hybrid,nets,nete,dtnu,ptop,pmid,&
     !
     ! if user or namelist is not specifying sponge del4 settings here are best guesses (empirically determined)
     !
+    umax = 0.0_r8
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/global_norms_mod.F90]: done (fixed in Francis's code suggestion)

File: src/physics/cam/vertical_diffusion.F90 (hunk 4 above)
Comment (PeterHjortLauritzen) [reply src/physics/cam/vertical_diffusion.F90]: OK. Removed.

File: doc/ChangeLog (hunk 6 above)
Comment (PeterHjortLauritzen) [reply doc/ChangeLog:47]: @nusbaume can you do this?

**Comment by PeterHjortLauritzen** [comment]
@nusbaume and @fvitt: thank you for the code review. I believe I have addressed your comments/concerns.

File: doc/ChangeLog (hunk 6 above)
Comment (nusbaume) [reply doc/ChangeLog:47]: The `ChangeLog` should be fully updated now.  Thanks!

**Review by nusbaume — APPROVED** [review]
Everything now looks good to me!

File: src/physics/cam/vertical_diffusion.F90 [hunk 16]
```diff
@@ -1067,6 +1089,28 @@ subroutine vertical_diffusion_tend( &
...
+  else if (ptop_ref>1e-4_r8) then
+     !
+     ! WACCM and WACCM-x
+     !
+     kvm(:ncol,1) = kvm(:ncol,1)+2E6_r8
+     kvm(:ncol,2) = kvm(:ncol,2)+2E6_r8
+     kvm(:ncol,3) = kvm(:ncol,3)+1.5E6_r8
+     kvm(:ncol,4) = kvm(:ncol,4)+1.0E6_r8
+     kvm(:ncol,5) = kvm(:ncol,5)+0.5E6_r8
+     kvm(:ncol,6) = kvm(:ncol,6)+0.1E6_r8
```
Comment (fvitt) [inline src/physics/cam/vertical_diffusion.F90:1112]: You have these parameters definded in 2 places.  Here and in the log output in the init routine.  Can these be defined in 1 place, such as parameters global to this module?   If we need to adjust these parameters the changes can be done in 1 place.

**Review by fvitt — CHANGES_REQUESTED** [review]
Looking good. Just a couple more things.

File: src/dynamics/se/dycore/fvm_mapping.F90 [hunk 17]
```diff
@@ -87,9 +81,21 @@ subroutine phys2dyn_forcings_fvm(elem, fvm, hybrid,nets,nete,no_cslam, tl_f, tl_
...
+      if( ierr /= 0 ) then
+         write(iulog,*) 'phys2dyn_forcings_fvm:  fld_phys allocation error = ',ierr
+         call endrun('phys2dyn_forcings_fvm: failed to allocate fld_phys array')
+      end if
+      allocate(fld_gll(np,np,nlev,3,nets:nete), stat=ierr)
+      if( ierr /= 0 ) then
+         write(iulog,*) 'phys2dyn_forcings_fvm:  fld_gll allocation error = ',ierr
+         call endrun('phys2dyn_forcings_fvm: failed to allocate fld_gll array')
+      end if
+      allocate(llimiter(nflds), stat=ierr)
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/fvm_mapping.F90]: good catch; 3. Fixed

File: src/physics/cam/vertical_diffusion.F90 [hunk 18]
```diff
@@ -289,18 +292,58 @@ subroutine vertical_diffusion_init(pbuf2d)
...
+     kvm_sponge(5) = 0.5E6_r8
+     kvm_sponge(6) = 0.1E6_r8
+  else
+     allocate(kvm_sponge(1))
+     kvm_sponge(1) = 0.0_r8
+  end if
+  
   if (masterproc) then
      write(iulog,*)'Initializing vertical diffusion (vertical_diffusion_init)'
+     if (maxval(kvm_sponge(:))>0.0_r8) then
```
Comment (fvitt) [inline src/physics/cam/vertical_diffusion.F90:341]: Should check if `kvm_sponge` is allocated
```suggestion
     if (allocated(kvm_sponge)) then
```

**Review by fvitt — CHANGES_REQUESTED** [review]
1 more request

File: src/physics/cam/vertical_diffusion.F90 (hunk 18 above)
Comment (nusbaume) [reply src/physics/cam/vertical_diffusion.F90]: Good call!  I have added the `allocated` check as well as an `endrun` statement in the off chance the variable is never allocated (as it will fail downstream in that case).

@PeterHjortLauritzen just FYI.

**Comment by nusbaume** [comment]
@fvitt Sorry, I understand your concern now!  The variable `kvm_sponge` is now only allocated when it is actually being used, with the appropriate `allocated()` checks to make sure it doesn't break something if it hasn't been allocated.

**Review by fvitt — APPROVED** [review]
Looks good to me now.  Thanks.
