### PR TITLE
cam6_4_019: New CLUBB External to fix GPU problem

### LINKED ISSUE #1036: New CLUBB external with fixes to support GPU testing
### Issue Type

Externals Update

### Issue Description

Some issues have been found with the GPU code and the CLUBB externals. Te UWM guys are working on a new tag now to update the CLUBB external so the GPU test suite can move forward correctly.

Unsure of answer changes at this point. If there are any, they should be very minimal.

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

### PR DESCRIPTION
**Pull request by Katetc**
Small answer changes, but no new CLUBB science. Diagnostics can be found here:
https://webext.cgd.ucar.edu/F2000climo/newCLUBBtesting/larson_tag_20240605.katemerge.062724-0201.F2000dev.f09_f09_mg17_1_2_vs_larson_tag_control.cam6_3_162.062724-1359.F2000dev.f09_f09_mg17_1_2/website/index.html

Ran 6 year ne30 BLT1850 simulations to look at differences in applicable and longer runs. Had some trouble with diagnostics but the results can be found here:
[https://webext.cgd.ucar.edu/FHIST/clubb_tests/larson_tag_20240605.katemerge.071924-1633.FLTHIST.ne30pg3_g17_1979_1984_vs_larson_tag_control.cam6_4_007.071924-1639.FLTHIST.ne30pg3_g17_1979_1984/website/](https://webext.cgd.ucar.edu/FHIST/clubb_tests/larson_tag_20240605.katemerge.071924-1633.FLTHIST.ne30pg3_g17_1979_1984_vs_larson_tag_control.cam6_4_007.071924-1639.FLTHIST.ne30pg3_g17_1979_1984/website/)

Differences seem to be minimal.

Fixes #1036
closes #1048

### CODE REVIEW

**Review by cacraigucar — CHANGES_REQUESTED** [review]

**Review by sjsprecious — APPROVED** [review]
The current CLUBB GPU tag runs successfully on Derecho's GPU but fails the ensemble consistency test. The UWM group is debugging the GPU code now but we (CISL group) are fine with moving on with this PR and including the new CLUBB GPU tag in the CAM regression test.

**Comment by adamrher** [comment]
@Katetc I'm under the impression that these new clubb externals remove the ghost point from the thermodynamic 'zt' grid. But I'm not seeing a reduction in the size of the zt arrays in clubb_intr in this PR. What am I missing?

File: .gitmodules
Comment (sjsprecious) [inline .gitmodules:1]: The `ccs_config` tag needs to be updated to `ccs_config_cesm1.0.0` so that the CLUBB GPU code can be compiled correctly on the GPU.

**Review by sjsprecious — CHANGES_REQUESTED** [review]

File: src/physics/cam/clubb_intr.F90 [hunk 1]
```diff
@@ -1810,18 +1850,25 @@ subroutine clubb_ini_cam(pbuf2d)
       call addfld ( 'edmf_qtflx'    , (/ 'ilev' /), 'A', 'W/m2'    , 'qt flux (EDMF)' )
     end if
 
+#ifndef SILHS
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:1853]: Couldn't this be wrapped in a `    if ( trim(subcol_scheme) == 'SILHS' ) then`?  The only reason to put code like this inside a #ifndef directive is to hide it completely from the compiler.  I believe that hm_metadata and the two fields always are declared.

File: src/physics/cam/clubb_intr.F90 [hunk 2]
```diff
@@ -1810,18 +1850,25 @@ subroutine clubb_ini_cam(pbuf2d)
...
+    ! hm_metadata is set up by calling init_pdf_hydromet_arrays_api in subcol_init_SILHS.
+    ! So if we are not using silhs, we allocate the parts of hm_metadata that need allocating
+    ! in order to making intel debug tests happy.
+    allocate( hm_metadata%hydromet_list(1) )
+    allocate( hm_metadata%l_mix_rat_hm(1) )
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:1858]: Need to return and check an error code for the allocations.

**Review by cacraigucar — CHANGES_REQUESTED** [review]

**Comment by cacraigucar** [comment]
@adamrher and @bstephens82 - @Katetc requested reviews from both of you.  Please either remove yourself as a reviewer or do a review when you can.

**Review by adamrher — APPROVED** [review]
I'm approving this PR, but would like to understand why all the arrays on the thermodynamic grid in clubb_intr.F90 are still retaining their ghost points. It was my understanding that this PR is removing the ghost point? Is the plan to just do that in the clubb externals, not the CAM interface?

For example, ```rho_zt``` is still of size ```dimension(state%ncol,pverp+1-top_lev)``` in clubb_intr.F90; it has the ghost point.

**Comment by vlarson** [comment]
> I'm approving this PR, but would like to understand why all the arrays on the thermodynamic grid in clubb_intr.F90 are still retaining their ghost points. It was my understanding that this PR is removing the ghost point? Is the plan to just do that in the clubb externals, not the CAM interface?
> 
> For example, `rho_zt` is still of size `dimension(state%ncol,pverp+1-top_lev)` in clubb_intr.F90; it has the ghost point.

This code merely changes some lower BCs to one-sided derivatives within CLUBB core (and fixes some minor bugs involving full-level variables being placed on the wrong (half-level) grid levels).  This PR doesn't change the clubb_intr, but UWM hopes to do that at some point.

**Comment by vlarson** [comment]
@adamrher, do you think that the changes in the solution look "large", or do they look like what you'd expect from truncation error (numerics)?

**Comment by adamrher** [comment]
Thanks for getting back to me on the ghost point. All is good then.

> @adamrher, do you think that the changes in the solution look "large", or do they look like what you'd expect from truncation error (numerics)?

The global mean turbulent fluxes and radiative fluxes look ~identical, so that suggests round-off level changes. There's some differences in the lat-lon map plots but those are what you would expect from comparing to two, 2 year long runs.

**Review by bstephens82 — APPROVED** [review]

File: src/physics/cam/clubb_intr.F90 [hunk 3]
```diff
@@ -51,6 +53,17 @@ module clubb_intr
...
+
+  type (hm_metadata_type) :: &
+    hm_metadata
+
+!$omp threadprivate(hm_metadata)
+
+  type (sclr_idx_type) :: &
+    sclr_idx
+
+!$omp threadprivate(sclr_idx)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90]: Removed all three

File: src/physics/cam/subcol_SILHS.F90 [hunk 4]
```diff
@@ -446,36 +452,38 @@ subroutine subcol_init_SILHS(pbuf2d)
...
+                                         subcol_SILHS_ncnp2_on_ncnm2,                 & ! intent(in)
+                                         hm_metadata, pdf_dim,                        & ! intent(out)
+                                         subcol_SILHS_hmp2_ip_on_hmm2_ip_slope,       & ! optional(in)
+                                         subcol_SILHS_hmp2_ip_on_hmm2_ip_intrcpt )      ! optional(in)
 
       !-------------------------------
       ! Set up hydrometeors and correlation arrays for SILHS
       !-------------------------------
+      allocate(corr_array_n_cloud(pdf_dim,pdf_dim))
+      allocate(corr_array_n_below(pdf_dim,pdf_dim))
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/subcol_SILHS.F90]: Fixed

File: .gitmodules
Comment (Katetc) [reply .gitmodules:1]: The current head of cam_development points to ccs_config_cesm1.0.0 so when this branch is merged up, the external will be correctly versioned.

File: src/physics/cam/clubb_intr.F90 (hunk 1 above)
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90]: Seems like it should be fine. I'm updating to just a straight "if" here.

File: src/physics/cam/clubb_intr.F90 (hunk 2 above)
Comment (Katetc) [reply src/physics/cam/clubb_intr.F90]: Fixed.

File: .gitmodules
Comment (sjsprecious) [reply .gitmodules:1]: Thanks Kate. That is great!

**Review by sjsprecious — APPROVED** [review]

File: src/physics/cam/clubb_intr.F90 (hunk 1 above)
Comment (cacraigucar) [reply src/physics/cam/clubb_intr.F90]: Should probably use `/=` instead of `.ne.` to adhere to the CAM coding standards (it is a should and not a must)

**Review by cacraigucar — APPROVED** [review]
One minor tweak requested, but I am approving

**Comment by Katetc** [comment]
> One minor tweak requested, but I am approving

I had a minor bug fix too, so I fixed this "if" statement as well.
