### PR TITLE
cam6_4_122: Prescribed MAM5 volcanic forcings

### LINKED ISSUE #1187: Updates needed for prescribed MAM5 stratospheric aerosols
### What is the feature/what would you like to discuss?

Update the `prescribed_strataero` module to consider the 5th mode of MAM5 aerosols.

In addition to new prescribed stratospheric aerosol files, updated radiative physprops files will need to be provided, which will be referenced in namelist settings.

### Is there anyone in particular you want to be part of this conversation?

@tilmes

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by fvitt**
This provides the ability to use prescribed MAM5 stratospheric aerosols.

Closes #1187

### CODE REVIEW

File: cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+rad_climate =
+ 'A:Q:H2O', 'N:O2:O2', 'A:CO2:CO2', 'N:ozone:O3', 'A:N2O:N2O', 'A:CH4:CH4', 'N:CFC11STAR:CFC11', 'A:CFC12:CFC12',
+ 'M:mam4_mode1:$DIN_LOC_ROOT/atm/cam/physprops/mam4_mode1_rrtmg_aeronetdust_sig1.6_dgnh.48_c140304.nc',
+ 'M:mam4_mode2:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/mam4_mode2_rrtmg_aitkendust_c141106.nc',
+ 'M:mam4_mode3:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/mam4_mode3_rrtmg_aeronetdust_c141106.nc',
+ 'M:mam4_mode4:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/mam4_mode4_rrtmg_c130628.nc',
+ 'N:VOLC_MMR1:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.6_mode1_c210211.nc',
+ 'N:VOLC_MMR2:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.6_mode2_c210211.nc',
+ 'N:VOLC_MMR3:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode3_c210211.nc',
+ 'N:VOLC_MMR5:/glade/campaign/cesm/cesmdata/inputdata/atm/cam/physprops/volc_camRRTMG_byradius_sigma1.2_mode3_c210211.nc'
```
Comment (cacraigucar) [inline cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam]: These need to use a relative path

File: src/chemistry/utils/prescribed_strataero.F90 [hunk 2]
```diff
@@ -192,7 +202,7 @@ subroutine prescribed_strataero_register()
        call pio_seterrorhandling(file_handle, PIO_BCAST_ERROR)
 
        ierr = pio_inq_varid( file_handle, 'so4mass_a1', varid )
-       three_mode = three_mode .and. (ierr.eq.PIO_NOERR)
+       three_mode = (ierr.eq.PIO_NOERR)
```
Comment (cacraigucar) [inline src/chemistry/utils/prescribed_strataero.F90]: Since you are modifying this line, perhaps you could also use modern Fortran comparison syntax (i.e. ==) here and on line 218 and 220

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam (hunk 1 above)
Comment (fvitt) [reply cime_config/testdefs/testmods_dirs/cam/outfrq9s_cam7_presc_volc/user_nl_cam]: fixed

File: src/chemistry/utils/prescribed_strataero.F90 (hunk 2 above)
Comment (fvitt) [reply src/chemistry/utils/prescribed_strataero.F90]: fixed

**Review by cacraigucar — APPROVED** [review]
