### PR TITLE
cam6_3_127:  Turn on HB where CLUBB is not active

### LINKED ISSUE #772: New topo file for ne30pg3 does not work with WACCM
### What happened?

Running with the new topo file` atm/cam/topo/se/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0100_20230105.nc` , the following regression test is failing:
ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30

It fails with the following error message:
763:k,dp_star_moist,u,v,T   66  24.689901113417    -10.83     -6.15    270.98
763:k,dp_star_moist,u,v,T   67  22.522655331776    -11.13     -6.97    272.49
763:k,dp_star_moist,u,v,T   68  20.162142134925    -10.94     -7.85    273.77
763:k,dp_star_moist,u,v,T   69  17.626340784678    -10.35     -8.58    274.78
763:k,dp_star_moist,u,v,T   70  14.950487855732     -9.00     -9.08    275.67
763: ERROR: negative moist layer thickness.  timestep or remap time too large

Discussions:

@PeterHjortLauritzen Hypothesis: 
`changing topo file makes the initial condition less balanced which leads to instability (vertically propagating  gravity waves); when the model top is over ~80km our dynamical cores have a hard time remaining stable. So we probably have to spin-up a new initial condition file. I can take a stab at that ...`

@fvitt 
`Probably need to spin up WACCM for the new topo file to get a new IC file.  I can see what I can do. `

@adamrher 
```
It looks like the sponge layer is producing negative pressure thicknesses on tasks 763 and 764:

763:k,dp_star_moist,u,v,T    1  -0.000000019366    708.58   -610.86   1657.68
763:k,dp_star_moist,u,v,T    2   0.000001158560    638.91   -535.36   1252.90
763:k,dp_star_moist,u,v,T    3   0.000004057404    573.90   -457.40   1068.71

764:k,dp_star_moist,u,v,T    1  -0.000000019366    708.58   -610.86   1657.68
764:k,dp_star_moist,u,v,T    2   0.000001158560    638.91   -535.36   1252.90
764:k,dp_star_moist,u,v,T    3   0.000004057404    573.90   -457.40   1068.71
```

@PeterHjortLauritzen 
`consistent with hypothesis ...`

@PeterHjortLauritzen 
```

Julio,


I am having trouble getting a stable simulation with the new topo file. Is your initialization (Python) software ready for generating balanced initial conditions? If yes, could you create one for the 70 level WACCM?

Grid and levels here:

/glade/p/cesmdata/cseg/inputdata/atm/waccm/ic/FW2000_ne30pg3_L70_01-01-0001_c200602.nc

Topo file:

/glade/p/cesmdata/cseg/inputdata/atm/cam/topo/se/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0100_20230105.nc
```

### What are the steps to reproduce the bug?

./create_test ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30

### What CAM tag were you using?

cam6_3_101 (not yet committed)

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/scratch/cacraig/ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30.20230329_093652_s86z2r/run

### Will you be addressing this bug yourself?

No

### Extra info

_No response_

### LINKED ISSUE #846: Option to turn on HB where CLUBB is not active
### What is the feature/what would you like to discuss?

To address stability issues with non-FV dynamical cores we would like to turn on Holtslag-Boville PBL scheme where CLUBB is not active. This code change will help address

https://github.com/ESCOMP/CAM/issues/772

Science discussion here:

https://github.com/NCAR/amwg_dev/discussions/284

Have code ready and will start PR when time permits ... branch with code mods here:

https://github.com/PeterHjortLauritzen/CAM/tree/clubb_hb

### Is there anyone in particular you want to be part of this conversation?

@adamrher @JulioTBacmeister @fvitt 

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by jtruesdal**
Free atmosphere Richardson number based mixing (using the free atmosphere part of the Holtslag-Boville PBL scheme) for those layers where CLUBB is not active (turned on in cam6 or cam_dev). Also helps stabilize less diffusive dynamical cores. A new namelist variable will be added to allow this new functionality.

The issue for the PR is #846.  This PR will also address issue #772

The science validation for this code is:
https://webext.cgd.ucar.edu/FLTHIST/f.cam6_3_112.FLTHIST_v0c.ne30.non-ogw-ubcT-effgw0.3-rdg_beta0.5-vtrmi1.5-hb-tt.001/atm/

closes #772
closes #846

### CODE REVIEW

**Comment by jtruesdal** [comment]
I am making some minor corrections due to regression test failures but will "undraft" this PR very soon.

**Comment by jtruesdal** [comment]
@nusbaume Ready for initial review.  This PR is only for using HB scheme with cam_dev.

File: src/physics/cam/hb_diff.F90 [hunk 1]
```diff
@@ -247,6 +248,96 @@ subroutine compute_hb_diff(lchnk, ncol,            &
...
+    real(r8), intent(in)  :: q(pcols,pver)            ! specific humidity [kg/kg]
+    real(r8), intent(in)  :: z(pcols,pver)            ! height above surface [m]
+    real(r8), intent(in)  :: u(pcols,pver)            ! zonal velocity
+    real(r8), intent(in)  :: v(pcols,pver)            ! meridional velocity
+    real(r8), intent(in)  :: taux(pcols)              ! zonal stress [N/m2]
+    real(r8), intent(in)  :: tauy(pcols)              ! meridional stress [N/m2]
+    real(r8), intent(in)  :: shflx(pcols)             ! sensible heat flux
+    real(r8), intent(in)  :: qflx(pcols)              ! water vapor flux
+    real(r8), intent(in)  :: pmid(pcols,pver)         ! midpoint pressures
+    character(len=16), intent(in) :: eddy_scheme
```
Comment (nusbaume) [inline src/physics/cam/hb_diff.F90:288]: I don't think `eddy_scheme` is being used in this subroutine.

File: src/physics/cam/vertical_diffusion.F90 [hunk 2]
```diff
@@ -1097,7 +1139,7 @@ subroutine vertical_diffusion_tend( &
      tauy = 0._r8
      shflux = 0._r8
      cflux(:,1) = 0._r8
-     if (cam_physpkg_is("cam_dev")) then
+     if (clubb_do_hb_above) then
```
Comment (nusbaume) [inline src/physics/cam/vertical_diffusion.F90:1142]: Do we actually want to do this?  I thought this change was originally because of the physics re-order in `cam_dev`, and so it might cause problems if someone turns this option on for, say, CAM6 physics.

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks pretty good!  I only have some (hopefully) minor change requests and a few questions.

**Comment by nusbaume** [comment]
Also forgot to ask if this PR will fully resolve issues #772 and #846?  If so it would be good to add the "closes #XXX" keyword to the main PR description box so that those issues are closed automatically once this PR is merged in.

File: src/physics/cam/hb_diff.F90 [hunk 3]
```diff
@@ -247,6 +248,96 @@ subroutine compute_hb_diff(lchnk, ncol,            &
...
+    !
+    !-----------------------------------------------------------------------
+
+    use pbl_utils, only: virtem, calc_ustar, calc_obklen, austausch_atm
+
+    !------------------------------Arguments--------------------------------
+    !
+    ! Input arguments
+    !
+    integer, intent(in) :: lchnk                      ! chunk index (for debug only)
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/hb_diff.F90:274]: Removed (Jesse = NAG compiler :-) )

File: src/physics/cam/hb_diff.F90 [hunk 4]
```diff
@@ -247,6 +248,96 @@ subroutine compute_hb_diff(lchnk, ncol,            &
...
+    real(r8), intent(out) :: kvq(pcols,pverp)         ! eddy diffusivity for constituents [m2/s]
+    real(r8), intent(out) :: cgh(pcols,pverp)         ! counter-gradient term for heat [J/kg/m]
+    real(r8), intent(out) :: cgs(pcols,pverp)         ! counter-gradient star (cg/flux)
+    real(r8), intent(out) :: ustar(pcols)             ! surface friction velocity [m/s]
+    real(r8), intent(out) :: obklen(pcols)            ! Obukhov length
+    real(r8), intent(out) :: ri(pcols,pver)           ! richardson number: n2/s2
+    !
+    !---------------------------Local workspace-----------------------------
+    !
+    real(r8) :: thv(pcols,pver)         ! virtual temperature
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/hb_diff.F90:303]: agree. Comment fixed

File: src/physics/cam/hb_diff.F90 [hunk 5]
```diff
@@ -247,6 +248,96 @@ subroutine compute_hb_diff(lchnk, ncol,            &
...
+    real(r8) :: rrho(pcols)             ! 1./bottom level density
+    real(r8) :: kqfs(pcols)             ! kinematic surf constituent flux (kg/m2/s)
+    real(r8) :: khfs(pcols)             ! kinimatic surface heat flux 
+    real(r8) :: kbfs(pcols)             ! surface buoyancy flux 
+    real(r8) :: kvf(pcols,pverp)        ! free atmospheric eddy diffsvty [m2/s]
+    real(r8) :: s2(pcols,pver)          ! shear squared
+    real(r8) :: n2(pcols,pver)          ! brunt vaisaila frequency
+
+    ! virtual temperature
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/hb_diff.F90:312]: fixed

File: src/physics/cam/hb_diff.F90 [hunk 6]
```diff
@@ -247,6 +248,96 @@ subroutine compute_hb_diff(lchnk, ncol,            &
...
+    !
+    call austausch_atm(pcols, ncol, pver, ntop_turb, nbot_turb, &
+         ml2, ri, s2, kvf)
+
+    kvq(:ncol,:) = kvf(:ncol,:)
+    kvm(:ncol,:) = kvf(:ncol,:)
+    kvh(:ncol,:) = kvf(:ncol,:)
+    cgh(:ncol,:) = 0._r8
+    cgs(:ncol,:) = 0._r8
+    return
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/hb_diff.F90:337]: removed (also removed from subroutine compute_hb_diff on which this subroutine is based)

File: src/physics/cam/vertical_diffusion.F90 [hunk 7]
```diff
@@ -276,7 +276,8 @@ subroutine vertical_diffusion_init(pbuf2d)
   use trb_mtn_stress_cam,only : trb_mtn_stress_init
   use beljaars_drag_cam, only : beljaars_drag_init
   use upper_bc,          only : ubc_init
-  use phys_control,      only : waccmx_is, fv_am_correction
+  use phys_control,      only : waccmx_is, fv_am_correction, cam_physpkg_is
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/vertical_diffusion.F90:279]: correct. removed.

File: src/physics/cam/vertical_diffusion.F90 [hunk 8]
```diff
@@ -401,6 +402,19 @@ subroutine vertical_diffusion_init(pbuf2d)
      call addfld('HB_ri',      (/ 'lev' /),  'A', 'no',  'Richardson Number (HB Scheme), I' )
   case ( 'CLUBB_SGS' )
      do_pbl_diags = .true.
+       call init_hb_diff(gravit, cpair, ntop_eddy, nbot_eddy, pref_mid, &
```
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/vertical_diffusion.F90:405]: fixed

File: doc/ChangeLog [hunk 9]
```diff
@@ -1,4 +1,130 @@
...
+
+Purpose of changes (include the issue number and title text for each relevant GitHub issue):
+  - To address stability issues with non-FV dynamical cores we would like to turn on
+	Holtslag-Boville PBL scheme where CLUBB is not active. The issue for this PR is #846
+	and it will also address issue #772
+
+Describe any changes made to build system: NA
+
+Describe any changes made to the namelist:
+  - Introduced namelist variable clubb_do_hb_above. Default False unless using cam6 or cam_dev then
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply doc/ChangeLog:17]: Yes.  Corrected the comment.  We will add cam6 when waccmx is working with this scheme.

File: src/physics/cam/vertical_diffusion.F90 [hunk 10]
```diff
@@ -401,6 +402,19 @@ subroutine vertical_diffusion_init(pbuf2d)
...
+            karman, eddy_scheme)
+     !
+     ! run HB scheme where CLUBB is not active when running cam6 or cam_dev
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: Yep. Corrected the comment.

File: src/physics/cam/hb_diff.F90 (hunk 1 above)
Comment (jtruesdal) [reply src/physics/cam/hb_diff.F90]: Removed it here and in the call to compute_hb_free_atm_diff in vertical_diffusion.F90

File: src/physics/cam/vertical_diffusion.F90 (hunk 2 above)
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: @PeterHjortLauritzen Jesse's catch here was actually a bug I introduced when getting the mods ready for the PR. Since it will affect the tests and could be the reason for the cam6 waccm failure I am rerunning the regression tests.  If everything passes we will be able to include CAM6 as part of this PR and be done with it. Thanks again for your careful review Jesse!

Comment (PeterHjortLauritzen) [reply src/physics/cam/vertical_diffusion.F90]: My re-creation of the failing regression test (FX2000; CAM_CONFIG_OPTS: -phys cam6 -waccmx -ionosphere wxie -chem waccm_ma_mam5) is still failing with this code change ...

**Comment by jtruesdal** [comment]
I modified the description to note that this PR currently applies to cam_dev and the issues noted will be kept open until a future PR addresses a couple cam6 regression errors.  The issues will be fully resolved and closed in that future PR.

File: src/physics/cam/hb_diff.F90 (hunk 5 above)
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/physics/cam/hb_diff.F90:311]: It doesn't look like this change was actually committed/pushed?

File: src/physics/cam/hb_diff.F90 (hunk 6 above)
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/physics/cam/hb_diff.F90:336]: It doesn't look like this change was actually committed/pushed?

**Comment by PeterHjortLauritzen** [comment]
> I think some changes were either not committed or not pushed. I tried to mark which changes were still "missing", but if it is unclear which changes those are just let me know. Thanks!

Sorry had a several day delay in pushing changes ...

File: src/physics/cam/hb_diff.F90 (hunk 5 above)
[the remark this answers is not in the document]
Comment (PeterHjortLauritzen) [reply src/physics/cam/hb_diff.F90]: Got very distracted and did not push ...

File: bld/namelist_files/namelist_definition.xml [hunk 11]
```diff
@@ -4296,6 +4296,13 @@ Real: number of plumes in mass flux ensemble
 Default: 10
 </entry>
 
+<entry id="clubb_do_hb_above" type="logical" category="pbl"
+       group="clubb_params_nl" valid_values="" >
+Logical: If True activate Holtslag and Boville PBL scheme where CLUBB is not active
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply bld/namelist_files/namelist_definition.xml]: Replaced PBL with "vertical diffusion"

File: src/physics/cam/hb_diff.F90 (hunk 3 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/hb_diff.F90]: removed lchnk in called and calling routines.

File: src/physics/cam/hb_diff.F90 (hunk 4 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/hb_diff.F90]: Looks to be OK now

File: src/physics/cam/hb_diff.F90 (hunk 5 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/hb_diff.F90]: Fixed.

File: src/physics/cam/hb_diff.F90 (hunk 6 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/hb_diff.F90]: Looks like its OK now

File: src/physics/cam/vertical_diffusion.F90 (hunk 8 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: Looks to be fixed now.

**Review by nusbaume — APPROVED** [review]
Everything looks good to me now, thanks!

File: bld/namelist_files/namelist_definition.xml [hunk 12]
```diff
@@ -4296,6 +4296,13 @@ Real: number of plumes in mass flux ensemble
 Default: 10
 </entry>
 
+<entry id="clubb_do_hb_above" type="logical" category="pbl"
```
Comment (cacraigucar) [inline bld/namelist_files/namelist_definition.xml:4299]: I propose changing the name of this to be `do_hb_above_clubb`.   There are several reasons I believe this is advantageous:

1. It reads more like what it is doing (initially I saw this flag indicating clubb doing somthing in regards to hb)
2. This variable is really controlling hb and not clubb
3. All other `clubb_` namelists are controlling clubb behaviour

File: src/physics/cam/clubb_intr.F90 [hunk 13]
```diff
@@ -805,8 +811,9 @@ subroutine clubb_readnl(nlfile)
          clubb_skw_max_mag, &
          clubb_tridiag_solve_method, &
          clubb_up2_sfc_coef, &
-         clubb_wpxp_L_thresh
-                               
+         clubb_wpxp_L_thresh, &
+         clubb_do_hb_above
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:815]: I believe on my argument above, that this is actually controlling hb behaviour and not clubb.  If that is indeed the case, then I propose this namelist should be in the hb_diff module (and a namelist reader will need to be added to that module).

**Review by cacraigucar — CHANGES_REQUESTED** [review]
Need to use a keyword in the description to automatically close the issues.  `closes #XXX` is an example.

Submitting these comments early as they may take a bit to implement.  I plan on doing a more complete review, so more comments may be forthcoming (I also want to get feedback on whether my understanding is correct or not).

**Review by cacraigucar — CHANGES_REQUESTED** [review]
Next round of change requests

File: src/dynamics/se/dycore/global_norms_mod.F90 [hunk 14]
```diff
@@ -681,7 +681,9 @@ subroutine print_cfl(elem,hybrid,nets,nete,dtnu,ptop,pmid,&
     do k=1,nlev
       ! Vertical profile from FV dycore (see Lauritzen et al. 2012 DOI:10.1177/1094342011410088)
       scale1        = 0.5_r8*(1.0_r8+tanh(2.0_r8*log(pmid(sponge_del4_lev)/pmid(k))))
-      nu_div_lev(k) = (1.0_r8-scale1)*nu_div+scale1*nu_div_max
+      if (sponge_del4_nu_div_fac.ne.1.0_r8) then
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/dynamics/se/dycore/global_norms_mod.F90:684]: Fixed both instances.

File: src/physics/cam/vertical_diffusion.F90 [hunk 15]
```diff
@@ -979,42 +995,67 @@ subroutine vertical_diffusion_tend( &
...
-
-     ! Not defined since PBL is not actually running here.
-     cgh = 0._r8
-     cgs = 0._r8
-
+    !
+    ! run HB scheme where CLUBB is not active when running cam_dev
+    !
+    if (clubb_do_hb_above) then
+      call compute_hb_free_atm_diff( lchnk     , ncol          , &
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90:1015]: Jesse noted that lchnk was not used in compute_hb_diff and hb_free_atm_diff and I removed them but apparently missed this parameter in the calling routine.  It's fixed now.

File: src/physics/cam/clubb_intr.F90 (hunk 13 above)
Comment (jtruesdal) [reply src/physics/cam/clubb_intr.F90:815]: Sounds good to me. if @PeterHjortLauritzen agrees I'll make the changes.

File: src/physics/cam/vertical_diffusion.F90 [hunk 16]
```diff
@@ -979,42 +995,67 @@ subroutine vertical_diffusion_tend( &
...
+    ! run HB scheme where CLUBB is not active when running cam_dev
+    !
+    if (clubb_do_hb_above) then
+      call compute_hb_free_atm_diff( ncol          , &
+           th        , state%t  , state%q , state%zm           , &
+           state%pmid, state%u  , state%v , tautotx  , tautoty , &
+           cam_in%shf, cam_in%cflx(:,1), obklen  , ustar       , &
+           kvm       , kvh      , kvq     , cgh      , cgs     , &
+           ri        )
+      clubbtop_idx = pbuf_get_index('clubbtop')
```
Comment (brian-eaton) [inline src/physics/cam/vertical_diffusion.F90:1021]: The call to pbuf_get_index belongs in vertical_diffusion_init (so it's only done once).

File: src/physics/cam/vertical_diffusion.F90 [hunk 17]
```diff
@@ -649,6 +661,7 @@ subroutine vertical_diffusion_tend( &
   ! This is an interface routine for vertical diffusion !
   !---------------------------------------------------- !
   use physics_buffer,     only : physics_buffer_desc, pbuf_get_field, pbuf_set_field
+  use physics_buffer,     only : pbuf_get_index
```
Comment (brian-eaton) [inline src/physics/cam/vertical_diffusion.F90:664]: This should be removed along with the corresponding call below (belongs in init method).

File: src/physics/cam/vertical_diffusion.F90 [hunk 18]
```diff
@@ -839,6 +853,8 @@ subroutine vertical_diffusion_tend( &
   real(r8) :: tauy(pcols)
   real(r8) :: shflux(pcols)
   real(r8) :: cflux(pcols,pcnst)
+  integer  :: clubbtop_idx
```
Comment (brian-eaton) [inline src/physics/cam/vertical_diffusion.F90:856]: This should be private module data (initialized by init method).

File: src/physics/cam/clubb_intr.F90 (hunk 13 above)
Comment (brian-eaton) [reply src/physics/cam/clubb_intr.F90:815]: I would suggest putting this in phys_ctl_nl.  That's a good place for a control variable that's needed in both clubb_intr and vertical_diffusion.  Putting it in vertical_diffusion is also an option since that's where the control layer is for vertical diffusion.  But clubb_intr can't access it directly from vertical diffusion because of circular dependency issues.  Another option is to let vertical_diffusion_register add clubbtop to the pbuf, then have clubb_ini_cam check to see whether the index is in the pbuf.  But I think putting it in phys_ctl_nl is probably the easiest, and most readily understandable.

**Review by brian-eaton — CHANGES_REQUESTED** [review]

File: doc/ChangeLog (hunk 9 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply doc/ChangeLog:17]: As the cam6 fix is now included for using HB above CLUBB I changed the comment to reflect that it can be used for cam_dev and cam6.

File: src/physics/cam/vertical_diffusion.F90 (hunk 10 above)
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: As the cam6 fix is now included for using HB above CLUBB I changed the comment to reflect that it can be used for cam_dev and cam6.

File: bld/namelist_files/namelist_definition.xml (hunk 12 above)
Comment (jtruesdal) [reply bld/namelist_files/namelist_definition.xml]: Changed clubb_do_hb_above to do_hb_above_clubb and moved definition from clubb control section of namelist to "PBL and vertical diffusion" section.

File: src/physics/cam/clubb_intr.F90 (hunk 13 above)
Comment (jtruesdal) [reply src/physics/cam/clubb_intr.F90]: Moved HB control variable to to phys_ctl_nl. Now variable accessed via phy_getopts call like other physics control variables.

File: src/physics/cam/clubb_intr.F90 [hunk 19]
```diff
@@ -467,8 +468,10 @@ subroutine clubb_register_cam( )
     !------------------------------------------------ !
 
     !  Add CLUBB fields to pbuf 
-    use physics_buffer,  only: pbuf_add_field, dtype_r8, dyn_time_lvls
+    use physics_buffer,  only: pbuf_add_field, dtype_r8, dtype_i4, dyn_time_lvls, pbuf_get_index
     use subcol_utils,    only: subcol_get_scheme
+
+    integer :: err_idx, idx
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/clubb_intr.F90]: Removed.

File: src/physics/cam/clubb_intr.F90 [hunk 20]
```diff
@@ -467,8 +468,10 @@ subroutine clubb_register_cam( )
     !------------------------------------------------ !
 
     !  Add CLUBB fields to pbuf 
-    use physics_buffer,  only: pbuf_add_field, dtype_r8, dyn_time_lvls
+    use physics_buffer,  only: pbuf_add_field, dtype_r8, dtype_i4, dyn_time_lvls, pbuf_get_index
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/clubb_intr.F90]: Removed.

File: src/physics/cam/vertical_diffusion.F90 [hunk 21]
```diff
@@ -205,7 +204,7 @@ subroutine vd_register()
   ! Register physics buffer fields and constituents !
   !------------------------------------------------ !
 
-  use physics_buffer,      only : pbuf_add_field, dtype_r8, dtype_i4
+  use physics_buffer,      only : pbuf_add_field, dtype_r8, dtype_i4, pbuf_get_index
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: Removed.

File: src/physics/cam/vertical_diffusion.F90 (hunk 16 above)
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: Moved call to pbuf_get_index as recommended.

File: src/physics/cam/vertical_diffusion.F90 (hunk 17 above)
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: Updated as recommended.

File: src/physics/cam/vertical_diffusion.F90 (hunk 18 above)
Comment (jtruesdal) [reply src/physics/cam/vertical_diffusion.F90]: Moved to private data.

**Comment by jtruesdal** [comment]
@cacraigucar @nusbaume @brian-eaton Just a heads up: there is new code to look at for your rereview in addition to mods related to your comments.  Peter corrected the bug which caused cam6 FV regression failures.  The new mods are in geopotential.F90.  Previously do_hb_above_clubb was only enabled for cam_dev but now that we've corrected the error I am also enabling do_hb_above_clubb for cam6 as well.  Running HB above clubb is now the default for all dycores running cam6 or cam_dev physics.  Jesse, I unresolved 2 comments of yours that referenced incorrect comments that were modified with this latest addition (I added cam6 to the comment along with cam_dev.)

File: src/physics/cam/clubb_intr.F90 (hunk 13 above)
Comment (brian-eaton) [reply src/physics/cam/clubb_intr.F90]: This is OK, but I'd like to point out that more recently we've just been accessing variables from the `phys_control` module by giving them `public, protected` attributes.  It's easier than adding arguments to the accessor methods which were implemented before the `protected` attribute was available.

Comment (jtruesdal) [reply src/physics/cam/clubb_intr.F90]: I didn't notice that we had some public protected in there which is cleaner and easier.  I will update to that method as phys_control is already a mix of the two.  A little less to cleanup in the future.

**Review by nusbaume — APPROVED** [review]
The new changes look good to me!

File: doc/ChangeLog [hunk 22]
```diff
@@ -1,4 +1,144 @@
...
+	- remove duplicate timing call
+
+If there were any failures reported from running test_driver.sh on any test
+platform, and checkin with these failures has been OK'd by the gatekeeper,
+then copy the lines from the td.*.status files for the failed tests to the
+appropriate machine below.  All failed tests must be justified.
+
+cheyenne/intel/aux_cam: all BFB except:
+  ERP_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30 (Overall: FAIL)
+     - pre-existing failure
```
Comment (fvitt) [inline doc/ChangeLog:64]: Is HB active above clubb in this test case?  Shouldn't HB mixing stabilize WACCM-SE?  Does this need a new spunup IC file?

Comment (jtruesdal) [reply doc/ChangeLog:64]: @PeterHjortLauritzen Do you have any insight into this failure? I think it is a crossing of levels failure. The HB mixing will stabilize WACCM-SE but it may not be enough to overcome an out of balance IC file. (If that is the issue)

File: src/dynamics/se/dycore/prim_advance_mod.F90 [hunk 23]
```diff
@@ -1176,51 +1176,57 @@ subroutine compute_and_apply_rhs(np1,nm1,n0,dt2,elem,hvcoord,hybrid,&
...
+            !
+            T1 = lapse_rate*Tref*cpair*rga
+            T0 = Tref-T1
+
+            if (hvcoord%hybm(k)>0) then
+               call gradient_sphere(log(exner(:,:)),deriv,elem(ie)%Dinv,grad_logexner)
+               pgf_term(:,:,1)=pgf_term(:,:,1) + &
+                    cpair*T0*(grad_logexner(:,:,1)-pgf_term(:,:,1)/exner(:,:))
+               pgf_term(:,:,2)=pgf_term(:,:,2) + &
+                    cpair*T0*(grad_logexner(:,:,2)-pgf_term(:,:,2)/exner(:,:))
```
Comment (nusbaume) [inline src/dynamics/se/dycore/prim_advance_mod.F90:1217]: Is this formulation still equivalent to the previous one?  It looks like `grad_exner` variable was still just the gradient of the exner function at this point, but the `pgf_term` variable now includes a `cp_dry(:,:,k)*theta_v(:,:)` term as well.

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks good, but I did have one question that would be great for someone to sanity-check me on.

**Review by cacraigucar — APPROVED** [review]

File: src/dynamics/se/dycore/prim_advance_mod.F90 (hunk 23 above)
Comment (jtruesdal) [reply src/dynamics/se/dycore/prim_advance_mod.F90:1217]: I agree. @PeterHjortLauritzen could you double check the implementation for these lines?

Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/prim_advance_mod.F90]: Thanks @nusbaume ! Indeed a bug - I have verified that answers are bit-for-bit with the code version before the buggy commit.

**Review by nusbaume — APPROVED** [review]

File: src/dynamics/se/dycore/prim_advance_mod.F90 (hunk 23 above)
Comment (nusbaume) [reply src/dynamics/se/dycore/prim_advance_mod.F90]: Thanks @jtruesdal and @PeterHjortLauritzen!  The new code looks good to me.

File: doc/ChangeLog (hunk 22 above)
Comment (PeterHjortLauritzen) [reply doc/ChangeLog:64]: @fvitt Thanks for the comment/reminder: 

Yes HB helps stabilize the initial condition but the existing initial condition uses an older topography. With the new topography (where PHIS=0 over ocean) some spin-up with more damping is necessary (due to the gravity waves excited by the change in topography). Here is a spun-up initial condition:

/glade/p/cgd/amp/pel/inic/FW2000.ne30pg3_ne30pg3_nlev70.i.nc

(I did not know that when running with full chemistry the model does not run when using an FWsc2000 initial conditions - hangs at startup with plenty error messages in the CESM log file; so I took the default IC file and overwrote U,V,T,Q, PS with the spun-up fields from an FWsc2000 IC file I had: ncks -m -A -C -v U,V,T,Q,PS spinup.ic.nc orig.ic.nc)

For the failing test:

SMS_Ln9_Vnuopc.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30

we can now use the default se_nsplit. (no need to increase to 30 anymore).

Need some guidance to make these changes ... or maybe @jtruesdal can do it.

Comment (fvitt) [reply doc/ChangeLog:64]: @PeterHjortLauritzen 
Full TSMLT chemistry can be tricky to spin up if all the chemical constituents are starting from zero concentrations (no chemical tracers in the IC file). The chemical solver may not converge in some places.  Are these the type of error messages you are seeing?
I am not sure what you need guidance on.  It sounds like you have a working IC by using the dynamical fields taken from a working FWsc2000 IC file...

Comment (PeterHjortLauritzen) [reply doc/ChangeLog:64]: Yes exactly those errors ...

I have everything I need ... but I don't think I have permissions to add new IC files etc. I think @jtruesdal can take care of it ...

**Review by PeterHjortLauritzen — APPROVED** [review]

File: doc/ChangeLog (hunk 22 above)
Comment (PeterHjortLauritzen) [reply doc/ChangeLog:64]: ... just realized I did not add the mandatory meta data to IC file and change the file name to incl. creation date!

Modified IC file now:

/glade/p/cgd/amp/pel/inic/FW2000.ne30pg3_ne30pg3_nlev70_c230906.nc

File: bld/namelist_files/namelist_definition.xml [hunk 24]
```diff
@@ -5116,6 +5116,13 @@ Bretherton; 'HBR' for Rasch modified version of 'HB'.
 Default: set by build-namelist
 </entry>
 
+<entry id="do_hb_above_clubb" type="logical" category="pbl"
+       group="phys_ctl_nl" valid_values="" >
+Logical: If True activate Holtslag and Boville vertical diffusion scheme where CLUBB is not active
+         (note that CLUBB top is dynamic in each column)
+Default: none
```
Comment (fvitt) [inline bld/namelist_files/namelist_definition.xml:5123]: Should the default be "FALSE" or "set by build-namelist"?

File: src/dynamics/se/dycore/control_mod.F90 [hunk 25]
```diff
@@ -124,5 +124,7 @@ module control_mod
   real(r8), public :: molecular_diff = -1.0_r8
 
   integer, public  :: vert_remap_uvTq_alg, vert_remap_tracer_alg
-  
+
+
+  integer, public :: pgf_formulation !PGF formulation - see prim_advance_mod.F90
```
Comment (fvitt) [inline src/dynamics/se/dycore/control_mod.F90:129]: Initialize this to -1 here to ensure that it get properly set later
```suggestion
  integer, public :: pgf_formulation = -1 !PGF formulation - see prim_advance_mod.F90
```

File: src/dynamics/se/dycore/prim_advance_mod.F90 [hunk 26]
```diff
@@ -1177,51 +1176,50 @@ subroutine compute_and_apply_rhs(np1,nm1,n0,dt2,elem,hvcoord,hybrid,&
...
-           call gradient_sphere(log(exner(:,:)),deriv,elem(ie)%Dinv,grad_logexner)
-           grad_exner_term(:,:,1)=grad_exner_term(:,:,1) + &
-                cpair*T0*(grad_logexner(:,:,1)-grad_exner(:,:,1)/exner(:,:))
-           grad_exner_term(:,:,2)=grad_exner_term(:,:,2) + &
-                cpair*T0*(grad_logexner(:,:,2)-grad_exner(:,:,2)/exner(:,:))
-         end if
-
-
+           pgf_term(:,:,1)  = density_inv(:,:)*grad_p_full(:,:,1,k)
+           pgf_term(:,:,2)  = density_inv(:,:)*grad_p_full(:,:,2,k)
```
Comment (fvitt) [inline src/dynamics/se/dycore/prim_advance_mod.F90:1216]: Is this block for pgf_formulation==2? Should check for pgf_formulation==2.  Error out if pgf_formulation is not 1 or 2.

File: src/physics/cam/vertical_diffusion.F90 [hunk 27]
```diff
@@ -599,6 +616,9 @@ subroutine vertical_diffusion_init(pbuf2d)
      kvh_idx = pbuf_get_index('kvh')
   end if
 
+  ! pbuf field denoting top of clubb
+  clubbtop_idx = pbuf_get_index('clubbtop')
```
Comment (fvitt) [inline src/physics/cam/vertical_diffusion.F90:620]: Is the `clubbtop` pbuf field always available?
```suggestion
  if (do_hb_above_clubb) then
     ! pbuf field denoting top of clubb
     clubbtop_idx = pbuf_get_index('clubbtop')
  end if
```

**Review by fvitt — CHANGES_REQUESTED** [review]
A few suggestions

File: doc/ChangeLog (hunk 22 above)
Comment (jtruesdal) [reply doc/ChangeLog:64]: I will check over the new IC file and load it onto our local systems.  I'll submit it to the data repository once the PR is approved.

File: bld/namelist_files/namelist_definition.xml (hunk 24 above)
Comment (PeterHjortLauritzen) [reply bld/namelist_files/namelist_definition.xml]: Default in namelist_defaults_cam.xml is false. Please check if I modified the code correctly ... thanks

File: src/dynamics/se/dycore/prim_advance_mod.F90 (hunk 26 above)
Comment (PeterHjortLauritzen) [reply src/dynamics/se/dycore/prim_advance_mod.F90:1216]: Done!

File: src/physics/cam/vertical_diffusion.F90 (hunk 27 above)
Comment (PeterHjortLauritzen) [reply src/physics/cam/vertical_diffusion.F90:620]: I think it is always available when using CLUBB

Comment (brian-eaton) [reply src/physics/cam/vertical_diffusion.F90:620]: `clubb` is only on by default for `cam6/cam_dev`.  So I think the original code will fail for pre-cam6 configurations.  Francis's suggested change is one approach.  Another would be to use the optional `errcode` argument to `pbuf_get_index` so that if it's not available the function will just return -1 rather than `call endrun`.

File: bld/namelist_files/namelist_definition.xml (hunk 24 above)
Comment (brian-eaton) [reply bld/namelist_files/namelist_definition.xml]: It is done correctly, but the default depends on the physics package.  So the documentation in `namelist_definition.xml` should read:
`Default: Set by build-namelist.` instead of `Default: none`

Comment (PeterHjortLauritzen) [reply bld/namelist_files/namelist_definition.xml]: Thanks. Changed to "Set by build-namelist."

File: doc/ChangeLog (hunk 22 above)
Comment (jtruesdal) [reply doc/ChangeLog:64]: SMS and ERP WACCM tests now passing using the new IC and default se_nsplit

**Review by fvitt — APPROVED** [review]
