### PR TITLE
cam6_4_116: Mods for RRTMGP blending layer

### LINKED ISSUE #1382: Further refine the blending layer for the upper stratosphere
### What is the feature/what would you like to discuss?

Will be implementing a namelist for a lower boundary limit for the blending layer in addition to the upper limit which was previously committed

### Is there anyone in particular you want to be part of this conversation?

@JulioTBacmeister @peverwhee 

### Will this change (regression test) answers?

I Don't Know

### Will you be implementing this enhancement yourself?

No

### PR DESCRIPTION
**Pull request by peverwhee**
Adds namelist fields for additional control over radheat merge region; adds logic for "tricking" RRTMGP vertical layers.

Closes #1382

### CODE REVIEW

File: .gitmodules [hunk 1]
```diff
@@ -28,8 +28,8 @@
 
 [submodule "atmos_phys"]
 	path = src/atmos_phys
-	url = https://github.com/ESCOMP/atmospheric_physics
-        fxtag = atmos_phys0_16_002
+	url = https://github.com/peverwhee/atmospheric_physics
+	fxtag = 5e8d7fff667b473ff9ab89892e3c5fa1df0b310b
```
Comment (cacraigucar) [inline .gitmodules]: A reminder to me, that the external needs to be updated before I move forward with regression testing

File: src/physics/cam/radheat.F90 [hunk 2]
```diff
@@ -275,8 +298,14 @@ subroutine radheat_tend(state, pbuf,  ptend, qrl, qrs, fsns, &
     lchnk = state%lchnk
     call physics_ptend_init(ptend, state%psetcols, 'radheat', ls=.true.)
  
-! Shortwave heating is RRTMG solar heating only
-    qrs_mrg(:,:) = qrs(:,:)
+   ! Shortwave heating is RRTMG solar heating only
+   ! ++ jtb test setting M/LT SW to scaled cosine
+   ! solar zenith angle
```
Comment (cacraigucar) [inline src/physics/cam/radheat.F90]: Assume this comment can be removed?

File: src/physics/cam/radheat.F90 [hunk 3]
```diff
@@ -351,6 +391,65 @@ subroutine merge_qrl (ncol, hcam, hmlt, hmrg)
...
+
+    ! Assign values from popt
+    c0 = 32.45612064_r8
+    c1 = -0.50124861_r8
+    a1 = 19.11626479_r8
+    z1 = 30.41572125_r8
+    s1 = 20.90525292_r8
+    a2 = 13.50543681_r8
+    z2 = 87.95888464_r8
+    s2 =  9.94346974_r8
```
Comment (cacraigucar) [inline src/physics/cam/radheat.F90:436]: Can a comment be added to further explain these numbers?

File: src/physics/cam/radheat.F90 [hunk 4]
```diff
@@ -351,6 +391,65 @@ subroutine merge_qrl (ncol, hcam, hmlt, hmrg)
...
+    implicit none
+    real(r8), intent(in) :: z
+    real(r8) :: x             ! heating in K/day
+
+    ! ---- Best-fit parameters ----
+    real(r8), parameter :: c0_1 = -11.839696742958163_r8	
+    real(r8), parameter :: c1_1 =   0.23077408652259085_r8	
+    real(r8), parameter :: a1_1 =   3.741649559788312_r8	
+    real(r8), parameter :: z1_1 =  36.50366034343402_r8	
+    real(r8), parameter :: s1_1 =   8.696300405188122_r8
```
Comment (cacraigucar) [inline src/physics/cam/radheat.F90]: More variables which it would be nice to better document.  i.e. are they from a paper (if so, include DOI)

File: src/physics/cam/radheat.F90 [hunk 5]
```diff
@@ -351,6 +391,65 @@ subroutine merge_qrl (ncol, hcam, hmlt, hmrg)
...
+!-----------------------------------------------------------------------
+  pure elemental function qrs_mlt_profile_a(z) result(x)
+    !---------------------------------------------------------------
+    ! Returns profile of SW heating (K/day) based on curve
+    ! fitting to equatorial mean profile of QRS_TOT in:
+    !
+    !        SCWACCM_forcing_zm_L70_1849-2015_CMIP6ensAvg_c181011.nc
+    !----------------------------------------------------------------
+    implicit none
+    real(r8), intent(in) :: z
```
Comment (cacraigucar) [inline src/physics/cam/radheat.F90]: Please comment what z is

File: src/physics/cam/radheat.F90 [hunk 6]
```diff
@@ -351,6 +391,65 @@ subroutine merge_qrl (ncol, hcam, hmlt, hmrg)
...
+    real(r8), parameter :: c1_1 =   0.23077408652259085_r8	
+    real(r8), parameter :: a1_1 =   3.741649559788312_r8	
+    real(r8), parameter :: z1_1 =  36.50366034343402_r8	
+    real(r8), parameter :: s1_1 =   8.696300405188122_r8	
+
+    if (z < 40._r8 ) then
+       x = 0._r8	
+    else
+       x = c0_1 + c1_1*z + a1_1*sin( (z - z1_1)/s1_1 )
+    end if
```
Comment (cacraigucar) [inline src/physics/cam/radheat.F90:477]: It would be good to comment this if block

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: src/physics/cam/radheat.F90 (hunk 2 above)
Comment (JulioTBacmeister) [reply src/physics/cam/radheat.F90]: Remove "Shortwave heating is RRTMG solar heating only"
Keep "Setting idealized M/LT SW to scaled cosine solar zenith angle

File: src/physics/cam/radheat.F90 (hunk 5 above)
Comment (JulioTBacmeister) [reply src/physics/cam/radheat.F90]: z is a reference height profile

File: src/physics/cam/radheat.F90 (hunk 6 above)
Comment (JulioTBacmeister) [reply src/physics/cam/radheat.F90:477]: Set heating rate profile to zero below 40km. Above 40 km use functional form.

File: src/physics/cam/radheat.F90 (hunk 3 above)
Comment (JulioTBacmeister) [reply src/physics/cam/radheat.F90:436]: Values from are from fitting to mean equatorial  WACCM QRS_TOT in 

SCWACCM_forcing_zm_L70_1849-2015_CMIP6ensAvg_c181011.nc

using function 'curve_fit' in scipy.optimize:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html

applied to the functional form:
c0 + c1*z + a1 * tanh( (z - z1)/s1 ) + a2 * tanh( (z - z2)/s2 )

z is in the range 0 to 100km

File: src/physics/cam/radheat.F90 (hunk 4 above)
Comment (JulioTBacmeister) [reply src/physics/cam/radheat.F90]: Values from are from fitting to mean equatorial WACCM QRS_TOT in

SCWACCM_forcing_zm_L70_1849-2015_CMIP6ensAvg_c181011.nc

using function 'curve_fit' in scipy.optimize:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html

applied to the functional form:
c0_1 + c1_1*z + a1_1*sin( (z - z1_1)/s1_1 )

z is in the range 40 to 100km

**Review by cacraigucar — APPROVED** [review]
