### PR TITLE
part of cam6_4_162: Fix issue with aerosol optics diagnostics

### LINKED ISSUE #1497: Issues with prescribed volcanic aerosol optics diagnostics
### Issue Type

Other (please describe below)

### Issue Description

Some of the aerosol optics, such as AODVIS, do not work correctly for prescribed volcanic aerosols.

### Will this change answers?

No

### Will you be implementing this yourself?

Yes

### PR DESCRIPTION
**Pull request by fvitt**
Fixes issues with prescribed volcanic (and bulk) aerosol optics diagnostics.

Closes #1497

### CODE REVIEW

**Comment by jimmielin** [comment]
Thanks @fvitt, I am working on getting BAM diagnostics to work in CAM-SIMA and the changes in this PR helped me. I am happy to review and approve this when it's out of draft.

File: src/physics/cam/aerosol_optics_cam.F90 [hunk 1]
```diff
@@ -1080,24 +1080,25 @@ subroutine update_diags( is_coarse_dust )
...
-            absbc(icol)  = (absbc(icol) +  absh2o*hygrobc(icol)/sumhygro)/sumabs
-
-            scatsslt(icol) = (scatsslt(icol) + scath2o*hygrosslt(icol)/sumhygro)/sumscat
-            abssslt(icol)  = (abssslt(icol) + absh2o*hygrosslt(icol)/sumhygro)/sumabs
+               scatbc(icol)= (scatbc(icol) + scath2o*hygrobc(icol)/sumhygro)/sumscat
+               absbc(icol)  = (absbc(icol) +  absh2o*hygrobc(icol)/sumhygro)/sumabs
 
+               scatsslt(icol) = (scatsslt(icol) + scath2o*hygrosslt(icol)/sumhygro)/sumscat
+               abssslt(icol)  = (abssslt(icol) + absh2o*hygrosslt(icol)/sumhygro)/sumabs
+            endif
```
Comment (jimmielin) [inline src/physics/cam/aerosol_optics_cam.F90]: This is a nitpick but suggestion to keep this consistent with other parts of this file
```suggestion
            end if
```

**Review by jimmielin — APPROVED** [review]
Thanks @fvitt, approving based on my experience that these changes work to get the right diagnostics in CAM-SIMA. I have one super minor comment only.
