### PR TITLE
cam6_3_144: New PUMAS external with machine learning support

### LINKED ISSUE #801: Bring in Machine Learning warm rain capability
### What is the feature/what would you like to discuss?

This is the CAM side of https://github.com/ESCOMP/PUMAS/issues/50

### Is there anyone in particular you want to be part of this conversation?

@andrewgettelman @Katetc @djgagne

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by Katetc**
Preliminary PR with the tag for PUMAS now including early support for a machine learning kernel.

Fixes #801

### CODE REVIEW

File: src/physics/cam_dev/stochastic_emulated_cam.F90 [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+
+  call mpi_bcast(stochastic_emulated_filename_input_scale, cl, mpi_character, mstrid, mpicom, ierr)
+  if (ierr /= 0) call endrun(sub//": FATAL: mpi_bcast: stochastic_emulated_filename_input_scale")
+
+  call mpi_bcast(stochastic_emulated_filename_output_scale, cl, mpi_character, mstrid, mpicom, ierr)
+  if (ierr /= 0) call endrun(sub//": FATAL: mpi_bcast: stochastic_emulated_filename_output_scale")
+
+!CACNOTE
+  write(0,*) ' Inside stochastic_emulated_readnl, stochastic_emulated_filename_quantile=',&
+               stochastic_emulated_filename_quantile
```
Comment (cacraigucar) [inline src/physics/cam_dev/stochastic_emulated_cam.F90:79]: This was a note to myself that this write statement needed to be dealt with.  Either iulog needs to be used or the write needs to be removed.

File: src/physics/cam_dev/stochastic_tau_cam.F90 [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+     close(unitn)
+     call freeunit(unitn)
+  end if
+
+  ! Broadcast namelist variables
+  call mpi_bcast(pumas_stochastic_tau_kernel_filename, cl, mpi_character, mstrid, mpicom, ierr)
+  if (ierr /= 0) call endrun(sub//": FATAL: mpi_bcast: pumas_stochastic_tau_kernel_filename")
+
+!CACNOTE
+  write(0,*) ' Inside stochastic_tau_readnl, pumas_stochastic_tau_kernel_filename=',pumas_stochastic_tau_kernel_filename
```
Comment (cacraigucar) [inline src/physics/cam_dev/stochastic_tau_cam.F90:61]: This was a note to myself that this write statement needed to be dealt with.  Either iulog needs to be used or the write needs to be removed.

File: src/physics/cam_dev/stochastic_tau_cam.F90 [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+implicit none
+private
+save
+
+! Subroutines
+public :: stochastic_tau_init_cam, stochastic_tau_readnl
+
+!Module variables
+
+integer, parameter, public  :: ncd = 35
```
Comment (cacraigucar) [inline src/physics/cam_dev/stochastic_tau_cam.F90:22]: Should this be namelist option, or does ML always use 35?  If it becomes a namelist then it should be renamed soemthing like "pumas_ml_ncd".   If it becomes a namelist, then the same change needs to be made in stochastic_emulated_cam.F90

File: src/physics/cam_dev/stochastic_emulated_cam.F90 [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+integer, parameter, public  :: ncd = 35
+integer, parameter, public  :: ncdp = ncd + 1
+
+character(len=cl) :: stochastic_emulated_filename_quantile = " "
+character(len=cl) :: stochastic_emulated_filename_input_scale = " "
+character(len=cl) :: stochastic_emulated_filename_output_scale = " "
+
+real(r8), public :: mmean(ncd), diammean(ncd)       ! kg & m at bin mid-points
+real(r8), public :: medge(ncdp), diamedge(ncdp)     ! kg & m at bin edges 
+integer, private  :: cutoff_id                       ! cutoff between cloud water and rain drop, D = 40 microns
```
Comment (cacraigucar) [inline src/physics/cam_dev/stochastic_emulated_cam.F90:33]: I believe these can all be removed - they don't appear to be used anywhere in this module

File: src/physics/cam_dev/stochastic_emulated_cam.F90 [hunk 5]
```diff
@@ -0,0 +1,141 @@
...
+! From Morrison (Lebo, originally TAU bin code)
+! Gettelman and Chen 2018
+!the subroutines take in air density, air temperature, and the bin mass boundaries, and 
+!output the mass and number mixing ratio tendencies in each bin directly.
+!this is then wrapped for CAM. 
+
+use shr_kind_mod,      only: r8=>shr_kind_r8
+use shr_kind_mod,      only: cl=>shr_kind_cl
+use cam_history,       only: addfld
+use micro_pumas_utils, only: pi, rhow, qsmall
```
Comment (cacraigucar) [inline src/physics/cam_dev/stochastic_emulated_cam.F90:11]: These are not used and can be removed

File: src/physics/cam_dev/stochastic_tau_cam.F90 [hunk 6]
```diff
@@ -0,0 +1,118 @@
+module stochastic_tau_cam
+! From Morrison (Lebo, originally TAU bin code)
+! Gettelman and Chen 2018
+!the subroutines take in air density, air temperature, and the bin mass boundaries, and 
+!output the mass and number mixing ratio tendencies in each bin directly.
+!this is then wrapped for CAM. 
+
+use shr_kind_mod,      only: r8=>shr_kind_r8, cl=>shr_kind_cl
+use cam_history,       only: addfld
+use micro_pumas_utils, only: pi, rhow, qsmall
```
Comment (cacraigucar) [inline src/physics/cam_dev/stochastic_tau_cam.F90:10]: These are not used and can be removed

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: cime_config/testdefs/testlist_cam.xml [hunk 7]
```diff
@@ -1411,14 +1413,16 @@
...
     </machines>
     <options>
       <option name="wallclock">01:00:00</option>
     </options>
   </test>
-  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s_pumas_sb2001" supported="false">
+  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="ERP_D_Ln9_Vnuopc" testmods="cam/outfrq9s_pumas_sb2001" supported="false">
     <machines>
       <machine name="cheyenne" compiler="intel" category="aux_pumas"/>
+      <machine name="derecho"  compiler="intel" category="aux_pumas"/>
```
[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/testdefs/testlist_cam.xml:1499]: Can I use test_driver.sh to run the aux_pumas suite? I don't know how to do that... I'm just using the create_test command. And, when using the command, I need to specify that it's a derecho test.

File: cime_config/testdefs/testlist_cam.xml [hunk 8]
```diff
@@ -1466,15 +1476,46 @@
...
       <machine name="cheyenne" compiler="intel" category="aux_cam"/>
+      <machine name="cheyenne" compiler="intel" category="aux_pumas"/>
+      <machine name="derecho"  compiler="intel" category="aux_pumas"/>
       <machine name="cheyenne" compiler="intel" category="prealpha"/>
     </machines>
     <options>
       <option name="wallclock">01:00:00</option>
     </options>
   </test>
+  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s_pumas_tau" supported="false">
```
[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/testdefs/testlist_cam.xml:1487]: I agree with this in the long run, but right now, the ML code is still early development. It's likely there will be updates and changes, and it is a VERY experimental option that is not available in any out-of-the-box sense. I don't think these tests _currently_ belong in aux_cam or pre_alpha. Perhaps the next PUMAS PR.

File: cime_config/testdefs/testlist_cam.xml (hunk 7 above)
[the remark this answers is not in the document]
Comment (peverwhee) [reply cime_config/testdefs/testlist_cam.xml:1499]: @Katetc you can run test_driver.sh with the "--cesm aux_pumas" argument.

As @cacraigucar mentioned, the test_driver script is currently looking for "cheyenne" for derecho tests, so just running 

> ./test_driver.sh --cesm aux_pumas

should do the trick and the duplicate "derecho" test in testlist_cam can be removed.

[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/testdefs/testlist_cam.xml:1499]: Awesome, thanks! I'll remove the duplicate tests now. I'm wondering if I can use test_driver on the aux_glc testlist for cism wrapper too... I'll have to give this a try. :)

File: src/physics/cam_dev/stochastic_tau_cam.F90 (hunk 3 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90:22]: Because of the fact that this is used as a dimension in arrays (and not just a limit or adjustable scaling factor), I'm hesitant to add it as a namelist parameter right at this moment. I can add an issue in PUMAS to ask if this should be namelist parameter in the future, and to thoroughly test what the impact of that might be at that time.

Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90:22]: https://github.com/ESCOMP/PUMAS/issues/62

File: src/physics/cam_dev/stochastic_emulated_cam.F90 (hunk 1 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_emulated_cam.F90:79]: Added the iulog and Adjusted the message just a bit.

File: src/physics/cam_dev/stochastic_tau_cam.F90 (hunk 2 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90:61]: Added the iulog and adjusted the message a bit.

File: src/physics/cam_dev/stochastic_emulated_cam.F90 (hunk 4 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_emulated_cam.F90:33]: I agree, removed

File: src/physics/cam_dev/stochastic_emulated_cam.F90 (hunk 5 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_emulated_cam.F90:11]: "r8" is not used, so I removed it. "cl" and "addfld" are both used, so not removed. "pi", "rhow", and "qsmall" not used, so removed.

File: src/physics/cam_dev/stochastic_tau_cam.F90 (hunk 6 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90:10]: Removed "r8" and "micro_pumas_utils" use statements. Left "cl" and "addfld" as they are used.

File: bld/configure [hunk 9]
```diff
@@ -854,10 +858,10 @@ if (defined $opts{'carma'}) {
 }
 
 if ($carma_pkg =~ m/cirrus/i) {
-    unless ($microphys_pkg =~ /^mg/) {
+    unless ($microphys_pkg =~ /^mg|pumas/) {
```
Comment (peverwhee) [inline bld/configure:861]: based on lines 842-845, is checking for "pumas" necessary?

Comment (peverwhee) [reply bld/configure:861]: (same question for all the "|pumas" checks in this file)

**Review by peverwhee — APPROVED** [review]
Thanks for addressing all of @cacraigucar 's comments! I just have one small question in configure.

File: bld/configure (hunk 9 above)
Comment (Katetc) [reply bld/configure]: I gave adding pumas a go and it just didn't work. I'll remove these guys too. :)

Comment (sjsprecious) [reply bld/configure]: maybe you can try `$microphys_pkg =~ /^(mg|pumas)/` instead (an answer from ChatGPT)?

Comment (Katetc) [reply bld/configure]: Oh, this particular code worked. But, overall, when I tried to make "microphys=pumas" work in CAM physics, there were too many hard coded places where "mg" or something similar lurked and I couldn't find them all before I ran out of time and good will. I got tripped up with CLDLIQ not showing up in the pbuf for some reason...anyway. Cheryl (and others) don't want code hanging around that isn't ultimately used, as this isn't currently used, and I understand that.

**Comment by Katetc** [comment]
Hi all, I also wanted to add a note that, currently, the "Emulated" option in the ML is not working. It was for a while with Cheryl's work and then some updates from the group broke it. The ML group are working on another update now that should fix it going forward. As I mentioned in a comment above, the code modification here are still early stages, and issues won't impact any other compset or configuration in CAM. I don't know if we will have the final changes before we get to the CAM tag, so there may be another PUMAS update in the next few weeks.

File: src/physics/cam_dev/stochastic_emulated_cam.F90 [hunk 10]
```diff
@@ -0,0 +1,134 @@
...
+                               stochastic_emulated_filename_output_scale
+
+  if (masterproc) then
+     unitn = getunit()
+     open( unitn, file=trim(nlfile), status='old' )
+     call find_group_name(unitn, 'stochastic_emulated_nl', status=ierr)
+     if (ierr == 0) then
+        read(unitn, stochastic_emulated_nl, iostat=ierr)
+        if (ierr /= 0) then
+           call endrun(sub // ':: ERROR reading namelist')
```
Comment (nusbaume) [inline src/physics/cam_dev/stochastic_emulated_cam.F90:54]: I might include the `iostat` value in the error message as well:

```suggestion
           call endrun(sub // ':: ERROR reading namelist, iostat = ' // int2str(ierr))
```
where `int2str` comes from `string_utils`.

File: src/physics/cam_dev/stochastic_emulated_cam.F90 [hunk 11]
```diff
@@ -0,0 +1,134 @@
...
+    character(len=cl),intent(out) :: stochastic_emulated_filename_quantile_out
+    character(len=cl),intent(out) :: stochastic_emulated_filename_input_scale_out
+    character(len=cl),intent(out) :: stochastic_emulated_filename_output_scale_out
+
+    call add_hist_coord('bins_ncd', ncd, 'bins for TAU microphysics')
+
+    call addfld('amk_c',(/'trop_cld_lev','bins_ncd    '/),'A','kg','cloud liquid mass from bins')
+    call addfld('ank_c',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
+    call addfld('amk_r',(/'trop_cld_lev','bins_ncd    '/),'A','kg','cloud liquid mass from bins')
+    call addfld('ank_r',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
```
Comment (nusbaume) [inline src/physics/cam_dev/stochastic_emulated_cam.F90:91]: Should these be `rain` instead of `cloud liquid`?

File: src/physics/cam_dev/stochastic_emulated_cam.F90 [hunk 12]
```diff
@@ -0,0 +1,134 @@
...
+    call addfld('nctend_TAU',(/'trop_cld_lev'/),'A','1/kg/s','nc tendency due to TAU bin code')
+    call addfld('qrtend_TAU',(/'trop_cld_lev'/),'A','kg/kg/s','qr tendency due to TAU bin code') 
+    call addfld('nrtend_TAU',(/'trop_cld_lev'/),'A','1/kg/s','nr tendency due to TAU bin code')
+    call addfld('qctend_TAU_diag',(/'trop_cld_lev'/),'A','kg/kg/s','qc tendency due to TAU bin code')
+    call addfld('nctend_TAU_diag',(/'trop_cld_lev'/),'A','1/kg/s','nc tendency due to TAU bin code')
+    call addfld('qrtend_TAU_diag',(/'trop_cld_lev'/),'A','kg/kg/s','qr tendency due to TAU bin code')
+    call addfld('nrtend_TAU_diag',(/'trop_cld_lev'/),'A','1/kg/s','nr tendency due to TAU bin code')
+
+    call addfld('gmnnn_lmnnn_TAU',(/'trop_cld_lev'/),'A','1','sum of mass gain and loss from bin code')
+    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency of ML fixer is activated')
```
Comment (nusbaume) [inline src/physics/cam_dev/stochastic_emulated_cam.F90:121]: minor grammar issue:

```suggestion
    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency that ML fixer is activated')
```

File: src/physics/cam_dev/stochastic_tau_cam.F90 [hunk 13]
```diff
@@ -0,0 +1,116 @@
...
+  namelist /pumas_stochastic_tau_nl/ pumas_stochastic_tau_kernel_filename
+
+  if (masterproc) then
+     unitn = getunit()
+     open( unitn, file=trim(nlfile), status='old' )
+     call find_group_name(unitn, 'pumas_stochastic_tau_nl', status=ierr)
+     if (ierr == 0) then
+        read(unitn, pumas_stochastic_tau_nl, iostat=ierr)
+        if (ierr /= 0) then
+           call endrun(sub // ':: ERROR reading namelist')
```
Comment (nusbaume) [inline src/physics/cam_dev/stochastic_tau_cam.F90:48]: I might include the `iostat` value in the error message as well:

```suggestion
           call endrun(sub // ':: ERROR reading namelist, iostat = ' // int2str(ierr))
```
where `int2str` comes from `string_utils`.

File: src/physics/cam_dev/stochastic_tau_cam.F90 [hunk 14]
```diff
@@ -0,0 +1,116 @@
...
+
+    call pumas_stochastic_kernel_init(pumas_stochastic_tau_kernel_filename)
+
+    call add_hist_coord('bins_ncd', ncd, 'bins for TAU microphysics')
+
+    !Note: lev needs to be trop_cld_lev for proc_rates....
+    call addfld('amk_c',(/'trop_cld_lev','bins_ncd    '/),'A','kg','cloud liquid mass from bins')
+    call addfld('ank_c',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
+    call addfld('amk_r',(/'trop_cld_lev','bins_ncd    '/),'A','kg','cloud liquid mass from bins')
+    call addfld('ank_r',(/'trop_cld_lev','bins_ncd    '/),'A','1/kg','cloud liquid number concentration from bins')
```
Comment (nusbaume) [inline src/physics/cam_dev/stochastic_tau_cam.F90:77]: Should these be `rain` instead of `cloud liquid`?

File: src/physics/cam_dev/stochastic_tau_cam.F90 [hunk 15]
```diff
@@ -0,0 +1,116 @@
...
+    call addfld('nctend_TAU',(/'trop_cld_lev'/),'A','1/kg/s','nc tendency due to TAU bin code')
+    call addfld('qrtend_TAU',(/'trop_cld_lev'/),'A','kg/kg/s','qr tendency due to TAU bin code') 
+    call addfld('nrtend_TAU',(/'trop_cld_lev'/),'A','1/kg/s','nr tendency due to TAU bin code')
+    call addfld('qctend_TAU_diag',(/'trop_cld_lev'/),'A','kg/kg/s','qc tendency due to TAU bin code')
+    call addfld('nctend_TAU_diag',(/'trop_cld_lev'/),'A','1/kg/s','nc tendency due to TAU bin code')
+    call addfld('qrtend_TAU_diag',(/'trop_cld_lev'/),'A','kg/kg/s','qr tendency due to TAU bin code')
+    call addfld('nrtend_TAU_diag',(/'trop_cld_lev'/),'A','1/kg/s','nr tendency due to TAU bin code')
+
+    call addfld('gmnnn_lmnnn_TAU',(/'trop_cld_lev'/),'A','1','sum of mass gain and loss from bin code')
+    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency of ML fixer is activated')
```
Comment (nusbaume) [inline src/physics/cam_dev/stochastic_tau_cam.F90:107]: Grammar change:

```suggestion
    call addfld('ML_fixer',(/'trop_cld_lev'/),'A','1','frequency that ML fixer is activated')
```

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks good!  Just have some minor change requests.

File: cime_config/SystemTests/mgp.py [hunk 16]
```diff
@@ -0,0 +1,47 @@
...
+This is just like an ERC test and it's meant for CAM only 
+as it only does a single build.
+ 
+(1) Do an initial run with microphys setup as MG3 (suffix MG3)
+(2) Do an initial run with microphys setup as PUMAS (suffix PUMAS)
+"""
+
+import sys
+from CIME.XML.standard_module_setup import *
+from CIME.SystemTests.restart_tests import SystemTestsCompareTwo
```
[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/SystemTests/mgp.py:15]: Because I was using a CAM restart test for guidance and didn't know that you could do that. I have updated the test now, thanks!

File: bld/namelist_files/namelist_definition.xml [hunk 17]
```diff
@@ -2748,13 +2754,43 @@ Default: 1
...
+</entry>
+
+<entry id="stochastic_emulated_filename_output_scale" type="char*256" input_pathname="abs" category="microphys"
+       group="stochastic_emulated_nl" >
+Neural net output scaling values file for warm_rain machine learning
+</entry>
+
+<entry id="pumas_stochastic_tau_kernel_filename" type="char*256" input_pathname="abs" category="microphys"
+       group="pumas_stochastic_tau_nl" >
+Coefficients for the stochastic collection kernel used by the TAU stochastice collection code, invoked in PUMAS with micro_pumas_warm_rain = 'tau'
```
[the remark this answers is not in the document]
Comment (Katetc) [reply bld/namelist_files/namelist_definition.xml]: Fixed

File: cime_config/SystemTests/mgp.py [hunk 18]
```diff
@@ -0,0 +1,47 @@
...
+logger = logging.getLogger(__name__)
+
+class MGP(SystemTestsCompareTwo):
+
+    def __init__(self, case,
+        separate_builds=True,
+        run_one_suffix="mg3",
+        run_two_suffix="pumas",
+        run_one_description="initial",
+        run_two_description="restart",
```
[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/SystemTests/mgp.py]: When I first made this test, I tried this but changing this text broke it somehow (I forget exactly why). When I changed to pulling the test import from Restart to CompareTwo, this seems to be working now! So, I was able to follow your suggestion. Yey!

File: cime_config/testdefs/testlist_cam.xml [hunk 19]
```diff
@@ -1386,6 +1386,15 @@
     </options>
   </test>
 
+  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="MGP_D_Ln9" testmods="cam/outfrq3s">
```
[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/testdefs/testlist_cam.xml:1389]: Added

File: cime_config/testdefs/testlist_cam.xml [hunk 20]
```diff
@@ -1467,15 +1476,41 @@
...
     <machines>
       <machine name="cheyenne" compiler="intel" category="aux_cam"/>
+      <machine name="cheyenne" compiler="intel" category="aux_pumas"/>
       <machine name="cheyenne" compiler="intel" category="prealpha"/>
     </machines>
     <options>
       <option name="wallclock">01:00:00</option>
     </options>
   </test>
+  <test compset="F2000dev" grid="ne30pg3_ne30pg3_mg17" name="SMS_D_Ln9_Vnuopc" testmods="cam/outfrq9s_pumas_tau" supported="false">
```
[the remark this answers is not in the document]
Comment (Katetc) [reply cime_config/testdefs/testlist_cam.xml:1487]: Added

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 21]
```diff
@@ -1013,6 +1045,19 @@ subroutine micro_pumas_cam_init(pbuf2d)
...
+   call addfld ('nctend_KK2000',     (/ 'trop_cld_lev' /), 'A', '#/kg/s',  'cloud number mass tendency due to autoconversion  & accretion from KK2000')
+   call addfld ('qrtend_KK2000',     (/ 'trop_cld_lev' /), 'A', 'kg/kg/s',  'rain mass tendency due to autoconversion  & accretion from KK2000')
+   call addfld ('nrtend_KK2000',     (/ 'trop_cld_lev' /), 'A', '#/kg/s',  'rain number tendency due to autoconversion  & accretion from KK2000')
+   call addfld ('qctend_SB2001',     (/ 'trop_cld_lev' /), 'A', 'kg/kg/s',  'cloud liquid mass tendency due to autoconversion  & accretion from SB2001')
+   call addfld ('nctend_SB2001',     (/ 'trop_cld_lev' /), 'A', '#/kg/s',  'cloud liquid number tendency due to autoconversion  & accretion from SB2001')
+   call addfld ('qrtend_SB2001',     (/ 'trop_cld_lev' /), 'A', 'kg/kg/s',  'rain mass tendency due to autoconversion  & accretion from SB2001')
+   call addfld ('nrtend_SB2001',     (/ 'trop_cld_lev' /), 'A', '#/kg/s',  'rain number tendency due to autoconversion  & accretion from SB2001')
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90]: Added if tests for these.

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 22]
```diff
@@ -3192,6 +3249,55 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+      call outfld('qctend_SB2001',  proc_rates%qctend_SB2001,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+      call outfld('nctend_SB2001',  proc_rates%nctend_SB2001,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+      call outfld('qrtend_SB2001',  proc_rates%qrtend_SB2001,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+      call outfld('nrtend_SB2001',  proc_rates%nrtend_SB2001,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+   end if
+
+   call outfld('qctend_KK2000',  proc_rates%qctend_KK2000,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+   call outfld('nctend_KK2000',  proc_rates%nctend_KK2000,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+   call outfld('qrtend_KK2000',  proc_rates%qrtend_KK2000,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
+   call outfld('nrtend_KK2000',  proc_rates%nrtend_KK2000,  ncol, lchnk, avg_subcol_field=use_subcol_microp)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90]: Added if tests for these also.

File: src/physics/cam_dev/stochastic_emulated_cam.F90 (hunk 10 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_emulated_cam.F90]: Added this

File: src/physics/cam_dev/stochastic_emulated_cam.F90 (hunk 11 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_emulated_cam.F90]: Yep. Fixed!

File: src/physics/cam_dev/stochastic_emulated_cam.F90 (hunk 12 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_emulated_cam.F90]: Fixed it.

File: src/physics/cam_dev/stochastic_tau_cam.F90 (hunk 13 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90]: Added

File: src/physics/cam_dev/stochastic_tau_cam.F90 (hunk 14 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90]: Yep, fixed it!

File: src/physics/cam_dev/stochastic_tau_cam.F90 (hunk 15 above)
Comment (Katetc) [reply src/physics/cam_dev/stochastic_tau_cam.F90]: Fixed

**Review by cacraigucar — APPROVED** [review]
Resolved all @nusbaume conversations.  Giving my final approval as well.

File: bld/namelist_files/namelist_defaults_cam.xml [hunk 23]
```diff
@@ -2254,7 +2254,7 @@
 <micro_mg_vtrmi_factor                  >  1.D0    </micro_mg_vtrmi_factor>
 
 <micro_mg_vtrms_factor                  >  1.D0    </micro_mg_vtrms_factor>
-<micro_mg_vtrms_factor phys="cam_dev"   >  0.5D0    </micro_mg_vtrms_factor>
+<!--micro_mg_vtrms_factor phys="cam_dev"   >  0.5D0    </micro_mg_vtrms_factor-->
```
Comment (cacraigucar) [inline bld/namelist_files/namelist_defaults_cam.xml:2257]: My previous comment did not appear in this PR, so I am repeating it.  I am wondering why you commented this out instead of removing it completely?  If it will return in an upcoming PR, I am okay with leaving it, but if not, I would suggest it be removed in your next PR.

Comment (Katetc) [reply bld/namelist_files/namelist_defaults_cam.xml:2257]: It was for testing quickly last week. I'll remove it before the merge.
