### PR TITLE
cam6_4_160: TUV-x photolysis

### LINKED ISSUE #757: Introduce in-line photolysis rate calculations from TUV-x
### What is the feature/what would you like to discuss?

This enhancement would use [TUV-x](https://github.com/NCAR/tuv-x) to calculate photolysis rates.

Science motivation: CESM currently uses a look-up table for photolysis rates that was pre-calculated for different ozone and cloud conditions. Aerosol changes have not been considered in the look-up tables. However, it has been shown that photolysis rates can be strongly changed by increases in aerosols in both the stratosphere (for example after volcanic eruptions) or in the troposphere with strong pollution events. TUV-x is an inline model that calculates photolysis rates and takes into account both changes from ozone and aerosols (not clouds currently). The inclusion of this model is expected to significantly improve the representation of photolysis rates in the model, with implications for, e.g.,  OH and ozone in polluted regions, and is also important for geoengineering studies that use stratospheric aerosols.

### Is there anyone in particular you want to be part of this conversation?

@dkinnison @stacywalters @tilmes @fvitt @lizziel

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by fvitt**
This provides the option to use the TUV-x library to compute photo-chemical rates in-line as an alternative to the traditional table look up method.

Closes #757

### CODE REVIEW

File: src/chemistry/mozart/chemistry.F90 [hunk 1]
```diff
@@ -1345,11 +1357,13 @@ subroutine chem_final()
     use mee_ionization, only: mee_ion_final
     use rate_diags, only: rate_diags_final
     use species_sums_diags, only: species_sums_final
+    use mo_tuvx, only: tuvx_finalize
     use short_lived_species, only: short_lived_species_final
 
     call mee_ion_final()
     call rate_diags_final()
     call species_sums_final()
+    call tuvx_finalize()
```
Comment (jimmielin) [inline src/chemistry/mozart/chemistry.F90]: Could maybe wrap this within `if (tuvx_active)` to be consistent with the other calls

File: src/chemistry/mozart/mo_gas_phase_chemdr.F90 [hunk 2]
```diff
@@ -827,12 +830,22 @@ subroutine gas_phase_chemdr(state, lchnk, ncol, imozart, q, &
...
-    !	... lookup the photolysis rates from table
-    !-----------------------------------------------------------------
-    call table_photo( reaction_rates, pmid, pdel, tfld, zmid, zint, &
-                      col_dens, zen_angle, asdir, cwat, cldfr, &
-                      esfact, vmr, invariants, ncol, lchnk, pbuf )
+    if (tuvx_active) then
+      !-----------------------------------------------------------------
+      !	... get calculated photolysis rates from TUV-x
+      !-----------------------------------------------------------------
+      call tuvx_get_photo_rates( state, pbuf, ncol, lchnk, zmid, zint, &
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_gas_phase_chemdr.F90]: It looks like the only place `tuvx_get_photo_rates` uses `state` is to get ` state%ncol` in line ~679, but `ncol` is already passed in here. Maybe `state` does not have to be passed in to `call tuvx_get_photo_rates`

File: src/chemistry/mozart/mo_gas_phase_chemdr.F90 [hunk 3]
```diff
@@ -258,16 +258,17 @@ end subroutine gas_phase_chemdr_inti
...
                               cldw, troplev, troplevchem, &
                               ncldwtr, ufld, vfld,  &
                               delt, ps, &
                               fsds, ts, asdir, ocnfrac, icefrac, &
                               precc, precl, snowhland, ghg_chem, latmapback, &
-                              drydepflx, wetdepflx, cflx, fire_sflx, fire_ztop, nhx_nitrogen_flx, noy_nitrogen_flx, &
-                              use_hemco, qtend, pbuf)
+                              drydepflx, wetdepflx, cflx, fire_sflx, fire_ztop, &
+                              nhx_nitrogen_flx, noy_nitrogen_flx, &
+                              use_hemco, qtend, pbuf, state)
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_gas_phase_chemdr.F90]: These changes appear to be unnecessary as `state` was already previously passed in as the first argument, and was moved to the last one for some reason.

File: src/chemistry/mozart/mo_gas_phase_chemdr.F90 [hunk 4]
```diff
@@ -311,6 +313,7 @@ subroutine gas_phase_chemdr(state, lchnk, ncol, imozart, q, &
     use mo_chm_diags,      only : chm_diags, het_diags
     use perf_mod,          only : t_startf, t_stopf
     use gas_wetdep_opts,   only : gas_wetdep_method
+    use physics_types,     only : physics_state
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_gas_phase_chemdr.F90]: This line is a duplicate of line 318 and does not need to be added again

File: src/chemistry/mozart/chemistry.F90 [hunk 5]
```diff
@@ -1261,14 +1273,14 @@ subroutine chem_timestep_tend( state, ptend, cam_in, cam_out, dt, pbuf,  fh2o)
...
-    call gas_phase_chemdr(state,lchnk, ncol, imozart, state%q, &
+    call gas_phase_chemdr(lchnk, ncol, imozart, state%q, &
                           state%phis, state%zm, state%zi, calday, &
                           state%t, state%pmid, state%pdel, state%pint, state%rpdel, state%rpdeldry, &
                           cldw, tropLev, tropLevChem, ncldwtr, state%u, state%v, chem_dt, state%ps, &
                           fsds, cam_in%ts, cam_in%asdir, cam_in%ocnfrac, cam_in%icefrac, &
                           cam_out%precc, cam_out%precl, cam_in%snowhland, ghg_chem, state%latmapback, &
                           drydepflx, wetdepflx, cam_in%cflx, cam_in%fireflx, cam_in%fireztop, &
-                          nhx_nitrogen_flx, noy_nitrogen_flx, use_hemco, ptend%q, pbuf )
+                          nhx_nitrogen_flx, noy_nitrogen_flx, use_hemco, ptend%q, pbuf, state )
```
Comment (jimmielin) [inline src/chemistry/mozart/chemistry.F90]: These changes appear to be unnecessary as `state` was already previously passed in as the first argument, and was moved to the last one for some reason.

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 6]
```diff
@@ -0,0 +1,2069 @@
...
+      real(r8),        intent(in)    :: optical_depth_cld(pcols, pver+1, this%n_wavelength_bins_) ! aerosol optical depth [unitless]
+      real(r8),        intent(in)    :: single_scattering_albedo_cld(pcols, pver+1, this%n_wavelength_bins_) ! single scattering albedo [unitless]
+      real(r8),        intent(in)    :: asymmetry_factor_cld(pcols, pver+1, this%n_wavelength_bins_) ! asymmetry factor [unitless]
+
+      integer  :: i_level
+      real(r8) :: tmp(pver)
+      real(r8) :: tau(pver+1, this%n_wavelength_bins_)
+      real(r8) :: edges(pver+2), densities(pver+1)
+      real(r8) :: exo_val
+      real(r8), parameter :: rgrav = 1.0_r8 / 9.80616_r8 ! reciprocal of acceleration by gravity (s/m)
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: Can `physconst`'s `rga` be used here instead?

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 7]
```diff
@@ -0,0 +1,2069 @@
...
+      ! air profile
+      ! ===========
+      edges(1) = fixed_species_conc(i_col,pver,indexm)
+      edges(2:pver+1) = fixed_species_conc(i_col,pver:1:-1,indexm)
+      edges(pver+2) = fixed_species_conc(i_col,1,indexm) ! use upper mid-point value for top edge
+      densities(1:pver+1) = this%height_delta_(1:pver+1) * km2cm * &
+         sqrt(edges(1:pver+1)) * sqrt(edges(2:pver+2))
+      call this%profiles_( PROFILE_INDEX_AIR )%update( &
+         edge_values = edges, layer_densities = densities, &
+         scale_height = 8.01_r8 ) ! scale height in [km]
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: The `8.01_r8` could be made as a SCALE_HEIGHT_AIR `parameter`.
It would be useful to have a reference of why this value was chosen, too.

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 8]
```diff
@@ -0,0 +1,2069 @@
...
+         edges(pver+2) = species_vmr(i_col,1,index_O2) * &
+            fixed_species_conc(i_col,1,indexm)
+      else
+         edges(:) = 0.0_r8
+      end if
+      densities(1:pver+1) = this%height_delta_(1:pver+1) * km2cm * &
+         sqrt(edges(1:pver+1)) * sqrt(edges(2:pver+2))
+      call this%profiles_( PROFILE_INDEX_O2 )%update( &
+         edge_values = edges, layer_densities = densities, &
+         scale_height = 7.0_r8 )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: The `7.0_r8` could be made as a `parameter :: SCALE_HEIGHT_O2`
It seems consistent with what is used in `mo_photo.F90` right now which says
```
                !....... Assuming a scale height of 7km for ozone
                !....... Assuming a scale height of 7km for O2
```
maybe that comment could be added here too.

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 9]
```diff
@@ -0,0 +1,2069 @@
...
+            + 0.5_r8 * exo_column_conc(i_col,1,1)
+         call this%profiles_( PROFILE_INDEX_O3 )%update( &
+            edge_values = edges, layer_densities = densities, &
+            exo_density = exo_column_conc(i_col,0,1) )
+      else
+         densities(1:pver+1) = this%height_delta_(1:pver+1) * km2cm * &
+            ( edges(1:pver+1) + edges(2:pver+2) ) * 0.5_r8
+         call this%profiles_( PROFILE_INDEX_O3 )%update( &
+            edge_values = edges, layer_densities = densities, &
+            scale_height = 7.0_r8 )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: Same note as the O2 scale height maybe set this to `parameter :: SCALE_HEIGHT_OZONE` and/or at least add a comment that a scale height is assumed here the same as `mo_photo.F90`

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 10]
```diff
@@ -0,0 +1,2069 @@
...
+   end subroutine get_aerosol_optical_properties
+
+!================================================================================================
+
+   !-----------------------------------------------------------------------
+   ! Reorders elements of an optical property array for conversion
+   !   from wavenumber to wavelength grid and out-of-order final
+   !   element in CAM wavenumber grid
+   !-----------------------------------------------------------------------
+   subroutine reorder_optics_array( optics_array )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: This subroutine appears unused (and not public) and could be removed

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 11]
```diff
@@ -0,0 +1,2069 @@
...
+         o2_dens(:) = species_vmr(:pver,index_O2) * fixed_species_conc(:pver,indexm)
+      end if
+
+      ! =======================
+      ! special height argument
+      ! =======================
+      height_arg(:) = height_mid(:)
+
+      call jeuv( pver, solar_zenith_angle, o_dens, o2_dens, n2_dens, height_arg, &
+                 euv_rates(pver:1:-1,:) )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: What does `special` mean here?
The altitude argument to `jeuv` appears to just take model height midpoints and is `intent(in)`, this could be just

```suggestion
      call jeuv( pver, solar_zenith_angle, o_dens, o2_dens, n2_dens, height_mid(:pver), &
                 euv_rates(pver:1:-1,:) )
```

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 12]
```diff
@@ -0,0 +1,2069 @@
...
+      end if
+
+      i_label = i_label + 1
+
+      if( do_jno ) then
+         all_labels( i_label ) = "jno"
+         i_label = i_label + 1
+      end if
+
+      call assert( 522515214, i_label == size( all_labels ) + 1 )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: What is the meaning of the `522515214` magic number here?

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 13]
```diff
@@ -0,0 +1,2069 @@
...
+   ! Indices for profile updaters
+   integer, parameter :: NUM_PROFILES = 8               ! number of profiles that CAM will update at runtime
+   integer, parameter :: PROFILE_INDEX_TEMPERATURE  = 1 ! Temperature profile index
+   integer, parameter :: PROFILE_INDEX_ALBEDO       = 2 ! Surface albedo profile index
+   integer, parameter :: PROFILE_INDEX_ET_FLUX      = 3 ! Extraterrestrial flux profile index
+   integer, parameter :: PROFILE_INDEX_AIR          = 4 ! Air density profile index
+   integer, parameter :: PROFILE_INDEX_O3           = 5 ! Ozone profile index
+   integer, parameter :: PROFILE_INDEX_O2           = 6 ! Molecular oxygen profile index
+   integer, parameter :: PROFILE_INDEX_SO2          = 7 ! Sulfur dioxide profile index
+   integer, parameter :: PROFILE_INDEX_NO2          = 8 ! Nitrogen dioxide profile index
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: These appear to be non-public and unused, can I ask if these are intended to be not implemented?

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 14]
```diff
@@ -0,0 +1,2069 @@
...
+
+   ! Indices for radiator updaters
+   integer, parameter :: NUM_RADIATORS = 2          ! number of radiators that CAM will update at runtime
+   integer, parameter :: RADIATOR_INDEX_AEROSOL = 1 ! Aerosol radiator index
+   integer, parameter :: RADIATOR_INDEX_CLOUDS  = 2 ! Cloud radiator index
+
+   ! Definition of the MS93 wavelength grid  TODO add description of this
+   integer,       parameter :: NUM_BINS_MS93 = 4
+   real(kind=r8), parameter :: WAVELENGTH_EDGES_MS93(NUM_BINS_MS93+1) = &
+      (/ 181.6_r8, 183.1_r8, 184.6_r8, 190.2_r8, 192.5_r8 /)
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: Missed `TODO` here about the description here

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 15]
```diff
@@ -0,0 +1,2069 @@
...
+      nwave = wavelength%size()
+
+      ! get TUVx wavelengths at bin centers
+      allocate(wc(nwave))
+      wc(1:nwave) = (wavelength%edge_(1:nwave) + wavelength%edge_(2:nwave+1))*0.5_r8
+
+      deallocate( cam_grids     )
+      deallocate( cam_profiles  )
+      deallocate( cam_radiators )
+      deallocate( wavelength )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: Since `wavelength => cam_grids%get_grid(...)` I would suggest switching the `deallocate` order for safety
```suggestion
      deallocate( wavelength )
      deallocate( cam_grids     )
      deallocate( cam_profiles  )
      deallocate( cam_radiators )
```

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 16]
```diff
@@ -0,0 +1,2069 @@
...
+      deallocate( height )
+      deallocate( wavelength )
+
+      ! ================
+      ! Profile updaters
+      ! ================
+
+      host_profile => profiles%get_profile( "temperature", "K" )
+      this%profiles_( PROFILE_INDEX_TEMPERATURE ) = this%core_%get_updater( host_profile, found )
+      call assert( 418735162, found )
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: Here and throughout the file, there are many calls to `musica_assert::assert` with seemingly random numbers for unique error codes. It seems to be consistent with what's done elsewhere in MUSICA, but I would request to at least have a comment somewhere that these numbers are just unique error codes and don't have any particular meaning other than being unique, and this is how the MUSICA library handles errors. Thanks!

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 17]
```diff
@@ -0,0 +1,2069 @@
...
+   ! ************************ (exo values) *****************************
+   !                                       ================== i_mid = pver + 1
+   ! ================= i_mid = 1           ------------------ i_int = pver + 1
+   ! ----------------- i_int = 2           ================== i_mid = pver
+   !                                       ------------------ i_int = pver
+   !        ||
+   !        ||                                     ||
+   !                                               ||
+   ! ----------------- i_int = pver
+   ! ================= i_imd = pver        ------------------ i_int = 2
```
Comment (jimmielin) [inline src/chemistry/mozart/mo_tuvx.F90]: typo here:
```suggestion
   ! ================= i_mid = pver        ------------------ i_int = 2
```

**Review by jimmielin — CHANGES_REQUESTED** [review]
Thanks @fvitt - I had some minor suggested changes that are hopefully straightforward.

File: src/chemistry/mozart/chemistry.F90 (hunk 1 above)
Comment (fvitt) [reply src/chemistry/mozart/chemistry.F90]: done

File: src/chemistry/mozart/mo_gas_phase_chemdr.F90 (hunk 2 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_gas_phase_chemdr.F90]: fixed

File: src/chemistry/mozart/mo_gas_phase_chemdr.F90 (hunk 3 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_gas_phase_chemdr.F90]: fixed

File: src/chemistry/mozart/mo_gas_phase_chemdr.F90 (hunk 4 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_gas_phase_chemdr.F90]: The duplicate line has been removed

File: src/chemistry/mozart/chemistry.F90 (hunk 5 above)
Comment (fvitt) [reply src/chemistry/mozart/chemistry.F90]: done

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 6 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: This parameter was not being used, so it was removed.

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 7 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: done

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 8 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: done

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 9 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: done

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 10 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: removed

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 11 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: changed as suggested

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 12 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: added a couple comments

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 13 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: removed

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 14 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: added a brief description

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 15 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: done

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 16 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: added comments

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 17 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: fixed

**Review by jimmielin — APPROVED** [review]

File: cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam [hunk 18]
```diff
@@ -11,3 +11,5 @@ solar_data_type='FIXED'
 solar_data_ymd=20000101
 carma_maxretries = 40
 ubc_specifier = 'T->MSIS', 'Q->2.d-8vmr', 'CH4->2.d-10vmr', 'H->MSIS', 'N->MSIS', 'O->MSIS', 'O2->MSIS', 'H2->TGCM', 'NO->SNOE'
+tuvx_active = .true.
+tuvx_config_path = '$SRCROOT/src/chemistry/pp_waccm_ma_sulfur/tuvx_config.json'
```
Comment (nusbaume) [inline cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam]: Should we use `$COMP_ROOT_DIR_ATM` here instead of `$SRCROOT`?  I am only asking because the other tests using TUV-x appear to use `$COMP_ROOT_DIR_ATM`.

File: cime_config/testdefs/testmods_dirs/cam/outfrq9s_waccm_ma_mam4/user_nl_cam [hunk 19]
```diff
@@ -5,3 +5,6 @@ inithist='ENDOFRUN'
 nlte_use_extco2 = .true.
 fincl2 = 'QRL_TOT','QRLNLTE','QCO2','QO3','QHC2S','QNO','QO3P',
          'QCO2ext','TCO2ext','PCO2ext','CO2_ext','N2_ext','O_ext','O2_ext'
+
+tuvx_active = .true.
+tuvx_config_path = '$COMP_ROOT_DIR_ATM/src/chemistry/pp_waccm_ma_mam5/tuvx_config.json'
```
Comment (nusbaume) [inline cime_config/testdefs/testmods_dirs/cam/outfrq9s_waccm_ma_mam4/user_nl_cam:10]: Just-double checking that the config file under `pp_waccm_ma_mam5` can also be used for a MAM4 test?

File: cime_config/buildlib [hunk 20]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
         logger.info("%s: \n\n output:\n %s \n\n err:\n\n%s\n", cmd, out, err)
         expect(rc == 0, "Command %s failed with rc=%s" % (cmd, rc))
 
+###############################################################################
+def _run_cmd(command, working_dir):
+###############################################################################
+
+    rc, out, err = run_cmd(command, from_dir=working_dir, verbose=True)
+    expect(rc == 0, "Command {} failed with rc={}".format(command, rc))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would add the `out` and `err` info to the `expect` call here as well (and convert it to an f-string):


```suggestion
    expect(rc == 0, f"Command {command} failed with rc={rc} out={out} err={err}")
    
```

File: cime_config/buildlib [hunk 21]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+        args += "-DCOMPILER={} ".format(build.get_value("COMPILER"))
+        args += "-DOS={} ".format(build.get_value("OS"))
+        args += "-DMACH={} ".format(case.get_value("MACH"))
+        args += "-DCMAKE_C_COMPILER_WORKS=1 "
+        args += "-DCMAKE_Fortran_COMPILER_WORKS=1 "
+        args += "-DCMAKE_CXX_COMPILER_WORKS=1 "
+        args += "-DDEBUG={} ".format(build.get_value("DEBUG"))
+        cmd = "cmake {} .".format(args)
+        rc, out, err = run_cmd(cmd, combine_output=True, from_dir=macro_path)
+        expect(rc == 0, "Command {} failed with rc={} out={} err={}".format(cmd, rc, out, err))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would convert these all to f-strings:


```suggestion
        args = "-DCONVERT_TO_MAKE=ON "
        args += f"-DCASEROOT={caseroot} "
        args += f"-DCOMPILER={build.get_value("COMPILER")} "
        args += f"-DOS={build.get_value("OS")} "
        args +=f "-DMACH={case.get_value("MACH")} "
        args += "-DCMAKE_C_COMPILER_WORKS=1 "
        args += "-DCMAKE_Fortran_COMPILER_WORKS=1 "
        args += "-DCMAKE_CXX_COMPILER_WORKS=1 "
        args += f"-DDEBUG={build.get_value("DEBUG")} "
        cmd = f"cmake {args} ."
        rc, out, err = run_cmd(cmd, combine_output=True, from_dir=macro_path)
        expect(rc == 0, f"Command {cmd} failed with rc={rc} out={out} err={err}")
```

File: cime_config/buildlib [hunk 22]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+        if build.get_value("MPILIB") == "mpi-serial":
+            cmake_args = "-DCMAKE_Fortran_COMPILER={} ".format(arg_dict["SFC"])
+        else:
+            cmake_args = "-DCMAKE_Fortran_COMPILER={} ".format(arg_dict["MPIFC"])
+            cmake_args += "-DTUVX_ENABLE_MPI:BOOL=TRUE "
+        if case.get_value("DEBUG"):
+            cmake_args += "-DCMAKE_BUILD_TYPE=Debug "
+        else:
+            cmake_args += "-DCMAKE_BUILD_TYPE=Release "
+        cmake_args += "-DCMAKE_VERBOSE_MAKEFILE=ON "
```
Comment (nusbaume) [inline cime_config/buildlib]: It looks like much of this Fortran compiler logic is immediately clobbered below.  Given that I don't think CAM ever really uses the "mpi-serial" library, I might clean this up like so:


```suggestion
        arg_dict = _cmake_default_args(caseroot)
        cmake_args = "-DCMAKE_VERBOSE_MAKEFILE=ON "
        if build.get_value("MPILIB") != "mpi-serial":
            cmake_args += "-DTUVX_ENABLE_MPI:BOOL=TRUE "
        if case.get_value("DEBUG"):
            cmake_args += "-DCMAKE_BUILD_TYPE=Debug "
        else:
            cmake_args += "-DCMAKE_BUILD_TYPE=Release "
```

File: cime_config/buildlib [hunk 23]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+        cmake_args += "-DTUVX_ENABLE_TESTS=OFF "
+        cmake_args += "-DTUVX_ENABLE_COVERAGE=OFF "
+        cmake_args += "-DTUVX_BUILD_CLI=OFF "
+        cmake_args += "-DTUVX_INSTALL_INCLUDE_DIR='{}' ".format(_tuvx_include_dir(libroot))
+        cmake_args += "-DTUVX_INSTALL_MOD_DIR='{}' ".format(_tuvx_include_dir(libroot))
+        cmake_args += srcpath
+
+        _run_cmd("cmake {}".format(cmake_args), bldpath)
+        _run_cmd(case.get_value("GMAKE"), bldpath)
+        _run_cmd("{} install".format(case.get_value("GMAKE")), bldpath)
```
Comment (nusbaume) [inline cime_config/buildlib]: I would convert these all to f-strings:


```suggestion
        if (case.get_value("MACH") == "izumi") :
            cmake_args += f"-DCMAKE_PREFIX_PATH={arg_dict["NETCDF_PATH"]} "
            cmake_args += f"-DCMAKE_IGNORE_PATH={os.environ.get('PYTHONHOME')} "
        if (case.get_value("MACH") == "izumi") and (case.get_value("COMPILER") == "nag") :
            cmake_args += "-DCMAKE_Fortran_FLAGS='-C=all -g ' "
        else :
            cmake_args += f"-DCMAKE_Fortran_FLAGS='{arg_dict["FFLAGS"]}' "

        cmake_args += f"-DCMAKE_INSTALL_PREFIX='{libroot}' "
        cmake_args += "-DTUVX_ENABLE_TESTS=OFF "
        cmake_args += "-DTUVX_ENABLE_COVERAGE=OFF "
        cmake_args += "-DTUVX_BUILD_CLI=OFF "
        cmake_args += f"-DTUVX_INSTALL_INCLUDE_DIR='{_tuvx_include_dir(libroot)}' "
        cmake_args += f"-DTUVX_INSTALL_MOD_DIR='{_tuvx_include_dir(libroot)}' "
        cmake_args += srcpath

        _run_cmd(f"cmake {cmake_args}", bldpath)
        _run_cmd(case.get_value("GMAKE"), bldpath)
        _run_cmd(f"{case.get_value("GMAKE"} install"), bldpath)
```

File: cime_config/buildlib [hunk 24]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+
+        # add TUV-x to include paths
+        incldir = os.environ.get('USER_INCLDIR')
+        if incldir is None:
+            incldir = ''
+        os.environ['USER_INCLDIR'] = incldir + \
+            " -I{} ".format(_tuvx_include_dir(libroot))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would an f-string here:


```suggestion
        os.environ['USER_INCLDIR'] = incldir + \
            f" -I{_tuvx_include_dir(libroot)} "
```

File: cime_config/buildlib [hunk 25]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+
+        # create simlink to library in folder CIME expects libraries to be in
```
Comment (nusbaume) [inline cime_config/buildlib]: Total nit-pick, but I believe it is technically shortened as "symlink":


```suggestion
        # create symlink to library in folder CIME expects libraries to be in
```

File: cime_config/buildlib [hunk 26]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+        os.symlink(_yaml_cpp_lib_path(libroot), dst)
+
+###############################################################################
+def _tuvx_include_dir(libroot):
+###############################################################################
+# Returns the path to the TUV-x include directory
+
+    coreinc = os.path.join(libroot, "include", "")
+    expect(os.path.exists(coreinc), \
+           "TUV-x include directory not found at {}".format(coreinc))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would clean this up slightly:


```suggestion
    coreinc = os.path.join(libroot, "include")
    expect(os.path.exists(coreinc), \
           f"TUV-x include directory not found at {coreinc}"
```

File: cime_config/buildlib [hunk 27]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+###############################################################################
+# Returns the path to the yaml-cpp library
+
+    corelib = os.path.join(libroot, "lib64", "libyaml-cpp.a")
+    if not os.path.exists(corelib):
+        corelib = os.path.join(libroot, "lib64", "libyaml-cppd.a")
+    if not os.path.exists(corelib):
+        corelib = os.path.join(libroot, "lib", "libyaml-cpp.a")
+    expect(os.path.exists(corelib), \
+           "yaml-cpp library not found at {}".format(corelib))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would make this an f-string:


```suggestion
           f"yaml-cpp library not found at {corelib}")
```

File: cime_config/buildlib [hunk 28]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+###############################################################################
+def _tuvx_lib_path(libroot):
+###############################################################################
+# Returns the path to the TUV-x library
+
+    corelib = os.path.join(_tuvx_install_dir(libroot), "lib64", "libtuvx.a")
+    if not os.path.exists(corelib):
+        corelib = os.path.join(_tuvx_install_dir(libroot), "lib", "libtuvx.a")
+    expect(os.path.exists(corelib), \
+           "TUV-x library not found at {}".format(corelib))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would make this an f-string:


```suggestion
           f"TUV-x library not found at {corelib}")
```

File: cime_config/buildlib [hunk 29]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+###############################################################################
+# Returns the path to the TUV-x install directory
+
+    corepaths = glob(os.path.join(libroot, "tuvx*"))
+    expect(len(corepaths)>0, \
+           "TUV-x not found at {}".format(libroot))
+    expect(len(corepaths)<2, \
+           "Multiple TUV-x versions found at {}".format(libroot))
+    expect(os.path.exists(corepaths[0]), \
+           "TUV-x install directory not found at {}".format(corepaths[0]))
```
Comment (nusbaume) [inline cime_config/buildlib]: I would convert these error messages to f-strings:


```suggestion
    expect(len(corepaths)>0, \
           f"TUV-x not found at {libroot}"
    expect(len(corepaths)<2, \
           f"Multiple TUV-x versions found at {libroot}"
    expect(os.path.exists(corepaths[0]), \
           f"TUV-x install directory not found at {corepaths[0]}"
```

File: cime_config/buildlib [hunk 30]
```diff
@@ -157,12 +158,182 @@ def _build_cam(caseroot, libroot, bldroot):
...
+    return corepaths[0]
+
+###############################################################################
+def _tuvx_package_dir(libroot):
```
Comment (nusbaume) [inline cime_config/buildlib]: I don't think this function is actually used anywhere (?).

File: cime_config/buildnml [hunk 31]
```diff
@@ -203,7 +203,7 @@ def buildnml(case, caseroot, compname):
         # -----------------------------------------------------
         # copy geos-chem config files to rundir if using geos-chem chemistry
         # -----------------------------------------------------
-
+
```
Comment (nusbaume) [inline cime_config/buildnml]: Is there a reason for the extra whitespace here?

File: src/chemistry/mozart/chemistry.F90 [hunk 32]
```diff
@@ -320,9 +321,12 @@ subroutine chem_register
     call register_cfc11star()
 
     if ( waccmx_is('ionosphere') ) then
-       call photo_register()
+       if( .not. tuvx_active ) then
+         call photo_register( )
+       end if
        call aurora_register()
     endif
+    call tuvx_register( )
```
Comment (nusbaume) [inline src/chemistry/mozart/chemistry.F90]: Is there a reason to call `tuvx_register()` if `tuvx_active` is `.false.`?  If not then I might update this to be:


```suggestion
    if( tuvx_active ) call tuvx_register( )
```

File: src/chemistry/mozart/mo_jeuv.F90 [hunk 33]
```diff
@@ -80,6 +80,7 @@ subroutine jeuv_init (photon_file, electron_file, indexer)
         character(len=2) :: mstring
         character(len=7) :: jstring
         logical :: do_jeuv
+        logical, save :: is_initialized = .false.
```
Comment (nusbaume) [inline src/chemistry/mozart/mo_jeuv.F90]: Nit-pick, but can we possibly move this up to be a `protected` module-level variable?  I generally wouldn't expect saved variables to exist within a subroutine.

**Review by nusbaume — CHANGES_REQUESTED** [review]
Thanks for bringing this in @fvitt!  I had some cleanup requests in the python code, but otherwise only had a couple other comments.  Hopefully none of my requests will cause any issues, but if you find that they do please let me know!

File: cime_config/testdefs/testmods_dirs/cam/outfrq9s_waccm_ma_mam4/user_nl_cam (hunk 19 above)
Comment (fvitt) [reply cime_config/testdefs/testmods_dirs/cam/outfrq9s_waccm_ma_mam4/user_nl_cam:10]: This work for the mam4 mechanism -- has the same photo-chemical reactions as the mam5 mechanism.

File: cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam (hunk 18 above)
Comment (fvitt) [reply cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam]: Changed.

File: cime_config/buildlib (hunk 20 above)
Comment (fvitt) [reply cime_config/buildlib]: changed as suggested

File: cime_config/buildlib (hunk 21 above)
Comment (fvitt) [reply cime_config/buildlib]: changed as suggested

File: cime_config/buildlib (hunk 22 above)
Comment (fvitt) [reply cime_config/buildlib]: changed as suggested

File: cime_config/buildlib (hunk 23 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 24 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 25 above)
Comment (fvitt) [reply cime_config/buildlib]: fixed

File: cime_config/buildlib (hunk 26 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 27 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 28 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 29 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 30 above)
Comment (fvitt) [reply cime_config/buildlib]: removed

File: cime_config/buildnml (hunk 31 above)
Comment (fvitt) [reply cime_config/buildnml]: removed

File: .gitmodules [hunk 34]
```diff
@@ -205,3 +205,10 @@ url = https://github.com/NCAR/CUPiD.git
 fxtag = v0.4.0
 fxrequired = ToplevelRequired
 fxDONOTUSEurl = https://github.com/NCAR/CUPiD.git
+
+[submodule "tuv-x"]
+path = libraries/tuv-x
+url = https://github.com/NCAR/tuv-x.git
+fxtag = ecf768a2b66
```
Comment (cacraigucar) [inline .gitmodules]: We need a tag for this instance

**Review by cacraigucar — CHANGES_REQUESTED** [review]
I would have expected an aux_cam regression test.  Can you modify an existing test to turn this on (or is there one already)?

File: src/chemistry/mozart/mo_tuvx.F90 [hunk 35]
```diff
@@ -0,0 +1,2042 @@
...
+      ! ==================================================================
+      ! construct a core and a map between TUV-x and CAM photolysis arrays
+      ! on the primary process and pack them onto an MPI buffer
+      ! ==================================================================
+      if( is_main_task ) then
+         call tuvx_config%from_file( config_path%to_char( ) )
+         call tuvx_config%get( "__CAM options", cam_config, my_name )
+         call assert_msg( 973680295, & ! random error number consistent with how MUSICA error handling
+            cam_config%validate( required_keys, optional_keys ), &
+            "Bad configuration for CAM TUV-x options." )
```
Comment (cacraigucar) [inline src/chemistry/mozart/mo_tuvx.F90]: Just curious why this random number approach is being used instead of the `__FILE__`and `__LINE__` which is being used elsewhere in CESM is not being used.  That approach leads the user to the exact spot without needing to do a grep or table lookup.

File: .gitmodules (hunk 34 above)
Comment (fvitt) [reply .gitmodules]: @K20shores, Can you make a new tag?

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 35 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: This style of error reporting was implemented by @mattldawson.  If we are not happy with this style in CAM code, I propose we use `endrun` to abort.  

@cacraigucar Let me know if these asserts need to be replaced.

File: src/chemistry/mozart/mo_jeuv.F90 (hunk 33 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_jeuv.F90]: changed as suggested

File: src/chemistry/mozart/chemistry.F90 (hunk 32 above)
Comment (fvitt) [reply src/chemistry/mozart/chemistry.F90]: done

**Comment by fvitt** [comment]
@cacraigucar 

TUV-x is turned on in this aux_cam test:
```
aux_cam: SMS_D_Ln9.f19_f19_mg17.FWma2000climo.derecho_intel.cam-outfrq9s_waccm_ma_mam4              # WACCM MA MAM4
```
See changes here:
https://github.com/ESCOMP/CAM/pull/1471/changes#diff-d1ec6e7c15fbf6c2148ef4c31be28506c102b8cf6811cb4a9dfc163edde61fd8

File: .gitmodules (hunk 34 above)
Comment (K20shores) [reply .gitmodules]: Created: https://github.com/NCAR/tuv-x/tree/v0.14.1

tag: v0.14.1

File: cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam [hunk 36]
```diff
@@ -12,4 +12,4 @@ solar_data_ymd=20000101
 carma_maxretries = 40
 ubc_specifier = 'T->MSIS', 'Q->2.d-8vmr', 'CH4->2.d-10vmr', 'H->MSIS', 'N->MSIS', 'O->MSIS', 'O2->MSIS', 'H2->TGCM', 'NO->SNOE'
 tuvx_active = .true.
-tuvx_config_path = '$SRCROOT/src/chemistry/pp_waccm_ma_sulfur/tuvx_config.json'
+tuvx_config_path = '$COMPCOMP_ROOT_DIR_ATM/src/chemistry/pp_waccm_ma_sulfur/tuvx_config.json'
```
Comment (nusbaume) [inline cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam]: Typo here (`COMPCOMP` -> `COMP`).

File: cime_config/buildlib [hunk 37]
```diff
@@ -175,17 +175,17 @@ def _cmake_default_args(caseroot):
     with Case(caseroot) as case:
         macro_path = os.path.abspath(os.path.join(caseroot, "cmake_macros", ""))
         args = "-DCONVERT_TO_MAKE=ON "
-        args += "-DCASEROOT={} ".format(caseroot)
-        args += "-DCOMPILER={} ".format(build.get_value("COMPILER"))
-        args += "-DOS={} ".format(build.get_value("OS"))
-        args += "-DMACH={} ".format(case.get_value("MACH"))
+        args += f"-DCASEROOT={caseroot} "
+        args += f"-DCOMPILER={build.get_value('COMPILER')} "
```
Comment (nusbaume) [inline cime_config/buildlib]: Apologies for not catching this in the first review round, but I think you can just use the `case.get_value` method here and below, in which case you can remove the `build = EnvBuild(case_root=caseroot)` line above.

File: cime_config/buildlib
Comment (nusbaume) [inline cime_config/buildlib]: I _think_ you can use `case.get_value` instead of `build.get_value` for all of the uses below, in which case I don't believe you need this line anymore.

**Review by nusbaume — CHANGES_REQUESTED** [review]
Thanks for resolving my concerns @fvitt!  

However, looking over the code again I realized that there might be no need to create a `build` variable in the CMake python functions, as I believe everything can just use `case.get_value()`, so I have a couple remaining change requests related to that (along with a typo fix).  Otherwise everything else looks good!

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 35 above)
Comment (cacraigucar) [reply src/chemistry/mozart/mo_tuvx.F90]: Yes, I would like to request the the asserts be replaced with `endrun` as it gives traceback information without a user needing to do a grep after the job fails to figure out where it stopped.

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: cime_config/buildlib
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/buildlib (hunk 37 above)
Comment (fvitt) [reply cime_config/buildlib]: done

File: cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam (hunk 36 above)
Comment (fvitt) [reply cime_config/testdefs/testmods_dirs/cam/carma_mixed_sulfate/user_nl_cam]: fixed

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 35 above)
Comment (fvitt) [reply src/chemistry/mozart/mo_tuvx.F90]: done

File: .gitmodules (hunk 34 above)
Comment (fvitt) [reply .gitmodules]: done

**Review by nusbaume — APPROVED** [review]
Everything looks great to me now.  Thanks for getting this brought in @fvitt!

**Comment by K20shores** [comment]
> Everything looks great to me now. Thanks for getting this brought in @fvitt!

Must second this. Quite literally could not have happened without you @fvitt. Your efforts are much appreciated

File: src/chemistry/mozart/mo_tuvx.F90 (hunk 35 above)
Comment (cacraigucar) [reply src/chemistry/mozart/mo_tuvx.F90]: Thanks for making these extensive changes.  Hopefully it wasn't to onerous to complete, but I believe the end user experience will benefit from the traceback capabilities of the endrun calls.

**Review by cacraigucar — APPROVED** [review]
