### PR TITLE
cam6_3_066: cleaning up clubb bugs, misc clubb issues

### LINKED ISSUE #336: CLUBB/CAM interface bug fixes
A series of bugs have been identified in clubb_intr.F90. They fall into three main categories:

**Incorrect definitions of variables throughout clubb_intr. The correct equations are as follows:**
- p_ds_zt = pmid/(1+qv*Rv/Rd) <--not currently a variable, needed for thv_ds_zt
- exner_ds_zt = (p_ds_zt/p0)^(Rd/cp) <--not currently a variable, needed for thv_ds_zt
- thv_ds_zt = T/exner_ds_zt
- rho_ds_zt = 1/g dp/dz (1-qv)
- This entire block should be removed as it would no longer be used to define thv_ds_zt:
   `   !  Compute virtual potential temperature, which is needed for CLUBB`  
   `do k=1,pver`
    ` do i=1,ncol`
       `thv(i,k) = state1%t(i,k)*inv_exner_clubb(i,k)*(1._r8+zvir*state1%q(i,k,ixq)&
                  -state1%q(i,k,ixcldliq))`
     `enddo`
   `enddo`
- The definition of thv for use in diagnosing the pbl should include condensate loading
  current: `thv(i,k) = th(i,k)*(1.0_r8+zvir*state1%q(i,k,ixq))`
  should be: `thv(i,k) = th(i,k)*(1.0_r8+zvir*state1%q(i,k,ixq)-state1%q(i,k,ixcldliq))`
-  rho calculated after state updates from clubb should be on interface levels, and use a mass definition.
  current: 
  `rho(:ncol,1:pver) = state1%pmid(:ncol,1:pver)/(rairv(:ncol,1:pver,lchnk)*state1%t(:ncol,1:pver))`
  `rho(:ncol,pverp)  = state1%ps(:ncol)/(rairv(:ncol,pver,lchnk)*state1%t(:ncol,pver))`
  should be: 
  `rho_zt(:ncol,2:pverp) = (1._r8/gravit)*(state1%pdel(:ncol,1:pver)/(state1%zi(:ncol,1:pver)-state1%zi(:ncol,2:pverp))`
  `rho_zt(:ncol,1) = rho_zt(:ncol,2)`
  `rho = zm2zt_api( rho_zt )` <--shorthand for interpolating to interface levels
                      

**Namelist not used for convection area fraction calculation, and are hard coded instead.**
- current: `deepcu(i,k) = max(0.0_r8,min(0.1_r8*log(1.0_r8+500.0_r8*(cmfmc(i,k+1)-cmfmc_sh(i,k+1))),0.6_r8))`
- should be: `deepcu(i,k) = max(0.0_r8,min(dp1*log(1.0_r8+dp2*(cmfmc(i,k+1)-cmfmc2(i,k+1))),0.60_r8))`
- where `dp1` and `dp2` refer to namelist variables `cldfrc_dp1` and `cldfrc_dp2`

**Outfld variables that are incorrectly assigned to the physics grid (i.e., ilev). These vars are on the lev grid.**
- `call addfld ('RCM_CLUBB',        (/ 'ilev' /), 'A', 'g/kg',     'Cloud Water Mixing Ratio')`
- `call addfld ('RCMINLAYER_CLUBB', (/ 'ilev' /), 'A', 'g/kg',     'Cloud Water in Layer')`
- `call addfld ('CLOUDCOVER_CLUBB', (/ 'ilev' /), 'A', 'fraction', 'Cloud Cover')`
- `call addfld ('WM_ZT_CLUBB',      (/ 'ilev' /), 'A', 'm/s',      'Vertical Velocity')`
- `call addfld ('UM_CLUBB',         (/ 'ilev' /), 'A', 'm/s',      'Zonal Wind')`
- `call addfld ('VM_CLUBB',         (/ 'ilev' /), 'A', 'm/s',      'Meridional Wind')`
Note that the reason they are incorrectly assigned to ilev grid is b/c CLUBB variables defined at the mid-point levels still have arrays of size pverp b/c CLUBB includes a ghost point in the subsurface on the mid-point grid. And so the arrays that are fed into outfld need to be indexed 2:pverp.

All the above changes do not noticeably alter the climate (save for the change in the thv calculation for diagnosing the pbl depth, which I have not checked yet). I will add links to amwg diagnostics when I resolve a permissions error for the webext site.

@PeterHjortLauritzen @JulioTBacmeister

### LINKED ISSUE #496: scale sensible heat fluxes in CLUBB by exner function
The sensible heat fluxes ```w'T'_sfc``` should be converted ```w'theta'_sfc``` before supplying them as boundary conditions to the CLUBB solver, in order to be consistent with CLUBB's prognostic variables. The difference is a factor inverse exner at the surface:

      inv_exner_clubb_surf = 1._r8/((state1%pmid(i,pver)/p0_clubb)**(rair/cpair)) !phl Option 2
      wpthlp_sfc = wpthlp_sfc*inv_exner_clubb_surf

where exner is defined using a reference pressure of 1000 hPa (```p0_clubb```). This primarily impacts high elevation, near surface fields. AMWG diagnostics w/ and w/o this fix are [here](https://webext.cgd.ucar.edu/F2000climo/cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_scaleshf_Nx5yrs.arh/atm/cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_scaleshf_Nx5yrs.2_20-cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_Nx5yrs.2_20/).

@PeterHjortLauritzen

### LINKED ISSUE #497: Add diagnostics: CLUBB energy fixer and DQCORE
Make energy leak from CLUBB an outfld. Make water vapor tendency due to dycore, DQCORE, an outfld (modeled after DTCORE).

@PeterHjortLauritzen

### LINKED ISSUE #536: Inline calculation of IVT for AR detection
Inline calculations of IVT,uIVT,vIVT (vertically integrated moisture transport) in cam_diagnostics.F90 has been used by AR researchers (@shieldsca) as SourceMods for some time now ... so I'm opening this issue to put this additional diagnostic on the trunk. @andrewgettelman Christine said you planned on getting this in at some point, but didn't see an issue. Happy to include this in the upcoming CLUBB PR since that will have additional diagnostics in it as well (i.e.,  https://github.com/ESCOMP/CAM/issues/497).

### LINKED ISSUE #582: moving CLUBB pdf closure to after advancing the CLUBB equations #582
In https://github.com/ESCOMP/CAM/pull/545, UWM wanted to move the pdf closure to the post position (i.e., call pdf closure after advancing the prognostic moments). I believe the motivation is because the pdf closure is CAM's saturation adjustment, which is usually the last process to be called because it provides an instantaneous adjustment. We decided against moving the pdf closure in https://github.com/ESCOMP/CAM/pull/545, and I instead have opened this issue to discuss what I perceive as the obstacles needed to be addressed before moving the pdf closure.

The pdf closure provides variables that are used to advance the prognostic equations, and we currently call the pdf closure at the top of CLUBB, so that all routines in CLUBB are able to use to those variables. By moving the pdf closure to the post position, the necessary variables will need to be saved from time-step to time-step, and fed in to CLUBB to be used to advance the CLUBB equations. UWM proposed saving these variables time-step to time-step by expanding their scope in the PBUF to 'global':

```
    call pbuf_add_field('WP2THVP',    'global', dtype_r8, (/pcols,pverp/), wp2thvp_idx)
    call pbuf_add_field('RTPTHVP',    'global', dtype_r8, (/pcols,pverp/), rtpthvp_idx)
    call pbuf_add_field('THLPTHVP',   'global', dtype_r8, (/pcols,pverp/), thlpthvp_idx)
    call pbuf_add_field('CLOUD_FRAC', 'global', dtype_r8, (/pcols,pverp/), cloud_frac_idx)
    call pbuf_add_field('ISS_FRAC',   'global',  dtype_r8, (/pcols,pverp/), ice_supersat_idx)
    call pbuf_add_field('RCM',        'global', dtype_r8, (/pcols,pverp/), rcm_idx)
```

The first three variables are probably fine to keep in the PBUF, but they are incorrect if we turn on advecting the moments via ```clubb_do_adv```. Looking through ```advance_clubb_core``` I don't believe CLOUD_FRAC is used anywhere prior to the post position of the pdf closure (I only see one place where CLOUD_FRAC might be used before the pdf closure, and that's for adjusting the C2 coefficient using cloud_frac (l_C2_cloud_frac), which as far as I can tell is defaulting to false).

RCM is my major concern. It is used in many places in CLUBB before the post pdf closure position (primarily for computing virtual potential temperature or just plain temperature, from RCM). Cloud liquid is supposed to be advected by the dycore, and so using the PBUF to access the cloud field from time-step to time-step is not appropriate. Two possible solutions:

1. Make RCM a proper dycore tracer in state%q
2. Set RCM to CLDLIQ to be fed into CLUBB (this would be for all macmic cycles to be consistent)

The nice thing about (2) is that then thl and rtm are consistent with RCM, since they are defined using CLDLIQ. However, this will introduce a change to the definition of cloud liquid compared to the current code base where we compute the pdf closure at the top of CLUBB. That is because CLUBB lives in an all liquid world, and the cloud liquid created by the pdf closure is always going to be larger than the CLDLIQ field after MG2 has had chance to repartition some of it to CLDICE. Setting RCM to CLDLIQ will always reflect this MG2 re-partition. So by initializing RCM to CLDLIQ we are changing the definition of the cloud used to calculate various things such virtual potential temperature. 

I actually think that the balance of trade-offs points towards using (2). This is because it creates consistency between thl, rtm and RCM throughout a larger portion of the CLUBB code, where it is important to maintain these consistencies because their definitions are used to convert back and forth from moist conserved to non conserved variables (e.g., thl and T). However, once we exit CLUBB we will use the pdf closure cloud to convert from CLUBB's thl / rtm back to CAM's T, q, CLDLIQ. 

This all make me wonder whether an (3) option is possible; initializing RCM to CLDLIQ+CLDICE, rtm=qv+RCM, and thl = thli = f(CLDLIQ,CLDICE), and using the pdf closure cloud liquid to convert back to CAM's variables.

@Katetc
@vlarson
@bstephens82
@JulioTBacmeister

### LINKED ISSUE #604: default clubb_timestep's needlessly small for hi-res
### Issue Type

Code Clean-up

### Issue Description

It appears that as a postdoc, I incorrectly set the ```clubb_timestep``` in namelist_defaults to needlessly small values for the hi-res grids (ne120np4, and the var-res grids). This is incorrect. CLUBB's time-step shouldn't depend on dx, but rather dz. ```clubb_timestep``` should default to 300 s for all grids.

As this is a simple fix, I will add it to my current draft PR https://github.com/ESCOMP/CAM/pull/598

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

### LINKED ISSUE #605: CLDTOP/CLDBOT pbuf variables initialized incorrectly
### What happened?

I'm answering a question about PCLDTOP/PCLDBOT on the forums here:
https://bb.cgd.ucar.edu/cesm/threads/how-are-pcldtop-and-pcldbot-defined.7420/#post-45190

He's saying that there are instances when PCLDBOT < PCLDTOP, indicating cloud bottom is above cloud top. I think I've tracked this down to how we are initializing these variables. tl;dr these variables are set in convect_shallow, to the state%pmid associated with the pbuf variables CLDBOT/CLDTOP. Both in deep convection and shallow convection, the top and bottoms are both initialized backwards:

convect_deep:
    jctop = pver
    jcbot = 1._r8

convect_shallow:
      cnt2        = pver
      cnb2        = 1._r8

It's initializing the cloud bottom to k=1, and cloud top to k=pver. These variables are subsequently used to define CLDTOP/CLDBOT. So if there is no convection, the backwards values are used, which would explain the occurrence of PCLDBOT < PCLDTOP in the simulations.

### What are the steps to reproduce the bug?

run the model

### What CAM tag were you using?

all versions

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by adamrher**
Fixes #336 
Fixes #496 
Fixes #497
Fixes #536 
Fixes #582 
Fixes #604 
Fixes #605

This PR is an continuation of (closed) PR https://github.com/ESCOMP/CAM/pull/352

### CODE REVIEW

**Comment by adamrher** [comment]
@Katetc @JulioTBacmeister @bstephens82 @swrneale I'd say about half of the CLUBB outfld vars are incorrectly assigned to "ilev" when they are technically on the "lev". This is because in clubb, the midpoint grid contains pverp entries, just like the interface grid, because there is a ghost point in the subsurface. 

Does everyone agree with putting these outfld vars on the correct grid? Or leave it as it is?

**Comment by JulioTBacmeister** [comment]
I think the CLUBB output should be on the correct grid.

**Comment by Katetc** [comment]
Does that mean we won't output the ghost point? That's probably fine. I can't remember if it was ever important. Be careful with the array truncation code, that's an easy thing to get weird seg fault errors in.

**Comment by adamrher** [comment]
> Does that mean we won't output the ghost point?

Yes. Which is fine IMO too. The clubb documentation says that after the state is advanced in clubb, it just copies the pver values into pverp (the ghost point). So there's no additional information.

I'll plan on fixing the outfld's then...

**Comment by bstephens82** [comment]
Sounds good to me.

File: src/physics/cam/clubb_intr.F90 [hunk 1]
```diff
@@ -2614,6 +2583,7 @@ subroutine clubb_tend_cam( &
      do i=1,ncol
        inv_exner_clubb(i,k) = 1._r8/((state1%pmid(i,k)/p0_clubb)**(rairv(i,k,lchnk)/cpairv(i,k,lchnk)))
      enddo
+     inv_exner_clubb_surf(i) = 1._r8/((state1%pint(i,pverp)/p0_clubb)**(rair/cpair))
```
Comment (bstephens82) [inline src/physics/cam/clubb_intr.F90:2586]: This statement contains an `i` but is outside of the `i` loop...is that intentional?

File: src/physics/cam/check_energy.F90 [hunk 2]
```diff
@@ -66,6 +66,7 @@ module check_energy
 
   integer  :: teout_idx  = 0       ! teout index in physics buffer
   integer  :: dtcore_idx = 0       ! dtcore index in physics buffer
+  integer  :: dqcore_idx = 0
```
Comment (bstephens82) [inline src/physics/cam/check_energy.F90:69]: Should this be commented?

File: src/physics/cam/physpkg.F90 [hunk 3]
```diff
@@ -88,6 +88,8 @@ module physpkg
   integer ::  dlfzm_idx          = 0     ! detrained convective cloud water mixing ratio.
   integer ::  ducore_idx         = 0     ! ducore index in physics buffer
   integer ::  dvcore_idx         = 0     ! dvcore index in physics buffer
+  integer ::  dtcore_idx         = 0
+  integer ::  dqcore_idx         = 0
```
Comment (bstephens82) [inline src/physics/cam/physpkg.F90:92]: Should these two lines be commented?

File: src/physics/cam_dev/physpkg.F90 [hunk 4]
```diff
@@ -86,6 +86,7 @@ module physpkg
   integer ::  ducore_idx         = 0     ! ducore index in physics buffer
   integer ::  dvcore_idx         = 0     ! dvcore index in physics buffer
   integer ::  dtcore_idx         = 0
+  integer ::  dqcore_idx         = 0
   integer ::  cmfmczm_idx        = 0     ! Zhang-McFarlane convective mass fluxes
```
Comment (bstephens82) [inline src/physics/cam_dev/physpkg.F90:90]: Should this be commented?

**Review by bstephens82 — APPROVED** [review]

File: src/physics/cam/clubb_intr.F90 (hunk 1 above)
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:2586]: good catch! yep this is a mistake; wasn't looking closely at the loop nesting

File: src/physics/cam/check_energy.F90 (hunk 2 above)
Comment (adamrher) [reply src/physics/cam/check_energy.F90:69]: fixed

File: src/physics/cam/physpkg.F90 (hunk 3 above)
Comment (adamrher) [reply src/physics/cam/physpkg.F90:92]: done

**Review by cacraigucar — COMMENTED** [review]
First pass review

File: src/physics/cam/cam_diagnostics.F90 [hunk 5]
```diff
@@ -1344,8 +1350,32 @@ subroutine diag_phys_writeout_moist(state, pbuf, p_surf_t)
...
+       ftem5(:ncol,1) = ftem5(:ncol,1) + ftem5(:ncol,k)
+    end do
+    ! compute ivt
+    ftem(:ncol,1) = sqrt( ftem4(:ncol,1)**2 + ftem5(:ncol,1)**2)
+
+    call outfld ('IVT     ',ftem, pcols   ,lchnk     )
+
+    ! output uq*dp/g
+    ftem(:ncol,1) =  ftem4(:ncol,1)
+    call outfld ('uIVT     ',ftem, pcols   ,lchnk     )
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/cam_diagnostics.F90:1371]: no reason. I removed this redundancy and just put ftem4/5 in the outfld calls directly.

File: src/physics/cam/micro_pumas_cam.F90 [hunk 6]
```diff
@@ -48,11 +48,13 @@ module micro_pumas_cam
...
    micro_pumas_cam_init,            &
    micro_pumas_cam_tend,            &
-   micro_mg_version,             &
+   micro_mg_version,                &
+   micro_mg_num_steps,              &
    massless_droplet_destroyer
 
 integer :: micro_mg_version     = 1      ! Version number for MG.
 integer :: micro_mg_sub_version = 0      ! Second part of version number.
+integer :: micro_mg_num_steps   = 1      ! Number of substepping iterations done by MG (versions 1.5 and later).
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/micro_pumas_cam.F90:57]: thanks! I actually pulled this out of the branch because it relates to outputting the time-steps to the log. But I made a new branch with just the time-step output code, and added your mods to micro_pumas_cam.

File: src/physics/cam/check_energy.F90 [hunk 7]
```diff
@@ -139,11 +140,13 @@ subroutine check_energy_register()
 
     call pbuf_add_field('TEOUT', 'global',dtype_r8 , (/pcols,dyn_time_lvls/),      teout_idx)
     call pbuf_add_field('DTCORE','global',dtype_r8,  (/pcols,pver,dyn_time_lvls/),dtcore_idx)
+    call pbuf_add_field('DQCORE','global',dtype_r8,  (/pcols,pver,dyn_time_lvls/),dqcore_idx)
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/check_energy.F90:143]: done

File: src/physics/cam/check_energy.F90 [hunk 8]
```diff
@@ -199,6 +202,7 @@ subroutine check_energy_init()
     call addfld('TEFIX',  horiz_only,  'A', 'J/m2', 'Total energy after fixer')
     call addfld('EFIX',   horiz_only,  'A', 'W/m2', 'Effective sensible heat flux due to energy fixer')
     call addfld('DTCORE', (/ 'lev' /), 'A', 'K/s' , 'T tendency due to dynamical core')
+    call addfld('DQCORE', (/ 'lev' /), 'A', 'kg/kg/s' , 'Q tendency due to dynamical core')
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/check_energy.F90:205]: changed it to "Water vapor tendency ..."

File: src/physics/cam/clubb_intr.F90 [hunk 9]
```diff
@@ -2953,8 +2933,10 @@ subroutine clubb_tend_cam( &
         wprtp_in(i,k)   = wprtp(i,pverp-k+1)
         wpthlp_in(i,k)  = wpthlp(i,pverp-k+1)
         rtpthlp_in(i,k) = rtpthlp(i,pverp-k+1)
-        rcm_inout(i,k)  = rcm(i,pverp-k+1)
         cloud_frac_inout(i,k) = cloud_frac(i,pverp-k+1)
+        if (k.gt.1) then
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:2937]: done (ive been reminded of this before ... hopefully it will take this time)

File: src/physics/cam/clubb_intr.F90 [hunk 10]
```diff
@@ -4137,13 +4115,15 @@ subroutine clubb_tend_cam( &
     
    do i=1,ncol
       do k=1,pver
-         th(i,k) = state1%t(i,k)*state1%exner(i,k)
-         thv(i,k) = th(i,k)*(1.0_r8+zvir*state1%q(i,k,ixq))
+         !th(i,k) = state1%t(i,k)*state1%exner(i,k)
+         !thv(i,k) = th(i,k)*(1.0_r8+zvir*state1%q(i,k,ixq))
+         ! REMOVE AFTER CODE REVIEW - state%exner is not a proper exner
+         !                            thv should have condensate loading to be consistent with earlier def's
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:4121]: done

**Comment by adamrher** [comment]
@cacraigucar this PR is almost ready for prime time. Three outstanding issues:

1. @Katetc are there are low hanging clubb issues that we should add to this PR?
2. Do I need to merge up to the head? My branch is currently based on cam6_3_060.
3. Currently doing a quick science eval of these changes, which should be completed by tomorrow.

**Comment by cacraigucar** [comment]
> 2. Do I need to merge up to the head? My branch is currently based on cam6_3_060.

Yes, this will need to be merged to the head of cam_development before we run the final regression testing (once the reviews are complete and we are ready to begin the tagging process).  The code is fairly close to the head, so not critical for the review stage, especially since the tags since then have been pretty orthogonal.

**Comment by adamrher** [comment]
@JulioTBacmeister
@swrneale 
@andrewgettelman 
@bstephens82

Impact of this PR is [here](https://webext.cgd.ucar.edu/F2000climo/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs/atm/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8-cam6_3_060_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8/) --8 years, L58, F2000dev. Seems to be a bit more convection in W.Pac, and an increase in ice water path. Nothing alarming.

**Comment by swrneale** [comment]
West Pacific and Indian Monsoon are quite a bit wetter, which makes biases a bit worse. But in the far East Pacific it's slightly better. Mixed bag I guess. Do you have expectations of how stable/unstable the state is it on exit from CLUBB when you change the position of the PDF closure?

**Comment by adamrher** [comment]
wait a second I see something wrong - [PBLH](https://webext.cgd.ucar.edu/F2000climo/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs/atm/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8-cam6_3_060_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.2_8/set5_6/set5_ANN_PBLH_c.png).

I had previously tested the impact of the pdf closure position and not found any appreciably change. Rather it seems like I messed up the PBLH calculation in clubb_intr.

**Comment by swrneale** [comment]
Is it using the Holslag Boville PBLH calculation still? Does the PDF closure come at a difference place relative to this calculation now?

**Comment by adamrher** [comment]
Yes to Holstag Boville. No the pdf closure is not in a different place from the perspective of the PBLH call.

It's got to be one of two things. I changed the definition of theta to use the true exner function (not state%exner), and then in the theta_v calculation I added condensate loading. Doing two simulations with each of these reverted back right now. Note these theta / theta_v calculations are only used by the PBLH calculation.

**Comment by adamrher** [comment]
I fixed this bug I introduced into the PBLH calculation. The problem was that I naively just replaced state%exner with the exner defined in clubb_intr. But state%exner is cryptically named -- it is actually 1/exner. This has tripped up many of us before, and so should probably be fixed.

So this is fixed, and I'm re-running 10 years to evaluate the impact of this PR.

**Comment by adamrher** [comment]
Ten year runs of L58, cam_dev, [showing impact of this PR](https://webext.cgd.ucar.edu/F2000climo/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220625_fixexner2_Nx2yrs/atm/clubb.kitchensink_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220625_fixexner2_Nx2yrs.1_9-cam6_3_060_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_nuopc_3600pes_220623_Nx2yrs.1_9/). @swrneale there are no precip changes in tropical pacific or indian monsoon region anymore. The only changes I see are TS, primarily over land. Interestingly TREFHT has much smaller changes. This resembles what we found when we tested the impact of [scaling sensible heat fluxes in isolation](https://webext.cgd.ucar.edu/F2000climo/cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_scaleshf_Nx5yrs.arh/atm/cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_scaleshf_Nx5yrs.2_20-cam6_2_026.pel_F2000climo_ne30pg3_ne30pg3_mg17_1800pes_210924_ediags_Nx5yrs.2_20/set5_6/set5_ANN_TS_c.png). Note these old expts are L32 runs, whereas these new expts are L58 cam_dev. The largest TS changes are over high elevation regions, the Himalayas and the big ice sheets. This is where we expect the largest changes since dividing by exner is only going to impact regions where PS is very different from P0=1000 hPa.

Recall also that the scaling of the sensible heat fluxes drastically reduces CLUBB's energy leak, so this is a substantial enhancement to the model. See Figure 12 of @PeterHjortLauritzen's very short little GRL paper [here](https://www.cgd.ucar.edu/cms/pel/papers/LetAl2022JAMES.pdf).

File: src/physics/cam/clubb_intr.F90 [hunk 11]
```diff
@@ -2921,6 +2899,9 @@ subroutine clubb_tend_cam( &
     !  Surface fluxes provided by host model
     do i=1,ncol                                                                  
       wpthlp_sfc(i) = cam_in%shf(i)/(cpair*rho_ds_zm(i,1))       ! Sensible heat flux
+      !  Convert to flux of potential temperature
+      !  (sec 4.3.2 in Lauritzen et al. 2022, JAMES)
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:2903]: Do you have a DOI for this reference?  We've started trying to put those in as well.

File: src/physics/cam/clubb_intr.F90 [hunk 12]
```diff
@@ -3969,27 +3961,14 @@ subroutine clubb_tend_cam( &
    ! ------------------------------------------------- !
 
    !  density
-   rho(:ncol,1:pver) = state1%pmid(:ncol,1:pver)/(rairv(:ncol,1:pver,lchnk)*state1%t(:ncol,1:pver))
-   rho(:ncol,pverp)  = state1%ps(:ncol)/(rairv(:ncol,pver,lchnk)*state1%t(:ncol,pver))
+   ! REMOVE AFTER CODE REVIEW - this rho is for midpoints except the lowest level is the surface
+   !                          - BUT this is supposed to be rho at the interface levels
+   !                          - replace with rho at mid-points using mass def, to be consistent w/ earlier def's
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:3966]: Just a reminder to remove this after all the reviewers have seen it.  I assume you will be removing the commented out lines as well.

File: src/physics/cam/clubb_intr.F90 [hunk 13]
```diff
@@ -4172,64 +4151,59 @@ subroutine clubb_tend_cam( &
...
 
-     rtpthlp_output(:ncol,:) = rtpthlp_output(:ncol,:) * 1000._r8
-     call outfld( 'RTPTHLP_CLUBB',    rtpthlp_output,          pcols, lchnk )
+     temp2d(:ncol,:) = rtm(1:ncol,1:pver)
+     call outfld( 'RTM_CLUBB',        temp2d,                 pcols, lchnk )
 
-     temp2dp(:ncol,:) = rcm(:ncol,:) * 1000._r8
-     call outfld( 'RCM_CLUBB',        temp2dp,                 pcols, lchnk )
+     temp2d(:ncol,:) = thlm(:ncol,1:pver)
+     call outfld( 'THLM_CLUBB',       temp2d,                 pcols, lchnk )
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:4178]: Since the arithmetic was removed, you can remove the copy operation and just put the thlm in the outfld call directly.  This comment applies to the rcm_in_layer below as well.

**Review by cacraigucar — COMMENTED** [review]
A few more minor points.  I think this will be ready for full review once you remove it from draft status.

**Review by cacraigucar — COMMENTED** [review]
One more general comment.  I believe that the description needs one issue number following a keyword like "fixes" to get the automation to close the issue.  @nusbaume is that correct, or can you have a list of issues?

File: src/physics/cam/clubb_intr.F90 (hunk 11 above)
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:2903]: it's still in review, so no doi yet, unfortunately. and section numbering might change. maybe we should just remove line 2903 for now?

File: src/physics/cam/clubb_intr.F90 (hunk 1 above)
Comment (bstephens82) [reply src/physics/cam/clubb_intr.F90:2590]: Resolved.

File: src/physics/cam/check_energy.F90 (hunk 2 above)
Comment (bstephens82) [reply src/physics/cam/check_energy.F90]: Resolved.

File: src/physics/cam/physpkg.F90 (hunk 3 above)
Comment (bstephens82) [reply src/physics/cam/physpkg.F90]: Resolved.

File: src/physics/cam_dev/physpkg.F90 (hunk 4 above)
Comment (bstephens82) [reply src/physics/cam_dev/physpkg.F90:90]: Resolved.

File: src/physics/cam/clubb_intr.F90 (hunk 13 above)
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:4178]: ok. same goes for existing entires before and after this line. Removed all unnecessary copy operations nearby.

File: src/physics/cam/clubb_intr.F90 (hunk 12 above)
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:3966]: ok. will remove when everyone has done a first pass.

**Comment by nusbaume** [comment]
@cacraigucar @adamrher Sadly you do need to have the "fixes" statement repeated for each issue, as well as just the issue number alone with the "#" sign (not the full URL).  

I went ahead and updated the main PR description to match these requirements, so hopefully that was ok!

**Review by gold2718 — APPROVED** [review]

**Review by peverwhee — APPROVED** [review]

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks good, but I do have some minor code clean-up requests.

File: src/physics/cam/cam_diagnostics.F90 [hunk 14]
```diff
@@ -1344,8 +1350,30 @@ subroutine diag_phys_writeout_moist(state, pbuf, p_surf_t)
       ftem(:ncol,1) = ftem(:ncol,1) + ftem(:ncol,k)
     end do
     call outfld ('TMQ     ',ftem, pcols   ,lchnk     )
+    !
+    ! Integrated vapor transport calculation
+    !
+    !compute uq*dp/g and vq*dp/g
+    ftem4(:ncol,:) = state%q(:ncol,:,1) * state%u(:ncol,:) *state%pdel(:ncol,:) * rga
+    ftem5(:ncol,:) = state%q(:ncol,:,1) * state%v(:ncol,:) *state%pdel(:ncol,:) * rga
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/cam_diagnostics.F90:1358]: OK. This does seem to be pervasive throughout this subroutine. I added in ixq / get_index_pbuf locally to the subroutine, and changed all occurrences of ```state%q(:ncol,:,1)``` to ```state%q(:ncol,:,ixq)```. I didn't try to define ixq at the module level because ixq is a intent(in) argument to one of the other subroutines in the module, which would create duplicate definitions.

File: src/physics/cam/cam_diagnostics.F90 [hunk 15]
```diff
@@ -1290,6 +1294,8 @@ subroutine diag_phys_writeout_moist(state, pbuf, p_surf_t)
     real(r8) :: ftem(pcols,pver) ! temporary workspace
     real(r8) :: ftem1(pcols,pver) ! another temporary workspace
     real(r8) :: ftem2(pcols,pver) ! another temporary workspace
+    real(r8) :: ftem4(pcols,pver) ! another temporary workspace
+    real(r8) :: ftem5(pcols,pver) ! another temporary workspace
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/cam_diagnostics.F90:1298]: replaced these with existing ftem1 and ftem2 arrays.

File: src/physics/cam_dev/physpkg.F90 [hunk 16]
```diff
@@ -2597,9 +2604,11 @@ subroutine tphysbc (ztodt, state,  &
     ! T, U, V tendency due to dynamics
     if ( nstep > dyn_time_lvls-1 ) then
        dtcore(:ncol,:pver) = (state%t(:ncol,:pver) - dtcore(:ncol,:pver))/ztodt
+       dqcore(:ncol,:pver) = (state%q(:ncol,:pver,1) - dqcore(:ncol,:pver))/ztodt
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam_dev/physpkg.F90:2607]: done

File: src/physics/cam/clubb_intr.F90 [hunk 17]
```diff
@@ -2755,12 +2721,21 @@ subroutine clubb_tend_cam( &
     !  Inputs for the momentum levels are set below setup_clubb core
     do k=1,nlev
       do i=1, ncol
-        p_in_Pa(i,k+1)         = state1%pmid(i,pver-k+1)                              ! Pressure profile
+        ! base state (dry) variables
+        p_ds_zt(i,k+1)         = state1%pmid(i,pver-k+1) &
+                                   /(1._r8 + state1%q(i,pver-k+1,ixq)*rh2o/rairv(i,pver-k+1,lchnk))
+        exner_ds_zt(i,k+1)     = (p_ds_zt(i,k+1)/p0_clubb)**(rairv(i,pver-k+1,lchnk)/cpairv(i,pver-k+1,lchnk))
+        thv_ds_zt(i,k+1)       = state1%t(i,pver-k+1)/exner_ds_zt(i,k+1)
+        rho_ds_zt(i,k+1)       = (1._r8/gravit)*(state1%pdel(i,pver-k+1) &
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:2729]: done

File: src/physics/cam/clubb_intr.F90 [hunk 18]
```diff
@@ -3969,27 +3961,14 @@ subroutine clubb_tend_cam( &
...
 
    !  density
-   rho(:ncol,1:pver) = state1%pmid(:ncol,1:pver)/(rairv(:ncol,1:pver,lchnk)*state1%t(:ncol,1:pver))
-   rho(:ncol,pverp)  = state1%ps(:ncol)/(rairv(:ncol,pver,lchnk)*state1%t(:ncol,pver))
+   ! REMOVE AFTER CODE REVIEW - this rho is for midpoints except the lowest level is the surface
+   !                          - BUT this is supposed to be rho at the interface levels
+   !                          - replace with rho at mid-points using mass def, to be consistent w/ earlier def's
+   !rho(:ncol,1:pver) = state1%pmid(:ncol,1:pver)/(rairv(:ncol,1:pver,lchnk)*state1%t(:ncol,1:pver))
+   !rho(:ncol,pverp)  = state1%ps(:ncol)/(rairv(:ncol,pver,lchnk)*state1%t(:ncol,pver))
+   rho(1:ncol,1:pver) = (1._r8/gravit)*state1%pdel(1:ncol,1:pver)/(state1%zi(1:ncol,1:pver)-state1%zi(1:ncol,2:pverp))
```
[the remark this answers is not in the document]
Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:3967]: done

File: src/physics/cam/cam_diagnostics.F90 (hunk 14 above)
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/physics/cam/cam_diagnostics.F90]: No worries, I actually only expected that you would modify the new code, so way to go above and beyond!

**Review by nusbaume — APPROVED** [review]
Looks great now, thanks!

File: src/physics/cam/physpkg.F90 [hunk 19]
```diff
@@ -1912,6 +1916,7 @@ subroutine tphysac (ztodt,   cam_in,  &
     ! store T, U, and V in buffer for use in computing dynamics T-tendency in next timestep
     do k = 1,pver
        dtcore(:ncol,k) = state%t(:ncol,k)
+       dqcore(:ncol,k) = state%q(:ncol,k,ixq)
```
Comment (cacraigucar) [inline src/physics/cam/physpkg.F90:1919]: ixq is not in scope (defined) in tphysac.  I'm working on a mod to fix this.  The cam_dev version already had the ixq defined in tphysac, which is why this was missed.

Comment (adamrher) [reply src/physics/cam/physpkg.F90:1919]: ah right, only in cam_dev/physpkg.F90 is ixq defined at the tphysac level.

File: src/physics/cam/clubb_intr.F90 [hunk 20]
```diff
@@ -4172,66 +4149,48 @@ subroutine clubb_tend_cam( &
    ! --------------------------------------------------------------------------------- !  
  
    !  Output calls of variables goes here
-   call outfld( 'RELVAR',           relvar,                  pcols, lchnk )
-   call outfld( 'RHO_CLUBB',        rho,                   pcols, lchnk )
+   call outfld( 'RELVAR',           relvar,                pcols, lchnk )
+   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),    pcols, lchnk )
```
Comment (cacraigucar) [inline src/physics/cam/clubb_intr.F90:4153]: At least two regression tests are erroring out at this location:

[11] Runtime Error: *** Arithmetic exception: Floating invalid operati[11] on - aborting
[11] /home/cacraig/cam_clubb_kitchensink/src/control/cam_history_buffers.F90, line 104: Error occurred[11]  in CAM_HISTORY_BUFFERS:HBUF_ACCUM_ADD
[11] /home/cacraig/cam_clubb_kitchensink/src/control/cam_history.F90, line 3429: Called by CAM_HISTORY:OUTFLD
[11] /home/cacraig/cam_clubb_kitchensink/src/physics/cam/clubb_intr.F90, line 4153: C[11] alled by CLUBB_INTR:CLUBB_TEND_CAM

A run can be seen at: 
/scratch/cluster/cacraig/aux_cam_nag_20220705130436/ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s.GC.aux_cam_nag_20220705130436/run

@adamrher  - Can you take a look at this?  I can check into this tomorrow if you don't solve this.  I'm guessing a mismatch in dimensions possibly.

Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:4153]: can you provide a create test command to reproduce this error?

Comment (cacraigucar) [reply src/physics/cam/clubb_intr.F90:4153]: The create_newcase used was:

 /home/cacraig/cam_clubb_kitchensink/cime/CIME/scripts/create_newcase.py --case /scratch/cluster/cacraig/aux_cam_nag_20220705130436/ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s.GC.aux_cam_nag_20220705130436 --res f10_f10_mg37 --compset QPWmaC6 --test --machine izumi --compiler nag --output-root /scratch/cluster/cacraig/aux_cam_nag_20220705130436 --workflow default --srcroot /home/cacraig/cam_clubb_kitchensink --driver nuopc --user-mods-dir /home/cacraig/cam_clubb_kitchensink/cime_config/testdefs/testmods_dirs/cam/outfrq3s --walltime 00:30:00

I know you need to remove the --test and --workflow default since you won't be in the testing suite.

Comment (cacraigucar) [reply src/physics/cam/clubb_intr.F90:4153]: > isn't there a much easier way to run this test? Say:
> 
> ./create_test ERC_D_Ln9_Vnuopc.f10_f10_mg37.QPWmaC6.izumi_nag.cam-outfrq3s
> 
> ??

Yes, you can use that command as well

Comment (adamrher) [reply src/physics/cam/clubb_intr.F90:4153]: It looks to be throwing a fit over all my new array subsetting in the outfld calls. E.g., this gives an error:
```
   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),  pcols, lchnk )
```
This does not:
```
   call outfld( 'RHO_CLUBB',        rho,                   pcols, lchnk )
```
I introduced this (1:ncol,1:pver) subsetting of arrays for about 10 different outfld calls in this PR. These arrays are of size (pcol,pverp). The problem is that clubb's grid for the mid-point levels has pverp entries, whereas CAM's mid-point grid only has pver entries, because clubb plops an additional vertical level in the subsurface. So my goal is to omit the pverp / subsurface point, and only outfld the 1:pver entries of the arrays, since they should be on CAM's  ```lev``` grid. 

@cacraigucar can you take a look at this tmrw?

Comment (gold2718) [reply src/physics/cam/clubb_intr.F90:4153]: > It looks to be throwing a fit over all my new array subsetting in the outfld calls. E.g., this gives an error:
> 
> ```
>    call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),  pcols, lchnk )
> ```

Makes sense, try:
```
   call outfld( 'RHO_CLUBB',        rho(1:ncol,1:pver),  ncol, lchnk )
```
Note the change in the third argument (which is the size of the first dimension of the second argument).

**Review by cacraigucar — APPROVED** [review]
