### PR TITLE
cam6_3_134: Update atmospheric_physics external

### LINKED ISSUE #752: Update atmospheric_physics external
### Issue Type

Externals Update

### Issue Description

We're behind on our external for atmospheric_physics.

Update to: [atmos_phys0_00_018](https://github.com/NCAR/atmospheric_physics/releases/tag/atmos_phys0_00_018)

### Will this change answers?

Yes

### Will you be implementing this yourself?

Yes

### LINKED ISSUE #802: Kessler physics using inconsistent reference pressures
### What happened?

While going through the use of CCPP standard names in our physics code, I saw that Kessler is being given a "reference" pressure that is the US standard atmosphere sea level pressure (i.e. 1013.25 hPa) to convert from the provided Exner function.  However, the Exner function itself is calculated using a reference pressure of 1000 hPa (which is also used in Klemp et al. referenced in the Kessler code).  Thus when values are calculated using the Exner function in Kessler there is an unphysical ~1.013 offset that occurs.

### What are the steps to reproduce the bug?

Look at `kessler_cam_init` in `physics/simple/kessler_cam.F90`, `kessler_init` and `kessler_run` in `atmos_phys/kessler/kessler.F90`, and `calc_exner_run` in `atmos_phys/utilities/state_converters.F90`.

### What CAM tag were you using?

cam6_3_109

### What machine were you running CAM on?

Other (please explain below)

### What compiler were you using?

Other (please specify below)

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

I will fix this issue when I bring in an updated version of the `atmospheric_physics` external (issue #752)

### PR DESCRIPTION
**Pull request by nusbaume**
This PR updates the atmospheric_physics external in CAM, which requires some source modifications on the CAM-side.  There has also been some replacement of CAM code with CCPP physics routines in order to reduce duplication.

Finally, this PR also fixes a bug found in Kessler where it was using the wrong pressure when converting to/from potential temperature via the exner function.

Fixes #752 
Fixes #802

Closes #904

### CODE REVIEW

File: src/physics/cam/geopotential.F90 [hunk 1]
```diff
@@ -107,83 +118,33 @@ subroutine geopotential_t(                                 &
...
-          end do
-!        end if
-        
+
         ! Now compute tv, zm, zi
-        
+
         do i = 1,ncol
-          tvfac   = (1._r8 + (zvir(i,k)+1.0_r8) * q(i,k,1)*qfac(i,k))*sum_dry_mixing_ratio(i,k)
+          tvfac   = 1._r8 + zvir(i,k) * q(i,k,ixq)
```
Comment (cacraigucar) [inline src/physics/cam/geopotential.F90:125]: Good catch- we tried to stamp all of these hardwired 1 a number of years ago, but obviously we didn't find them all.

File: src/physics/cam/geopotential.F90 [hunk 2]
```diff
@@ -107,83 +118,33 @@ subroutine geopotential_t(                                 &
...
       end do
+    else !Using MPAS or SE dycore
+
+      !Determine vertical coordinate type,
+      !uncomment if  FV (LR) or FV3 dycores allow for condensate loading.
+      !if ((dycore_is('LR') .or. dycore_is('FV3'))) then
+      !  lagrang = .true.
+      !else
+        lagrang = .false.
+      !end if
```
Comment (cacraigucar) [inline src/physics/cam/geopotential.F90:140]: I'm not crazy about this "uncomment this section'.  Isn't there something which we could key off of to make the appropriate selection.  I know this isn't new, but the comment is and it made me see it :-)

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: src/dynamics/se/dp_coupling.F90 [hunk 3]
```diff
@@ -686,18 +692,15 @@ subroutine derived_phys_dry(phys_state, phys_tend, pbuf2d)
...
       ! Compute initial dry static energy, include surface geopotential
-      do k = 1, pver
-         do i = 1, ncol
-            phys_state(lchnk)%s(i,k) = cpairv(i,k,lchnk)*phys_state(lchnk)%t(i,k) &
-                                     + gravit*phys_state(lchnk)%zm(i,k) + phys_state(lchnk)%phis(i)
-         end do
-      end do
+      call update_dry_static_energy_run(pver, gravit, phys_state(lchnk)%t, phys_state(lchnk)%zm,         &
+                                        phys_state(lchnk)%phis, phys_state(lchnk)%s, cpairv(:,:,lchnk),  &
+                                        errflg, errmsg)
```
Comment (cacraigucar) [inline src/dynamics/se/dp_coupling.F90:703]: As I'm resolving my comments in the NCAR/atmospheric_physics PR, I see that you did adopt the horiziontal_loop_extent dimension as it should be in CAM-SIMA.  I believe that this then will have a mismatch for this side.  I'm not sure if the dycore does the same allocations for the state variables as physics, where the variables are dimensioned by pcols.  If so, then the phys_state and cpairv variables need to be subsetted in the call, for instance `phys_state(lchnk)%t(1:ncol,:)`

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: src/utils/ccpp_constituent_prop_mod.F90 [hunk 4]
```diff
@@ -0,0 +1,190 @@
+! This module is a placeholder for the CCPP generated module of the same name
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/utils/ccpp_constituent_prop_mod.F90]: Fair point!  All `stub` comments updated accordingly.

File: src/utils/ccpp_constituent_prop_mod.F90 [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+
+   implicit none
+   private
+
+   !Define stub version of constituent properties mod
+   type, public :: ccpp_constituent_prop_ptr_t
+      logical, private :: thermo_active = .false.
+      logical, private :: water_species = .false.
+   contains
+      procedure :: standard_name     => ccpt_get_standard_name
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/utils/ccpp_constituent_prop_mod.F90]: In the actual CCPP-framework there is a `ccp` type and a `ccpt` type which points to the `ccp` object, but which has methods that are essentially the same. I am guessing I just copied the `ccpt` routines over instead of the `ccp` routines.  I've gone ahead and removed all of the extra "t"s.  

I am not 100% sure if we need to formalize a naming convention yet, simply because a lot of this is actually "hidden" from the physics routines themselves.  As long as the final public method name matches the framework then everything should work as expected.

File: src/utils/ccpp_constituent_prop_mod.F90 [hunk 6]
```diff
@@ -0,0 +1,190 @@
+! This module is a placeholder for the CCPP generated module of the same name
+module ccpp_constituent_prop_mod
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/utils/ccpp_constituent_prop_mod.F90]: Good idea!  Created a new `src/utils/cam_ccpp` directory to help better organize the source code.

File: src/physics/cam/geopotential.F90 [hunk 7]
```diff
@@ -74,28 +77,36 @@ subroutine geopotential_t(                                 &
...
+    !Determine index for water vapor mass mixing ratio
+    call cnst_get_ind('Q', ixq)
 
     !
     ! original code for backwards compatability with FV and EUL
     !
     if (.not.(dycore_is('MPAS') .or. dycore_is('SE'))) then
+
+      ! Compute zi, zm from bottom up.
+      ! Note, zi(i,k) is the interface above zm(i,k)
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/physics/cam/geopotential.F90]: Agreed, moved the comment down to just above the `do k = pver, 1, -1` line.

File: src/physics/cam/geopotential.F90 (hunk 1 above)
Comment (nusbaume) [reply src/physics/cam/geopotential.F90:124]: Thanks!  Every once in a while I get lucky and improve the code.

File: src/physics/cam/geopotential.F90 (hunk 2 above)
Comment (nusbaume) [reply src/physics/cam/geopotential.F90]: After looking at the code I realized I can just uncomment it as-is and it should work properly.  It does mean that there will be a useless dycore check done every time this subroutine is called, but I doubt it will be a big performance hit.

File: src/physics/cam/geopotential.F90 [hunk 8]
```diff
@@ -29,17 +29,18 @@ subroutine geopotential_t(                                 &
...
 ! interfaces using the input temperatures and pressures.
 !
 !-----------------------------------------------------------------------
 
-use ppgrid, only : pcols
-use air_composition, only: thermodynamic_active_species_num
-use air_composition, only: thermodynamic_active_species_idx, dry_air_species_num
+use ppgrid,                    only: pcols
+use constituents,              only: pcnst, cnst_get_ind
+use ccpp_constituent_prop_mod, only: ccpp_const_props      !CCPP constituent properties array (stub version)
```
Comment (cacraigucar) [inline src/physics/cam/geopotential.F90:42]: Still says `stub`

File: src/physics/cam/physpkg.F90 [hunk 9]
```diff
@@ -978,6 +980,10 @@ subroutine phys_init( phys_state, phys_tend, pbuf2d, cam_in, cam_out )
 
     end if
 
+    ! Initialize stub CCPP constituent properties array
```
Comment (cacraigucar) [inline src/physics/cam/physpkg.F90:983]: Still says `stub`

File: src/physics/cam_dev/physpkg.F90 [hunk 10]
```diff
@@ -947,6 +949,10 @@ subroutine phys_init( phys_state, phys_tend, pbuf2d, cam_in, cam_out )
 
     end if
 
+    ! Initialize stub CCPP constituent properties array
```
Comment (cacraigucar) [inline src/physics/cam_dev/physpkg.F90:952]: Still says `stub`

**Review by cacraigucar — CHANGES_REQUESTED** [review]

File: Externals_CAM.cfg [hunk 11]
```diff
@@ -55,9 +55,9 @@ tag = ALI_ARMS_v1.0.1
 required = True
 
 [atmos_phys]
-tag = atmos_phys0_00_011
+branch = updated_standard_names
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply Externals_CAM.cfg]: This has now been updated to point to an official tag.

File: src/physics/simple/held_suarez_cam.F90 [hunk 12]
```diff
@@ -104,8 +104,9 @@ subroutine held_suarez_tend(state, ptend, ztodt)
     ! initialize individual parameterization tendencies
     call physics_ptend_init(ptend, state%psetcols, 'held_suarez', ls=.true., lu=.true., lv=.true.)
 
-    call held_suarez_1994_run(pver, ncol, clat, state%pmid, &
-         state%u, state%v, state%t, ptend%u, ptend%v, ptend%s, errmsg, errflg)
+    call held_suarez_1994_run(pver, ncol, pref_mid_norm, clat, cappav(:,:,lchnk), cpairv(:,:,lchnk), &
```
[the remark this answers is not in the document]
Comment (nusbaume) [reply src/physics/simple/held_suarez_cam.F90]: Good catch! `ncol` has now been added to all array arguments.

File: src/physics/cam/geopotential.F90 (hunk 8 above)
Comment (nusbaume) [reply src/physics/cam/geopotential.F90]: Replaced with `CAM version`.

File: src/physics/cam/physpkg.F90 (hunk 9 above)
Comment (nusbaume) [reply src/physics/cam/physpkg.F90]: Replaced with `CAM`.

File: src/physics/cam_dev/physpkg.F90 (hunk 10 above)
Comment (nusbaume) [reply src/physics/cam_dev/physpkg.F90]: Replaced with `CAM`.

File: src/physics/simple/kessler_cam.F90 [hunk 13]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
     end do
-    
-    if (errflg == 0) then
-       call calc_exner_run(ncol, pver, cpair, rair, state%pmid, pk, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from calc_exner_run: '//trim(errmsg))
-       end if
+
+    ! Calculate Exner function:
+    call calc_exner_run(ncol, pver, cpairv(:,:,lchnk), rairv(:,:,lchnk), psurf_ref, state%pmid, pk, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:186]: These need to be subset by 1:ncol as well.  I'll look at adding something to the conversion document.

File: src/physics/simple/kessler_cam.F90 [hunk 14]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+    if (errflg /=0) then
+       call endrun('kessler_tend error: Error returned from calc_exner_run: '//trim(errmsg))
+    end if
+
+    ! Calculate potential temperature:
+    call temp_to_potential_temp_run(ncol, pver, temp, pk, th, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:192]: Add 1:ncol to this call as well

File: src/physics/simple/kessler_cam.F90 [hunk 15]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+       call endrun('kessler_tend error: Error returned from temp_to_potential_temp_run: '//trim(errmsg))
     end if
-    if (errflg == 0) then
-       call temp_to_potential_temp_run(ncol, pver, temp, pk, th, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from temp_to_potential_temp_run: '//trim(errmsg))
-       end if
+
+    ! Calculate density using ideal gas law:
+    call calc_dry_air_ideal_gas_density_run(ncol, pver, rairv(:,:,lchnk), state%pmiddry, temp, rho, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:198]: Add 1:ncol here as well

File: src/physics/simple/kessler_cam.F90 [hunk 16]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
     end if
-    if (errflg == 0) then
-       call pres_to_density_dry_run(ncol, pver, state%pmiddry, temp, rho, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from pres_to_density_dry_run: '//trim(errmsg))
-       end if
+
+    ! Convert moist air mixing ratios to dry air mixing ratios:
+    !---------------------------------------------------------
+    call wet_to_dry_water_vapor_run(ncol, pver, state%pdel, state%pdeldry, qv, qv_dry, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:205]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 17]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+    if (errflg /=0) then
+       call endrun('kessler_tend error: Error returned from wet_to_dry_water_vapor_run: '//trim(errmsg))
     end if
-    if (errflg == 0) then
-       call wet_to_dry_run(ncol, pver, state%pdel, state%pdeldry, qv, qc, qr, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from wet_to_dry_run: '//trim(errmsg))
-       end if
+
+    call wet_to_dry_cloud_liquid_water_run(ncol, pver, state%pdel, state%pdeldry, qc, qc_dry, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:210]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 18]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+       call endrun('kessler_tend error: Error returned from wet_to_dry_cloud_liquid_water_run: '//trim(errmsg))
     end if
-    if (errflg == 0) then
-       call kessler_run(ncol, pver, ztodt, lyr_surf, lyr_toa,        &
-                        rho, state%zm, pk, th, qv, qc, qr, prec_sed, relhum, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from kessler_run: '//trim(errmsg))
-       end if
+
+    call wet_to_dry_rain_run(ncol, pver, state%pdel, state%pdeldry, qr, qr_dry, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:215]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 19]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
-       call potential_temp_to_temp_run(ncol, pver, th, pk, temp, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from potential_temp_to_temp_run: '//trim(errmsg))
-       end if
+    !---------------------------------------------------------
+
+    ! Run Kessler physics scheme:
+    call kessler_run(ncol, pver, ztodt, lyr_surf, lyr_toa, cpairv(:,:,lchnk), &
+                     rairv(:,:,lchnk), rho, state%zm, pk, th, qv_dry, qc_dry, &
+                     qr_dry, prec_sed, relhum, scheme_name, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:224]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 20]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+       call endrun('kessler_tend error: Error returned from kessler_run: '//trim(errmsg))
     end if
-    if (errflg == 0) then
-       call dry_to_wet_run(ncol, pver, state%pdel, state%pdeldry, qv, qc, qr, errmsg, errflg)
-       if (errflg /=0) then
-          call endrun('kessler_tend error: Error returned from dry_to_wet_run: '//trim(errmsg))
-       end if
+
+    ! Calculate air temperature from potential temperature:
+    call potential_temp_to_temp_run(ncol, pver, th, pk, temp, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:230]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 21]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+    if (errflg /=0) then
+       call endrun('kessler_tend error: Error returned from potential_temp_to_temp_run: '//trim(errmsg))
+    end if
+
+    ! Convert dry air mixing ratios to moist air mixing ratios:
+    !---------------------------------------------------------
+    call dry_to_wet_water_vapor_run(ncol, pver, state%pdel, state%pdeldry, qv_dry, qv, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:237]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 22]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+    if (errflg /=0) then
+       call endrun('kessler_tend error: Error returned from dry_to_wet_water_vapor_run: '//trim(errmsg))
+    end if
+
+    call dry_to_wet_cloud_liquid_water_run(ncol, pver, state%pdel, state%pdeldry, qc_dry, qc, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:242]: Add 1:ncol here

File: src/physics/simple/kessler_cam.F90 [hunk 23]
```diff
@@ -169,63 +172,90 @@ subroutine kessler_tend(state, ptend, ztodt, pbuf)
...
+    if (errflg /=0) then
+       call endrun('kessler_tend error: Error returned from dry_to_wet_cloud_liquid_water_run: '//trim(errmsg))
+    end if
+
+    call dry_to_wet_rain_run(ncol, pver, state%pdel, state%pdeldry, qr_dry, qr, errmsg, errflg)
```
Comment (cacraigucar) [inline src/physics/simple/kessler_cam.F90:247]: Add 1:ncol here

**Review by cacraigucar — CHANGES_REQUESTED** [review]
We had some committed code which had the 1:ncol error as well as more places you added code.  This should be all of them in this PR.  

Basically the rule of thumb is that any run methods which have arrays dimensioned by pcols in CAM, need to have that subsetted by 1:ncol in the call.   (BTW, my ZM conversion doesn't have pcols removed from the lower layer yet - that will come with the metadata creation step - I went and checked!)

File: src/physics/simple/kessler_cam.F90 (hunk 14 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 15 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 16 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 18 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 19 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 20 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 21 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 22 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

File: src/physics/simple/kessler_cam.F90 (hunk 23 above)
Comment (nusbaume) [reply src/physics/simple/kessler_cam.F90]: Done.

**Review by cacraigucar — APPROVED** [review]

File: src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90 [hunk 24]
```diff
@@ -0,0 +1,190 @@
...
+      ! Pass back thermo active property:
+      val_out = this%thermo_active
+
+      ! Provide err values if requested:
+      if(present(errcode)) then
+         errcode = 0
+      end if
+      if(present(errmsg)) then
+         errmsg = 'Still Not Used!'
+      end if
```
Comment (peverwhee) [inline src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90:71]: I get why this error message exists for ccp_get_standard_name, but why these other subroutines?

File: src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90 [hunk 25]
```diff
@@ -0,0 +1,190 @@
...
+
+   end subroutine ccp_get_standard_name
```
Comment (peverwhee) [inline src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90:50]: Why do we need this at all?

**Review by peverwhee — APPROVED** [review]
A couple of non-critical questions/comments about the constituent_prop_mod stub.

**Comment by nusbaume** [comment]
@jtruesdal just pinging you about reviewing this PR when you get the chance!

**Review by jtruesdal — APPROVED** [review]
Thanks for the ping.  Looks good.

File: src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90 (hunk 24 above)
Comment (nusbaume) [reply src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90]: Good point!  I've changed the error messages to just be empty strings in order to avoid confusion (and to hint that CAM doesn't actually use these specific error messages).  If however you think I should actually be generating and using an error message variable here and in CAM then please let me know.

File: src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90 (hunk 25 above)
Comment (nusbaume) [reply src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90:50]: Because in CAM we are building (but not running) the CCPP-ized version of `qneg`, which uses the `standard_name` constituent property, which in-turn is pointing to this subroutine (in the same way that the real CCPP constituents object points to a subroutine).  

So without a subroutine like this the CAM build will fail.  I could simplify it further, but I also imagine in the future we'll have physics schemes which will really need to use this subroutine, or something like it, which is why I kept it in there.

Hopefully that makes sense?  If you still think it would be a good idea to simplify it even further then just let me know.
