### PR TITLE
cam6_4_169: CARMA with RRTMGP

### LINKED ISSUE #1430: CARMA does not run with RRTMGP
### What happened?

In the latest development version, CARMA does not run with RRTMGP using cam7 physics:
configure ERROR: The CARMA microphysics package does not currently work with RRTMGP

The problem is that radiation information is not initialized before  carma create, which causes a problem. 

### What are the steps to reproduce the bug?

Current test case:
/glade/work/tilmes/derecho/cesm3/f.e30.alpha07e.ctsm5.3.075.sp.ne30pg3_93L_FCARMAnudged.T4S.2016.001

### What CAM tag were you using?

alpha07e

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/work/tilmes/derecho/cesm3/f.e30.alpha07e.ctsm5.3.075.sp.ne30pg3_93L_FCARMAnudged.T4S.2016.001

### Will you be addressing this bug yourself?

No

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by fvitt**
This enables the use of CARMA with RRTMGP / cam7 physics.

Closes #1430 

Also includes some changes to improve performance of CARMA.

### CODE REVIEW

File: src/chemistry/aerosol/aerosol_state_mod.F90 [hunk 1]
```diff
@@ -333,15 +331,13 @@ subroutine loadaer( self, aero_props, istart, istop, k,  m, cs, phase, &
     real(r8) :: specdens, spechygro
     character(len=aero_name_len) :: spectype
 
-    real(r8) :: vol(istart:istop) ! aerosol volume mixing ratio
-    integer  :: i, l
+    real(r8) :: vol(ncol,nlev) ! aerosol volume mixing ratio
+    integer  :: i, k, l
```
Comment (peverwhee) [inline src/chemistry/aerosol/aerosol_state_mod.F90]: looks like you no longer need i or k in this routine

**Review by peverwhee — APPROVED** [review]
one tiny thing, but not enough to hold up my approval.

File: src/chemistry/aerosol/aerosol_state_mod.F90 (hunk 1 above)
Comment (fvitt) [reply src/chemistry/aerosol/aerosol_state_mod.F90]: fixed
