### PR TITLE
cam6_3_065:  Misc tag for Gravity Wave, contrail, cam_snapshot and SE dycore writes

### LINKED ISSUE #362: ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail  does not run for cesm2_3_alpha02d
ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail is failing with the following error.

99:MPT ERROR: Rank 99(g:99) received signal SIGFPE(8).
99:     Process ID: 35145, Host: r9i7n8, Program: /glade/scratch/fischer/t/cesm2_3_alpha02d_alpha_intel/ERP_D_Ln9.f09_f09_mg17.FSD.cheyenne_intel.cam-outfrq9s_contrail.GC.c2_3_a2d_int/bld/cesm.exe
99:     MPT Version: HPE MPT 2.21  11/28/19 04:21:40
99:
99:MPT: --------stack traceback-------
99:OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.

### LINKED ISSUE #606: Fix cam_snapshot
### What happened?

running CAM snapshot files results in fields being filled with zeroes

### What are the steps to reproduce the bug?

Make any cam_snapshot run

### What CAM tag were you using?

cam6_3_063

### What machine were you running CAM on?

CGD machine (e.g. izumi)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

To fix the bug in src/control/cam_snapshot_common.F90:

change: `cam_snapshot_before_num `and `cam_snapshot_after_num `inputs to
`cam_snapshot_before_num_in `and `cam_snapshot_after_num_in`.  

Then assign:
 `cam_snapshot_before_num= cam_snapshot_before_num_in`
`cam_snapshot_after_num = cam_snapshot_after_num_in`

### LINKED ISSUE #610: Correct logic for log print statement
### Issue Type

Code Clean-up

### Issue Description

In file global_norms_mod.F90 is code:

    if (hybrid%masterthread .and. nu_set .or. div_set .or. lev_set) then                                                                                                               
       write(iulog,* )""                                                                                                                                                               
       write(iulog,* )"Sponge layer del4 coefficient defaults based on model top location:"                                                                                            
    end if                                                                                       

This is printing from every task, I don't think this is intended and the if block should be:
    if (hybrid%masterthread .and. (nu_set .or. div_set .or. lev_set)) then                                                                                                               
                                                                             

### Will this change answers?

No

### Will you be implementing this yourself?

No

### PR DESCRIPTION
**Pull request by cacraigucar**
Issues being closed:

Closes #362 (contrail bug fix)
Closes #610  (SE dycore writes)
Closes #606 (cam_snapshot fix)

PRs being closed:
Closes #535 (contrail bug fix)
Closes #447 (GW diags)

Note to reviewers:  #535 and #447 were already reviewed.  The only unreviewed files are:  cam_snapshot_common.F90 and global_norms_mod.F90.  Also note that most of the changes in these two files are whitespace.  The actual code changes are minimal

### CODE REVIEW

File: src/dynamics/se/dycore/global_norms_mod.F90 [hunk 1]
```diff
@@ -639,7 +639,7 @@ subroutine print_cfl(elem,hybrid,nets,nete,dtnu,ptop,pmid,&
          write(iulog, '(a,e9.2)')   '  sponge_del4_nu_div_fac = ',sponge_del4_nu_div_fac
     if (hybrid%masterthread.and.lev_set) &
          write(iulog, '(a,i0)')   '  sponge_del4_lev        = ',sponge_del4_lev
-    write(iulog,* )""
+    if ((hybrid%masterthread) write(iulog,* )""
```
Comment (nusbaume) [inline src/dynamics/se/dycore/global_norms_mod.F90:642]: Would it make more sense to have this whole section of `write` statements inside a single `if (hybrid%masterthread) then` check?  Otherwise it seems like we are repeatedly doing the same check multiple times.

**Review by nusbaume — APPROVED** [review]
Looks good!  Just one optional code clean-up request.

File: src/dynamics/se/dycore/global_norms_mod.F90 (hunk 1 above)
Comment (cacraigucar) [reply src/dynamics/se/dycore/global_norms_mod.F90:642]: I will leave this up to @jtruesdal as he was the creator of this code.

Comment (gold2718) [reply src/dynamics/se/dycore/global_norms_mod.F90:642]: I think it is worth doing the cleanup.

**Review by gold2718 — CHANGES_REQUESTED** [review]

File: src/dynamics/se/dycore/global_norms_mod.F90 (hunk 1 above)
Comment (jtruesdal) [reply src/dynamics/se/dycore/global_norms_mod.F90:642]: Yes. I agree please clean this up as Jesse is recommending.

**Review by jtruesdal — APPROVED** [review]

File: src/dynamics/se/dycore/global_norms_mod.F90 (hunk 1 above)
Comment (cacraigucar) [reply src/dynamics/se/dycore/global_norms_mod.F90]: Made the change

Comment (nusbaume) [reply src/dynamics/se/dycore/global_norms_mod.F90]: Just for the sake of completeness (and probably annoyance) does it make sense to include the:

`write(iulog,*) ": sponge layer viscosity scaling factor"`

line just below that code block inside the new if statement as well?

Comment (gold2718) [reply src/dynamics/se/dycore/global_norms_mod.F90]: I would say yes but do not see how this print statement provides any information. Maybe in the past, the relevant values were printed but no they are not so I would remove it. @jtruesdal? @PeterHjortLauritzen?

**Review by gold2718 — CHANGES_REQUESTED** [review]
I'm taking myself off the re-review list for now since all of my requested changes have _not_ been made.

**Review by peverwhee — APPROVED** [review]
