### PR TITLE
Bug fixes and kill switch for WACCM-SE issue

### LINKED ISSUE #206: CAM_ROOT not correctly set in test_driver.sh
Replace line 105 with:
export CAM_ROOT="$( dirname $( dirname $( cd ${test_dir}; pwd -P ) ) )"

### LINKED ISSUE #213: FSCAM is failing prealpha test
This test is failing.

SMS_D_Ln9.T42_T42.FSCAM.cheyenne_intel.cam-scam_mpace_outfrq9s

Looks like it started failing at cam6_2_046.

Error message is

err=Smartmatch is experimental at /glade/u/home/fischer/code/cesm2_2_alpha06f/components/cam/bld/perl5lib/Build/ChemNamelist.pm line 274.
CAM build-namelist - ERROR: Invalid namelist variable in '-infile' /glade/scratch/fischer/t/cesm2_2_alpha06f_alpha_intel/SMS_D_Ln9.T42_T42.FSCAM.cheyenne_intel.cam-scam_mpace_outfrq9s.GC.c2_2_a6f_int/Buildconf/camconf/namelist.
 ERROR: in _validate_pair (package Build::NamelistDefinition): Variable name scmlat not found in /glade/u/home/fischer/code/cesm2_2_alpha06f/components/cam/bld/namelist_files/namelist_definition.xml'
  File "/glade/u/home/fischer/code/cesm2_2_alpha06f/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 797, in _run_catch_exceptions
    return run(test)
  File "/glade/u/home/fischer/code/cesm2_2_alpha06f/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 724, in _setup_phase
    expect(cmdstat in [0, TESTS_FAILED_ERR_CODE], "Fatal error in case.cmpgen_namelists: {}".format(output))
  File "/glade/u/home/fischer/code/cesm2_2_alpha06f/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 137, in expect
    raise exc_type(msg)

My guess is Steve removed a little bit too much.

### LINKED ISSUE #214: FCHIST test fails for ocnemis
Test is: `SMS_D_Ln9.f09_f09_mg17.FCHIST.cheyenne_intel.cam-outfrq9s_ocnemis`

Error message is:
```
0: GETFIL: FAILED to get /glade/scratch/fischer/inputdata/atm/cam/chem/ocnexch/Csw
0: _DMS_HiResML_f09f09_1990_2019_20190616a.nc
```

Cause is not listing `csw_specifier` as a special variable in `check_input_files`.

### PR DESCRIPTION
**Pull request by gold2718**
- Fix test_driver root directory search
- Fix usermods for SCAM files
- Add csw_specifier to special list of filename-containing name list variables
- Add kill switch for se_molecular_diff > 0

fixes #213 
fixes #214 
fixes #206 
addreses #208

### CODE REVIEW

File: bld/build-namelist [hunk 1]
```diff
@@ -4231,9 +4231,10 @@ sub check_input_files {
     # Treat special cases...
 
     # These namelist variables are arrays of strings.
-    my @vars = qw(aircraft_specifier ext_frc_specifier srf_emis_specifier mode_defs
-                  rad_climate rad_diag_1 rad_diag_2 rad_diag_3 rad_diag_4 rad_diag_5
-                  rad_diag_6 rad_diag_7 rad_diag_8 rad_diag_9 rad_diag_10);
+    my @vars = qw(aircraft_specifier csw_specifier ext_frc_specifier
+                  rad_climate rad_diag_1 rad_diag_2 rad_diag_3 rad_diag_4
+                  rad_diag_5 rad_diag_6 rad_diag_7 rad_diag_8 rad_diag_9
+                  rad_diag_10 srf_emis_specifier mode_defs);
```
Comment (fvitt) [inline bld/build-namelist:4237]: Is this sufficient for fixing the issue of the csw_specifier files not listed in cam.input_data_list?  How well was this tested?  In my test I found I needed changes to the perl parsing code to deal with white spaces surrounding the multiplier preceding the filepath.

File: src/dynamics/se/dyn_comp.F90 [hunk 2]
```diff
@@ -302,6 +302,10 @@ subroutine dyn_readnl(NLFileName)
    call MPI_bcast(se_raytau0, 1, mpi_real8, masterprocid, mpicom, ierr)
    call MPI_bcast(se_molecular_diff, 1, mpi_real8, masterprocid, mpicom, ierr)
 
+   if (se_molecular_diff > 0.0_r8) then
+      call endrun('dyn_readnl: se_molecular_diff must be zero for CESM2.2')
```
Comment (cacraigucar) [inline src/dynamics/se/dyn_comp.F90:306]: I would either say CESM2.2.0 (since we hope to have it fixed in CESM2.2.1) or a completely different wording:
('dyn_readnl: Current bug using molecular_diffusion in CAM-SE.  This option is temporarily disabled')

**Review by cacraigucar — APPROVED** [review]

File: bld/build-namelist (hunk 1 above)
Comment (gold2718) [reply bld/build-namelist:4237]: > Is this sufficient for fixing the issue of the csw_specifier files not listed in cam.input_data_list? How well was this tested?

Hmm. I ran the test which passes and verified that the two quantities were added correctly to the cam.input_data_list but now I see that the entries are not actually the filenames.

I will look into the changes you suggested.

**Review by nusbaume — APPROVED** [review]
