### PR TITLE
part of cam6_4_123: Fix the CAM+RRTMGP GPU interface bug

### LINKED ISSUE #1383: New RRTMGP library version fails with nvhpc
### Fixes from Jian:
1. [ccs_config_cesm1.0.59](https://github.com/ESMCI/ccs_config_cesm/releases/tag/ccs_config_cesm1.0.59)
2. https://github.com/ESCOMP/CAM/pull/1386

### What happened?

cam6_4_114 brought in the latest RRTMGP library (updating from v1.7 to v1.9.2). I have confimed that v1.8 does not produce the error. [Here](https://github.com/earth-system-radiation/rte-rrtmgp/compare/v1.8...v1.9.2) is what's new since v1.8.

The nvhpc aux_cam regression test fails with the following error:
```
ERROR: Longwave down sent from the atmosphere model is negative or zero
```

### What are the steps to reproduce the bug?

1. Check out CAM tag cam6_4_114
2. Run the nvhpc test on derecho: `env BL_TESTDIR=/glade/campaign/cesm/community/amwg/cam_baselines/cam6_4_114_nvhpc CAM_FC=nvhpc  ./test_driver.sh -f`
3. Observe the failing test in your scratch directory.

### What CAM tag were you using?

cam6_4_114

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

NVHPC

### Path to a case directory, if applicable

/glade/derecho/scratch/cacraig/aux_cam_nvhpc_20250905161547/ERS_Ln9.ne30pg3_ne30pg3_mt232.FHISTC_LTso.derecho_nvhpc.cam-outfrq9s_gpu_default.GC.aux_cam_nvhpc_20250905161547

### Will you be addressing this bug yourself?

Yes, but I will need some help

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by sjsprecious**
fix #1383 

Thanks @RobertPincus for providing the RRTMGP GPU unit tests at:
- https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/examples/rfmip-clear-sky/rrtmgp_rfmip_lw.F90
- https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/examples/rfmip-clear-sky/rrtmgp_rfmip_sw.F90
- https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/examples/all-sky/rrtmgp_allsky.F90
- https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/tests/check_variants.F90
- https://github.com/earth-system-radiation/rte-rrtmgp/blob/main/tests/check_equivalence.F90

which helps me figure out what is wrong in the CAM+RRTMGP interface.

It is better to look at those examples in details and do similar data transfer for other variables in the future.

### CODE REVIEW

File: src/physics/rrtmgp/radiation.F90 [hunk 1]
```diff
@@ -1200,7 +1199,7 @@ subroutine radiation_tend( &
                ! diagnostic aerosol output.
                call rrtmgp_set_aer_sw( &
                   icall, state, pbuf, nday, idxday, nnite, idxnite, aer_sw)
-                  
+
```
Comment (peverwhee) [inline src/physics/rrtmgp/radiation.F90]: nitpick, but can you remove this white space?

**Review by peverwhee — APPROVED** [review]
thanks @sjsprecious ! If you get a chance, there's some whitespace that can be removed, but otherwise looks good to me. @cacraigucar will bring it into an upcoming miscellaneous tag.

File: src/physics/rrtmgp/radiation.F90 (hunk 1 above)
Comment (sjsprecious) [reply src/physics/rrtmgp/radiation.F90]: Sure. Just removed it.

**Review by cacraigucar — CHANGES_REQUESTED** [review]
Courtney just added that this PR should also include the ccs_config tag that supports RRTMGP

**Comment by sjsprecious** [comment]
> Courtney just added that this PR should also include the ccs_config tag that supports RRTMGP

Thanks @cacraigucar. Should the ccs_config tag be updated in this PR https://github.com/ESCOMP/CAM/pull/1384 instead?

**Comment by sjsprecious** [comment]
@cacraigucar I updated the ccs_config tag to the latest one with RRTMGP fix as we discussed.
