### PR TITLE
cam6_3_159: Diagnostic rainbows and GPU fixes in PUMAS microphysics

### LINKED ISSUE #683: Add Diagnostic Rainbow Calculation
### What is the feature/what would you like to discuss?

I have ready a diagnostic calculation for rainbows. It adds 2 optional history fields in the micro_pumas_cam interface (both cam6 and cam_dev versions). The code is purely diagnostic and does not change answers. A paper is being written on this now.  I've ported it up to the head of the CAM trunk (testing that now, cam6_3_082), but will need some help making the pull request.

### Is there anyone in particular you want to be part of this conversation?

@Katetc 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

### PR DESCRIPTION
**Pull request by Katetc**
Fixes #683 Add Diagnostic Rainbow Calculation
Partially addresses #1007 Broken PUMAS GPU code and GPU regression test  by bringing in an updated PUMAS external tag with fixed GPU code. However, the needed ccs_config tag ( ccs_config_cesm0.0.99 ) caused a failure in the single column tests right now. So the updates to the ccs_config external will be left for the next GPU fixing tag.

RAINBOWS!!! I'M NOT KIDDING!!!!111!
Also a new PUMAS tag that fixes GPU OpenACC calls. B4b

Does not change answers.

### CODE REVIEW

**Review by andrewgettelman — APPROVED** [review]
Thanks Kate. This looks good. I ran with CAM and CAM_DEV and verify that I can reproduce the results I was expecting. Good from my side.

File: src/physics/cam/micro_pumas_cam.F90 [hunk 1]
```diff
@@ -3117,6 +3208,68 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+         rval=1.0_r8
+      else
+         rval=0.0_r8
+      end if
+      
+!Now can find conditions for a rainbow:
+! Maximum cloud cover (CLDTOT) < 0.5
+! 48 < SZA < 90
+! freqr (below rb_pmin) > 0.25
+! Spome rain (liquid > 1.e-6 kg/kg, convective precip > 1.e-7 m/s
```
Comment (nusbaume) [inline src/physics/cam/micro_pumas_cam.F90:3256]: Typo (`Spome` -> `Some`).

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 2]
```diff
@@ -13,6 +13,11 @@ module micro_pumas_cam
                           latvap, latice, mwh2o
 use phys_control,   only: phys_getopts, use_hetfrz_classnuc
 
+use shr_const_mod,  only: pi => shr_const_pi
+use time_manager,   only: get_curr_date, get_curr_calday
+use phys_grid,      only: get_rlat_all_p, get_rlon_all_p
+use orbit,          only: zenith
+use cam_logfile,    only: iulog
```
Comment (nusbaume) [inline src/physics/cam_dev/micro_pumas_cam.F90:20]: This line isn't needed because `iulog` is already being brought in below.

File: src/physics/cam/micro_pumas_cam.F90 [hunk 3]
```diff
@@ -1828,6 +1843,35 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+! Rainbow frequency and fraction for output
+
+   real(r8) :: rbfreq(state%psetcols)
+   real(r8) :: rbfrac(state%psetcols)
+
+!Rainbows: parameters
+
+   real(r8), parameter :: rb_rmin  =1.e-6_r8                    ! Strat Rain threshold (mixing ratio)
+   real(r8), parameter :: rb_rcmin = 5._r8/(86400._r8*1000._r8) ! Conv Rain Threshold (mm/d--> m/s)
+   real(r8), parameter :: rb_pmin =85000.                       ! Minimum pressure for surface layer
```
Comment (nusbaume) [inline src/physics/cam/micro_pumas_cam.F90:1865]: I would include the `_r8` here:

```suggestion
   real(r8), parameter :: rb_pmin =85000._r8                    ! Minimum pressure for surface layer
```

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 4]
```diff
@@ -1924,6 +1940,35 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+! Rainbow frequency and fraction for output
+
+   real(r8) :: rbfreq(state%psetcols)
+   real(r8) :: rbfrac(state%psetcols)
+
+!Rainbows: parameters
+
+   real(r8), parameter :: rb_rmin  =1.e-6_r8                    ! Strat Rain threshold (mixing ratio)
+   real(r8), parameter :: rb_rcmin = 5._r8/(86400._r8*1000._r8) ! Conv Rain Threshold (mm/d--> m/s)
+   real(r8), parameter :: rb_pmin =85000.                       ! Minimum pressure for surface layer
```
Comment (nusbaume) [inline src/physics/cam_dev/micro_pumas_cam.F90:1962]: I would include the `_r8` here:

```suggestion
   real(r8), parameter :: rb_pmin =85000._r8                    ! Minimum pressure for surface layer
```

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 5]
```diff
@@ -1924,6 +1940,35 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+   real(r8), parameter :: deg2rad = pi/180._r8            ! Conversion factor
+   integer :: top_idx  !Index for top level below rb_pmin
+   real(r8) :: convmx
+   real(r8) :: cldmx
+   real(r8) :: frlow
+   real(r8) :: cldtot
+   real(r8) :: rmax
+   real(r8) :: rval
```
Comment (nusbaume) [inline src/physics/cam_dev/micro_pumas_cam.F90:1970]: I would make `rval` a logical instead of a real, as that is how it is being used.

File: src/physics/cam/micro_pumas_cam.F90 [hunk 6]
```diff
@@ -2128,6 +2215,10 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
       state_loc_numgraup(:ncol,:) = 0._r8
    end if
 
+   ! Zero out diagnostic  out arrays
```
Comment (nusbaume) [inline src/physics/cam/micro_pumas_cam.F90:2218]: I might update this comment to match the one in cam_dev:

```suggestion
   ! Zero out diagnostic rainbow arrays
```

File: src/physics/cam_dev/micro_pumas_cam.F90 [hunk 7]
```diff
@@ -3246,6 +3339,70 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+         rval=1.0_r8
+      else
+         rval=0.0_r8
+      end if
+      
+!Now can find conditions for a rainbow:
+! Maximum cloud cover (CLDTOT) < 0.5
+! 48 < SZA < 90
+! freqr (below rb_pmin) > 0.25
+! Spome rain (liquid > 1.e-6 kg/kg, convective precip > 1.e-7 m/s
```
Comment (nusbaume) [inline src/physics/cam_dev/micro_pumas_cam.F90:3388]: Typo (`Spome` -> `Some`).

**Review by nusbaume — CHANGES_REQUESTED** [review]
Looks good!  Just have a few minor change requests (it looks like a lot simply because I repeated the same comments for both cam and cam_dev).

File: src/physics/cam/micro_pumas_cam.F90 [hunk 8]
```diff
@@ -1828,6 +1843,35 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
    real(r8), parameter :: mucon  = 5.3_r8            ! Convective size distribution shape parameter
    real(r8), parameter :: deicon = 50._r8            ! Convective ice effective diameter (meters)
 
+   ! Rainbows: solar zenit angle (SZA)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90]: Fixed

File: src/physics/cam/micro_pumas_cam.F90 [hunk 9]
```diff
@@ -1828,6 +1843,35 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+   real(r8), parameter :: rb_rcmin = 5._r8/(86400._r8*1000._r8) ! Conv Rain Threshold (mm/d--> m/s)
+   real(r8), parameter :: rb_pmin =85000.                       ! Minimum pressure for surface layer
+   real(r8), parameter :: deg2rad = pi/180._r8            ! Conversion factor
+   integer :: top_idx  !Index for top level below rb_pmin
+   real(r8) :: convmx
+   real(r8) :: cldmx
+   real(r8) :: frlow
+   real(r8) :: cldtot
+   real(r8) :: rmax
+   real(r8) :: rval
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90]: Made it a logical

File: src/physics/cam/micro_pumas_cam.F90 (hunk 1 above)
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90]: Fixed

File: src/physics/cam_dev/micro_pumas_cam.F90 (hunk 2 above)
Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90]: Removed

File: src/physics/cam_dev/micro_pumas_cam.F90 (hunk 4 above)
Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90]: Fixed

File: src/physics/cam_dev/micro_pumas_cam.F90 (hunk 5 above)
Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90]: Made it a logical

File: src/physics/cam/micro_pumas_cam.F90 (hunk 6 above)
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90]: Fixed

File: src/physics/cam_dev/micro_pumas_cam.F90 (hunk 7 above)
Comment (Katetc) [reply src/physics/cam_dev/micro_pumas_cam.F90]: Fixed

**Review by nusbaume — APPROVED** [review]
Everything looks great to me now, thanks!

File: src/physics/cam/micro_pumas_cam.F90 [hunk 10]
```diff
@@ -3123,6 +3213,64 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
...
+      
+! Find levels in surface layer
+      do k = top_lev, pver
+         if (state%pmid(i,k) > rb_pmin) then     
+            top_idx = min(k,top_idx)
+         end if 
+      end do 
+            
+!fractional precip: use maximum in surface layer
+
```
Comment (cacraigucar) [inline src/physics/cam/micro_pumas_cam.F90:3237]: Is the code for this comment gone?

**Review by cacraigucar — CHANGES_REQUESTED** [review]
My comments in cam/micro_pumas_cam.F90 also apply to cam_dev/micro_pumas_cam.F90

File: src/physics/cam/micro_pumas_cam.F90 [hunk 11]
```diff
@@ -1834,6 +1848,35 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
    real(r8), parameter :: mucon  = 5.3_r8            ! Convective size distribution shape parameter
    real(r8), parameter :: deicon = 50._r8            ! Convective ice effective diameter (meters)
 
+   ! Rainbows: solar zenith angle (SZA)
+   real(r8), dimension(state%psetcols)  :: &
+         zen_angle, &                                      ! solar zenith angles
+         rlats, rlons                                      ! chunk latitudes and longitudes (radians)
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90]: I agree. Updated the variable declarations here in both files.

File: src/physics/cam/micro_pumas_cam.F90 [hunk 12]
```diff
@@ -3123,6 +3213,64 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
 
    racau_grid = min(racau_grid, 1.e10_r8)
 
+!-----------------------------------------------------------------------
+! Diagnostic Rainbow Calculation. Seriously.
+!-----------------------------------------------------------------------
+! Converted Python code in a loop....
```
[the remark this answers is not in the document]
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90]: Removed this comment in both files

**Review by cacraigucar — APPROVED** [review]

File: src/physics/cam/micro_pumas_cam.F90 [hunk 13]
```diff
@@ -3215,8 +3215,9 @@ subroutine micro_pumas_cam_tend(state, ptend, dtime, pbuf)
 !-----------------------------------------------------------------------
 ! Diagnostic Rainbow Calculation. Seriously.
 !-----------------------------------------------------------------------
-      
-   do i = 1, ncol
+
+! Rainbows currently calculated on the grid, not subcolumn specific
+   do i = 1, ngrdcol
```
Comment (sjsprecious) [inline src/physics/cam/micro_pumas_cam.F90:3220]: If I do not use SCM or SILHS (e.g., just the default F2000 compset), does `ngrdcol` equal to `ncol` in this case?

File: Externals.cfg [hunk 14]
```diff
@@ -1,5 +1,5 @@
 [ccs_config]
-tag = ccs_config_cesm0.0.99
+tag = ccs_config_cesm0.0.85
```
Comment (sjsprecious) [inline Externals.cfg:2]: By changing the tag from `ccs_config_cesm0.0.99` to `ccs_config_cesm0.0.85`, the PUMAS GPU code won't be compiled correctly. Will the `ccs_config_cesm0.0.99` tag be brought separately later?

File: src/physics/cam/micro_pumas_cam.F90 (hunk 13 above)
Comment (Katetc) [reply src/physics/cam/micro_pumas_cam.F90:3220]: If subcolumns are not on (SILHS or any other subcolumn source) then ngrdcol is equal to ncol. The SCM issue was a result of the ccs_config tag, but I'm not sure why.

File: Externals.cfg (hunk 14 above)
Comment (Katetc) [reply Externals.cfg:2]: The ccs_config_cesm0.0.99 tag was causing the single column model test to fail. I'm not sure why, and I don't think it's in the scope of this tag to figure it out. When you work with Brian to bring in the GPU test suite, hopefully you can find and address the problem. Or, if somebody else updates the externals for CAM, they will need to fix this test. I will update the description to note this.

Comment (sjsprecious) [reply Externals.cfg:2]: Oh, thanks for the clarification. Do you have the steps to reproduce the failed single column model test?

File: src/physics/cam/micro_pumas_cam.F90 (hunk 13 above)
Comment (sjsprecious) [reply src/physics/cam/micro_pumas_cam.F90:3220]: Thanks for the clarification. That is good to know.

**Comment by cacraigucar** [comment]
@Katetc - Which test is the failing scm test?  I would suggest you add a prealpha test for it as well, so that when @fischer-ncar  updates the ccs_config (which I think he has already done, or may be doing with the next alpha tag), that the test fails at that level.  I assume that when you say scm, this is a SCAM test.  We want to make sure that we don't break SCAM with this next beta tag.

**Comment by Katetc** [comment]
> @Katetc - Which test is the failing scm test? I would suggest you add a prealpha test for it as well, so that when @fischer-ncar updates the ccs_config (which I think he has already done, or may be doing with the next alpha tag), that the test fails at that level. I assume that when you say scm, this is a SCAM test. We want to make sure that we don't break SCAM with this next beta tag.

HI Cheryl, this test fails with the newest ccs_config tag: SCT_D_Ln7.T42_T42_mg17.QPC5.derecho_intel.cam-scm_prep and passes with the current one. So I'm rolling back the ccs_config tag in this PR. I'll open an issue about this. And I can add a prealpha marking to this test as well.

**Comment by Katetc** [comment]
I have added this issue to be addressed regarding the ccs_config tag: https://github.com/ESCOMP/CAM/issues/1017

**Comment by Katetc** [comment]
I have added this issue to be addressed regarding unexpected test DIFFs for HEMCO: https://github.com/ESCOMP/CAM/issues/1018
